// Code generated by "stringer -type=SourceKind -output=internal/cfg/sourcekind_string.go internal/cfg/value.go"; DO NOT EDIT.

package cfg

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SourceUnknown-0]
	_ = x[SourceOverride-1]
	_ = x[SourceEnv-2]
	_ = x[SourceConfigFile-3]
	_ = x[SourceDefault-4]
}

const _SourceKind_name = "SourceUnknownSourceOverrideSourceEnvSourceConfigFileSourceDefault"

var _SourceKind_index = [...]uint8{0, 13, 27, 36, 52, 65}

func (i SourceKind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_SourceKind_index)-1 {
		return "SourceKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SourceKind_name[_SourceKind_index[idx]:_SourceKind_index[idx+1]]
}
