with-expecter: True
dir: ./core/mocks
issue-845-fix: True
resolve-type-alias: False
disable-version-string: True
outpkg: mocks
filename: "{{.InterfaceName | camelcase | firstLower }}_mock.go"

packages:
  github.com/zilliztech/milvus-backup/core/client:
    interfaces:
      Grpc: