coverage:
  status:
    project:
      default:
        target: 90%
    patch:
      default:
        target: 90%

ignore:
  - "**/*.py"
  - "**/*.sh"
  - "**/*.pb.go"
  - "**/*_mock.go"
  - "**/*_string.go"
