// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package milvus

import (
	"context"
	"time"

	"github.com/milvus-io/milvus-proto/go-api/v3/commonpb"
	"github.com/milvus-io/milvus-proto/go-api/v3/milvuspb"
	"github.com/milvus-io/milvus-proto/go-api/v3/schemapb"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGrpc creates a new instance of MockGrpc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGrpc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGrpc {
	mock := &MockGrpc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGrpc is an autogenerated mock type for the Grpc type
type MockGrpc struct {
	mock.Mock
}

type MockGrpc_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGrpc) EXPECT() *MockGrpc_Expecter {
	return &MockGrpc_Expecter{mock: &_m.Mock}
}

// AddField provides a mock function for the type MockGrpc
func (_mock *MockGrpc) AddField(ctx context.Context, db string, collName string, field *schemapb.FieldSchema) error {
	ret := _mock.Called(ctx, db, collName, field)

	if len(ret) == 0 {
		panic("no return value specified for AddField")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *schemapb.FieldSchema) error); ok {
		r0 = returnFunc(ctx, db, collName, field)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGrpc_AddField_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddField'
type MockGrpc_AddField_Call struct {
	*mock.Call
}

// AddField is a helper method to define mock.On call
//   - ctx context.Context
//   - db string
//   - collName string
//   - field *schemapb.FieldSchema
func (_e *MockGrpc_Expecter) AddField(ctx any, db any, collName any, field any) *MockGrpc_AddField_Call {
	return &MockGrpc_AddField_Call{Call: _e.mock.On("AddField", ctx, db, collName, field)}
}

func (_c *MockGrpc_AddField_Call) Run(run func(ctx context.Context, db string, collName string, field *schemapb.FieldSchema)) *MockGrpc_AddField_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *schemapb.FieldSchema
		if args[3] != nil {
			arg3 = args[3].(*schemapb.FieldSchema)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockGrpc_AddField_Call) Return(err error) *MockGrpc_AddField_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGrpc_AddField_Call) RunAndReturn(run func(ctx context.Context, db string, collName string, field *schemapb.FieldSchema) error) *MockGrpc_AddField_Call {
	_c.Call.Return(run)
	return _c
}

// AlterCollection provides a mock function for the type MockGrpc
func (_mock *MockGrpc) AlterCollection(ctx context.Context, db string, collName string, properties []*commonpb.KeyValuePair) error {
	ret := _mock.Called(ctx, db, collName, properties)

	if len(ret) == 0 {
		panic("no return value specified for AlterCollection")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []*commonpb.KeyValuePair) error); ok {
		r0 = returnFunc(ctx, db, collName, properties)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGrpc_AlterCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AlterCollection'
type MockGrpc_AlterCollection_Call struct {
	*mock.Call
}

// AlterCollection is a helper method to define mock.On call
//   - ctx context.Context
//   - db string
//   - collName string
//   - properties []*commonpb.KeyValuePair
func (_e *MockGrpc_Expecter) AlterCollection(ctx any, db any, collName any, properties any) *MockGrpc_AlterCollection_Call {
	return &MockGrpc_AlterCollection_Call{Call: _e.mock.On("AlterCollection", ctx, db, collName, properties)}
}

func (_c *MockGrpc_AlterCollection_Call) Run(run func(ctx context.Context, db string, collName string, properties []*commonpb.KeyValuePair)) *MockGrpc_AlterCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []*commonpb.KeyValuePair
		if args[3] != nil {
			arg3 = args[3].([]*commonpb.KeyValuePair)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockGrpc_AlterCollection_Call) Return(err error) *MockGrpc_AlterCollection_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGrpc_AlterCollection_Call) RunAndReturn(run func(ctx context.Context, db string, collName string, properties []*commonpb.KeyValuePair) error) *MockGrpc_AlterCollection_Call {
	_c.Call.Return(run)
	return _c
}

// BackupRBAC provides a mock function for the type MockGrpc
func (_mock *MockGrpc) BackupRBAC(ctx context.Context) (*milvuspb.BackupRBACMetaResponse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BackupRBAC")
	}

	var r0 *milvuspb.BackupRBACMetaResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*milvuspb.BackupRBACMetaResponse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *milvuspb.BackupRBACMetaResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*milvuspb.BackupRBACMetaResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGrpc_BackupRBAC_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BackupRBAC'
type MockGrpc_BackupRBAC_Call struct {
	*mock.Call
}

// BackupRBAC is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGrpc_Expecter) BackupRBAC(ctx any) *MockGrpc_BackupRBAC_Call {
	return &MockGrpc_BackupRBAC_Call{Call: _e.mock.On("BackupRBAC", ctx)}
}

func (_c *MockGrpc_BackupRBAC_Call) Run(run func(ctx context.Context)) *MockGrpc_BackupRBAC_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGrpc_BackupRBAC_Call) Return(backupRBACMetaResponse *milvuspb.BackupRBACMetaResponse, err error) *MockGrpc_BackupRBAC_Call {
	_c.Call.Return(backupRBACMetaResponse, err)
	return _c
}

func (_c *MockGrpc_BackupRBAC_Call) RunAndReturn(run func(ctx context.Context) (*milvuspb.BackupRBACMetaResponse, error)) *MockGrpc_BackupRBAC_Call {
	_c.Call.Return(run)
	return _c
}

// BulkInsert provides a mock function for the type MockGrpc
func (_mock *MockGrpc) BulkInsert(ctx context.Context, input GrpcBulkInsertInput) (int64, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for BulkInsert")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, GrpcBulkInsertInput) (int64, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, GrpcBulkInsertInput) int64); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, GrpcBulkInsertInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGrpc_BulkInsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkInsert'
type MockGrpc_BulkInsert_Call struct {
	*mock.Call
}

// BulkInsert is a helper method to define mock.On call
//   - ctx context.Context
//   - input GrpcBulkInsertInput
func (_e *MockGrpc_Expecter) BulkInsert(ctx any, input any) *MockGrpc_BulkInsert_Call {
	return &MockGrpc_BulkInsert_Call{Call: _e.mock.On("BulkInsert", ctx, input)}
}

func (_c *MockGrpc_BulkInsert_Call) Run(run func(ctx context.Context, input GrpcBulkInsertInput)) *MockGrpc_BulkInsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 GrpcBulkInsertInput
		if args[1] != nil {
			arg1 = args[1].(GrpcBulkInsertInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGrpc_BulkInsert_Call) Return(n int64, err error) *MockGrpc_BulkInsert_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockGrpc_BulkInsert_Call) RunAndReturn(run func(ctx context.Context, input GrpcBulkInsertInput) (int64, error)) *MockGrpc_BulkInsert_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockGrpc
func (_mock *MockGrpc) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGrpc_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockGrpc_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockGrpc_Expecter) Close() *MockGrpc_Close_Call {
	return &MockGrpc_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockGrpc_Close_Call) Run(run func()) *MockGrpc_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGrpc_Close_Call) Return(err error) *MockGrpc_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGrpc_Close_Call) RunAndReturn(run func() error) *MockGrpc_Close_Call {
	_c.Call.Return(run)
	return _c
}

// CreateCollection provides a mock function for the type MockGrpc
func (_mock *MockGrpc) CreateCollection(ctx context.Context, input CreateCollectionInput) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateCollection")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateCollectionInput) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGrpc_CreateCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCollection'
type MockGrpc_CreateCollection_Call struct {
	*mock.Call
}

// CreateCollection is a helper method to define mock.On call
//   - ctx context.Context
//   - input CreateCollectionInput
func (_e *MockGrpc_Expecter) CreateCollection(ctx any, input any) *MockGrpc_CreateCollection_Call {
	return &MockGrpc_CreateCollection_Call{Call: _e.mock.On("CreateCollection", ctx, input)}
}

func (_c *MockGrpc_CreateCollection_Call) Run(run func(ctx context.Context, input CreateCollectionInput)) *MockGrpc_CreateCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 CreateCollectionInput
		if args[1] != nil {
			arg1 = args[1].(CreateCollectionInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGrpc_CreateCollection_Call) Return(err error) *MockGrpc_CreateCollection_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGrpc_CreateCollection_Call) RunAndReturn(run func(ctx context.Context, input CreateCollectionInput) error) *MockGrpc_CreateCollection_Call {
	_c.Call.Return(run)
	return _c
}

// CreateDatabase provides a mock function for the type MockGrpc
func (_mock *MockGrpc) CreateDatabase(ctx context.Context, dbName string) error {
	ret := _mock.Called(ctx, dbName)

	if len(ret) == 0 {
		panic("no return value specified for CreateDatabase")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, dbName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGrpc_CreateDatabase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDatabase'
type MockGrpc_CreateDatabase_Call struct {
	*mock.Call
}

// CreateDatabase is a helper method to define mock.On call
//   - ctx context.Context
//   - dbName string
func (_e *MockGrpc_Expecter) CreateDatabase(ctx any, dbName any) *MockGrpc_CreateDatabase_Call {
	return &MockGrpc_CreateDatabase_Call{Call: _e.mock.On("CreateDatabase", ctx, dbName)}
}

func (_c *MockGrpc_CreateDatabase_Call) Run(run func(ctx context.Context, dbName string)) *MockGrpc_CreateDatabase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGrpc_CreateDatabase_Call) Return(err error) *MockGrpc_CreateDatabase_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGrpc_CreateDatabase_Call) RunAndReturn(run func(ctx context.Context, dbName string) error) *MockGrpc_CreateDatabase_Call {
	_c.Call.Return(run)
	return _c
}

// CreateIndex provides a mock function for the type MockGrpc
func (_mock *MockGrpc) CreateIndex(ctx context.Context, input CreateIndexInput) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateIndex")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateIndexInput) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGrpc_CreateIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateIndex'
type MockGrpc_CreateIndex_Call struct {
	*mock.Call
}

// CreateIndex is a helper method to define mock.On call
//   - ctx context.Context
//   - input CreateIndexInput
func (_e *MockGrpc_Expecter) CreateIndex(ctx any, input any) *MockGrpc_CreateIndex_Call {
	return &MockGrpc_CreateIndex_Call{Call: _e.mock.On("CreateIndex", ctx, input)}
}

func (_c *MockGrpc_CreateIndex_Call) Run(run func(ctx context.Context, input CreateIndexInput)) *MockGrpc_CreateIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 CreateIndexInput
		if args[1] != nil {
			arg1 = args[1].(CreateIndexInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGrpc_CreateIndex_Call) Return(err error) *MockGrpc_CreateIndex_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGrpc_CreateIndex_Call) RunAndReturn(run func(ctx context.Context, input CreateIndexInput) error) *MockGrpc_CreateIndex_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePartition provides a mock function for the type MockGrpc
func (_mock *MockGrpc) CreatePartition(ctx context.Context, db string, collName string, partitionName string) error {
	ret := _mock.Called(ctx, db, collName, partitionName)

	if len(ret) == 0 {
		panic("no return value specified for CreatePartition")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, db, collName, partitionName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGrpc_CreatePartition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePartition'
type MockGrpc_CreatePartition_Call struct {
	*mock.Call
}

// CreatePartition is a helper method to define mock.On call
//   - ctx context.Context
//   - db string
//   - collName string
//   - partitionName string
func (_e *MockGrpc_Expecter) CreatePartition(ctx any, db any, collName any, partitionName any) *MockGrpc_CreatePartition_Call {
	return &MockGrpc_CreatePartition_Call{Call: _e.mock.On("CreatePartition", ctx, db, collName, partitionName)}
}

func (_c *MockGrpc_CreatePartition_Call) Run(run func(ctx context.Context, db string, collName string, partitionName string)) *MockGrpc_CreatePartition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockGrpc_CreatePartition_Call) Return(err error) *MockGrpc_CreatePartition_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGrpc_CreatePartition_Call) RunAndReturn(run func(ctx context.Context, db string, collName string, partitionName string) error) *MockGrpc_CreatePartition_Call {
	_c.Call.Return(run)
	return _c
}

// CreateReplicateStream provides a mock function for the type MockGrpc
func (_mock *MockGrpc) CreateReplicateStream(ctx context.Context, sourceClusterID string) (milvuspb.MilvusService_CreateReplicateStreamClient, error) {
	ret := _mock.Called(ctx, sourceClusterID)

	if len(ret) == 0 {
		panic("no return value specified for CreateReplicateStream")
	}

	var r0 milvuspb.MilvusService_CreateReplicateStreamClient
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (milvuspb.MilvusService_CreateReplicateStreamClient, error)); ok {
		return returnFunc(ctx, sourceClusterID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) milvuspb.MilvusService_CreateReplicateStreamClient); ok {
		r0 = returnFunc(ctx, sourceClusterID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(milvuspb.MilvusService_CreateReplicateStreamClient)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, sourceClusterID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGrpc_CreateReplicateStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateReplicateStream'
type MockGrpc_CreateReplicateStream_Call struct {
	*mock.Call
}

// CreateReplicateStream is a helper method to define mock.On call
//   - ctx context.Context
//   - sourceClusterID string
func (_e *MockGrpc_Expecter) CreateReplicateStream(ctx any, sourceClusterID any) *MockGrpc_CreateReplicateStream_Call {
	return &MockGrpc_CreateReplicateStream_Call{Call: _e.mock.On("CreateReplicateStream", ctx, sourceClusterID)}
}

func (_c *MockGrpc_CreateReplicateStream_Call) Run(run func(ctx context.Context, sourceClusterID string)) *MockGrpc_CreateReplicateStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGrpc_CreateReplicateStream_Call) Return(milvusService_CreateReplicateStreamClient milvuspb.MilvusService_CreateReplicateStreamClient, err error) *MockGrpc_CreateReplicateStream_Call {
	_c.Call.Return(milvusService_CreateReplicateStreamClient, err)
	return _c
}

func (_c *MockGrpc_CreateReplicateStream_Call) RunAndReturn(run func(ctx context.Context, sourceClusterID string) (milvuspb.MilvusService_CreateReplicateStreamClient, error)) *MockGrpc_CreateReplicateStream_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSnapshot provides a mock function for the type MockGrpc
func (_mock *MockGrpc) CreateSnapshot(ctx context.Context, db string, collName string, snapshotName string, compactionProtection time.Duration) error {
	ret := _mock.Called(ctx, db, collName, snapshotName, compactionProtection)

	if len(ret) == 0 {
		panic("no return value specified for CreateSnapshot")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, time.Duration) error); ok {
		r0 = returnFunc(ctx, db, collName, snapshotName, compactionProtection)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGrpc_CreateSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSnapshot'
type MockGrpc_CreateSnapshot_Call struct {
	*mock.Call
}

// CreateSnapshot is a helper method to define mock.On call
//   - ctx context.Context
//   - db string
//   - collName string
//   - snapshotName string
//   - compactionProtection time.Duration
func (_e *MockGrpc_Expecter) CreateSnapshot(ctx any, db any, collName any, snapshotName any, compactionProtection any) *MockGrpc_CreateSnapshot_Call {
	return &MockGrpc_CreateSnapshot_Call{Call: _e.mock.On("CreateSnapshot", ctx, db, collName, snapshotName, compactionProtection)}
}

func (_c *MockGrpc_CreateSnapshot_Call) Run(run func(ctx context.Context, db string, collName string, snapshotName string, compactionProtection time.Duration)) *MockGrpc_CreateSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 time.Duration
		if args[4] != nil {
			arg4 = args[4].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockGrpc_CreateSnapshot_Call) Return(err error) *MockGrpc_CreateSnapshot_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGrpc_CreateSnapshot_Call) RunAndReturn(run func(ctx context.Context, db string, collName string, snapshotName string, compactionProtection time.Duration) error) *MockGrpc_CreateSnapshot_Call {
	_c.Call.Return(run)
	return _c
}

// DescribeCollection provides a mock function for the type MockGrpc
func (_mock *MockGrpc) DescribeCollection(ctx context.Context, db string, collName string) (*milvuspb.DescribeCollectionResponse, error) {
	ret := _mock.Called(ctx, db, collName)

	if len(ret) == 0 {
		panic("no return value specified for DescribeCollection")
	}

	var r0 *milvuspb.DescribeCollectionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*milvuspb.DescribeCollectionResponse, error)); ok {
		return returnFunc(ctx, db, collName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *milvuspb.DescribeCollectionResponse); ok {
		r0 = returnFunc(ctx, db, collName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*milvuspb.DescribeCollectionResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, db, collName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGrpc_DescribeCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribeCollection'
type MockGrpc_DescribeCollection_Call struct {
	*mock.Call
}

// DescribeCollection is a helper method to define mock.On call
//   - ctx context.Context
//   - db string
//   - collName string
func (_e *MockGrpc_Expecter) DescribeCollection(ctx any, db any, collName any) *MockGrpc_DescribeCollection_Call {
	return &MockGrpc_DescribeCollection_Call{Call: _e.mock.On("DescribeCollection", ctx, db, collName)}
}

func (_c *MockGrpc_DescribeCollection_Call) Run(run func(ctx context.Context, db string, collName string)) *MockGrpc_DescribeCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGrpc_DescribeCollection_Call) Return(describeCollectionResponse *milvuspb.DescribeCollectionResponse, err error) *MockGrpc_DescribeCollection_Call {
	_c.Call.Return(describeCollectionResponse, err)
	return _c
}

func (_c *MockGrpc_DescribeCollection_Call) RunAndReturn(run func(ctx context.Context, db string, collName string) (*milvuspb.DescribeCollectionResponse, error)) *MockGrpc_DescribeCollection_Call {
	_c.Call.Return(run)
	return _c
}

// DescribeDatabase provides a mock function for the type MockGrpc
func (_mock *MockGrpc) DescribeDatabase(ctx context.Context, dbName string) (*milvuspb.DescribeDatabaseResponse, error) {
	ret := _mock.Called(ctx, dbName)

	if len(ret) == 0 {
		panic("no return value specified for DescribeDatabase")
	}

	var r0 *milvuspb.DescribeDatabaseResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*milvuspb.DescribeDatabaseResponse, error)); ok {
		return returnFunc(ctx, dbName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *milvuspb.DescribeDatabaseResponse); ok {
		r0 = returnFunc(ctx, dbName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*milvuspb.DescribeDatabaseResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, dbName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGrpc_DescribeDatabase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribeDatabase'
type MockGrpc_DescribeDatabase_Call struct {
	*mock.Call
}

// DescribeDatabase is a helper method to define mock.On call
//   - ctx context.Context
//   - dbName string
func (_e *MockGrpc_Expecter) DescribeDatabase(ctx any, dbName any) *MockGrpc_DescribeDatabase_Call {
	return &MockGrpc_DescribeDatabase_Call{Call: _e.mock.On("DescribeDatabase", ctx, dbName)}
}

func (_c *MockGrpc_DescribeDatabase_Call) Run(run func(ctx context.Context, dbName string)) *MockGrpc_DescribeDatabase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGrpc_DescribeDatabase_Call) Return(describeDatabaseResponse *milvuspb.DescribeDatabaseResponse, err error) *MockGrpc_DescribeDatabase_Call {
	_c.Call.Return(describeDatabaseResponse, err)
	return _c
}

func (_c *MockGrpc_DescribeDatabase_Call) RunAndReturn(run func(ctx context.Context, dbName string) (*milvuspb.DescribeDatabaseResponse, error)) *MockGrpc_DescribeDatabase_Call {
	_c.Call.Return(run)
	return _c
}

// DescribeSnapshot provides a mock function for the type MockGrpc
func (_mock *MockGrpc) DescribeSnapshot(ctx context.Context, db string, collName string, snapshotName string) (*milvuspb.DescribeSnapshotResponse, error) {
	ret := _mock.Called(ctx, db, collName, snapshotName)

	if len(ret) == 0 {
		panic("no return value specified for DescribeSnapshot")
	}

	var r0 *milvuspb.DescribeSnapshotResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*milvuspb.DescribeSnapshotResponse, error)); ok {
		return returnFunc(ctx, db, collName, snapshotName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *milvuspb.DescribeSnapshotResponse); ok {
		r0 = returnFunc(ctx, db, collName, snapshotName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*milvuspb.DescribeSnapshotResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, db, collName, snapshotName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGrpc_DescribeSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribeSnapshot'
type MockGrpc_DescribeSnapshot_Call struct {
	*mock.Call
}

// DescribeSnapshot is a helper method to define mock.On call
//   - ctx context.Context
//   - db string
//   - collName string
//   - snapshotName string
func (_e *MockGrpc_Expecter) DescribeSnapshot(ctx any, db any, collName any, snapshotName any) *MockGrpc_DescribeSnapshot_Call {
	return &MockGrpc_DescribeSnapshot_Call{Call: _e.mock.On("DescribeSnapshot", ctx, db, collName, snapshotName)}
}

func (_c *MockGrpc_DescribeSnapshot_Call) Run(run func(ctx context.Context, db string, collName string, snapshotName string)) *MockGrpc_DescribeSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockGrpc_DescribeSnapshot_Call) Return(describeSnapshotResponse *milvuspb.DescribeSnapshotResponse, err error) *MockGrpc_DescribeSnapshot_Call {
	_c.Call.Return(describeSnapshotResponse, err)
	return _c
}

func (_c *MockGrpc_DescribeSnapshot_Call) RunAndReturn(run func(ctx context.Context, db string, collName string, snapshotName string) (*milvuspb.DescribeSnapshotResponse, error)) *MockGrpc_DescribeSnapshot_Call {
	_c.Call.Return(run)
	return _c
}

// DropCollection provides a mock function for the type MockGrpc
func (_mock *MockGrpc) DropCollection(ctx context.Context, db string, collectionName string) error {
	ret := _mock.Called(ctx, db, collectionName)

	if len(ret) == 0 {
		panic("no return value specified for DropCollection")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, db, collectionName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGrpc_DropCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DropCollection'
type MockGrpc_DropCollection_Call struct {
	*mock.Call
}

// DropCollection is a helper method to define mock.On call
//   - ctx context.Context
//   - db string
//   - collectionName string
func (_e *MockGrpc_Expecter) DropCollection(ctx any, db any, collectionName any) *MockGrpc_DropCollection_Call {
	return &MockGrpc_DropCollection_Call{Call: _e.mock.On("DropCollection", ctx, db, collectionName)}
}

func (_c *MockGrpc_DropCollection_Call) Run(run func(ctx context.Context, db string, collectionName string)) *MockGrpc_DropCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGrpc_DropCollection_Call) Return(err error) *MockGrpc_DropCollection_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGrpc_DropCollection_Call) RunAndReturn(run func(ctx context.Context, db string, collectionName string) error) *MockGrpc_DropCollection_Call {
	_c.Call.Return(run)
	return _c
}

// DropCollectionFieldProperties provides a mock function for the type MockGrpc
func (_mock *MockGrpc) DropCollectionFieldProperties(ctx context.Context, db string, collName string, fieldName string, keys []string) error {
	ret := _mock.Called(ctx, db, collName, fieldName, keys)

	if len(ret) == 0 {
		panic("no return value specified for DropCollectionFieldProperties")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, []string) error); ok {
		r0 = returnFunc(ctx, db, collName, fieldName, keys)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGrpc_DropCollectionFieldProperties_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DropCollectionFieldProperties'
type MockGrpc_DropCollectionFieldProperties_Call struct {
	*mock.Call
}

// DropCollectionFieldProperties is a helper method to define mock.On call
//   - ctx context.Context
//   - db string
//   - collName string
//   - fieldName string
//   - keys []string
func (_e *MockGrpc_Expecter) DropCollectionFieldProperties(ctx any, db any, collName any, fieldName any, keys any) *MockGrpc_DropCollectionFieldProperties_Call {
	return &MockGrpc_DropCollectionFieldProperties_Call{Call: _e.mock.On("DropCollectionFieldProperties", ctx, db, collName, fieldName, keys)}
}

func (_c *MockGrpc_DropCollectionFieldProperties_Call) Run(run func(ctx context.Context, db string, collName string, fieldName string, keys []string)) *MockGrpc_DropCollectionFieldProperties_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []string
		if args[4] != nil {
			arg4 = args[4].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockGrpc_DropCollectionFieldProperties_Call) Return(err error) *MockGrpc_DropCollectionFieldProperties_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGrpc_DropCollectionFieldProperties_Call) RunAndReturn(run func(ctx context.Context, db string, collName string, fieldName string, keys []string) error) *MockGrpc_DropCollectionFieldProperties_Call {
	_c.Call.Return(run)
	return _c
}

// DropCollectionProperties provides a mock function for the type MockGrpc
func (_mock *MockGrpc) DropCollectionProperties(ctx context.Context, db string, collName string, keys []string) error {
	ret := _mock.Called(ctx, db, collName, keys)

	if len(ret) == 0 {
		panic("no return value specified for DropCollectionProperties")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []string) error); ok {
		r0 = returnFunc(ctx, db, collName, keys)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGrpc_DropCollectionProperties_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DropCollectionProperties'
type MockGrpc_DropCollectionProperties_Call struct {
	*mock.Call
}

// DropCollectionProperties is a helper method to define mock.On call
//   - ctx context.Context
//   - db string
//   - collName string
//   - keys []string
func (_e *MockGrpc_Expecter) DropCollectionProperties(ctx any, db any, collName any, keys any) *MockGrpc_DropCollectionProperties_Call {
	return &MockGrpc_DropCollectionProperties_Call{Call: _e.mock.On("DropCollectionProperties", ctx, db, collName, keys)}
}

func (_c *MockGrpc_DropCollectionProperties_Call) Run(run func(ctx context.Context, db string, collName string, keys []string)) *MockGrpc_DropCollectionProperties_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []string
		if args[3] != nil {
			arg3 = args[3].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockGrpc_DropCollectionProperties_Call) Return(err error) *MockGrpc_DropCollectionProperties_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGrpc_DropCollectionProperties_Call) RunAndReturn(run func(ctx context.Context, db string, collName string, keys []string) error) *MockGrpc_DropCollectionProperties_Call {
	_c.Call.Return(run)
	return _c
}

// DropIndex provides a mock function for the type MockGrpc
func (_mock *MockGrpc) DropIndex(ctx context.Context, db string, collName string, indexName string) error {
	ret := _mock.Called(ctx, db, collName, indexName)

	if len(ret) == 0 {
		panic("no return value specified for DropIndex")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, db, collName, indexName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGrpc_DropIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DropIndex'
type MockGrpc_DropIndex_Call struct {
	*mock.Call
}

// DropIndex is a helper method to define mock.On call
//   - ctx context.Context
//   - db string
//   - collName string
//   - indexName string
func (_e *MockGrpc_Expecter) DropIndex(ctx any, db any, collName any, indexName any) *MockGrpc_DropIndex_Call {
	return &MockGrpc_DropIndex_Call{Call: _e.mock.On("DropIndex", ctx, db, collName, indexName)}
}

func (_c *MockGrpc_DropIndex_Call) Run(run func(ctx context.Context, db string, collName string, indexName string)) *MockGrpc_DropIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockGrpc_DropIndex_Call) Return(err error) *MockGrpc_DropIndex_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGrpc_DropIndex_Call) RunAndReturn(run func(ctx context.Context, db string, collName string, indexName string) error) *MockGrpc_DropIndex_Call {
	_c.Call.Return(run)
	return _c
}

// DropIndexProperties provides a mock function for the type MockGrpc
func (_mock *MockGrpc) DropIndexProperties(ctx context.Context, db string, collName string, indexName string, keys []string) error {
	ret := _mock.Called(ctx, db, collName, indexName, keys)

	if len(ret) == 0 {
		panic("no return value specified for DropIndexProperties")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, []string) error); ok {
		r0 = returnFunc(ctx, db, collName, indexName, keys)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGrpc_DropIndexProperties_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DropIndexProperties'
type MockGrpc_DropIndexProperties_Call struct {
	*mock.Call
}

// DropIndexProperties is a helper method to define mock.On call
//   - ctx context.Context
//   - db string
//   - collName string
//   - indexName string
//   - keys []string
func (_e *MockGrpc_Expecter) DropIndexProperties(ctx any, db any, collName any, indexName any, keys any) *MockGrpc_DropIndexProperties_Call {
	return &MockGrpc_DropIndexProperties_Call{Call: _e.mock.On("DropIndexProperties", ctx, db, collName, indexName, keys)}
}

func (_c *MockGrpc_DropIndexProperties_Call) Run(run func(ctx context.Context, db string, collName string, indexName string, keys []string)) *MockGrpc_DropIndexProperties_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []string
		if args[4] != nil {
			arg4 = args[4].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockGrpc_DropIndexProperties_Call) Return(err error) *MockGrpc_DropIndexProperties_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGrpc_DropIndexProperties_Call) RunAndReturn(run func(ctx context.Context, db string, collName string, indexName string, keys []string) error) *MockGrpc_DropIndexProperties_Call {
	_c.Call.Return(run)
	return _c
}

// DropSnapshot provides a mock function for the type MockGrpc
func (_mock *MockGrpc) DropSnapshot(ctx context.Context, db string, collName string, snapshotName string) error {
	ret := _mock.Called(ctx, db, collName, snapshotName)

	if len(ret) == 0 {
		panic("no return value specified for DropSnapshot")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, db, collName, snapshotName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGrpc_DropSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DropSnapshot'
type MockGrpc_DropSnapshot_Call struct {
	*mock.Call
}

// DropSnapshot is a helper method to define mock.On call
//   - ctx context.Context
//   - db string
//   - collName string
//   - snapshotName string
func (_e *MockGrpc_Expecter) DropSnapshot(ctx any, db any, collName any, snapshotName any) *MockGrpc_DropSnapshot_Call {
	return &MockGrpc_DropSnapshot_Call{Call: _e.mock.On("DropSnapshot", ctx, db, collName, snapshotName)}
}

func (_c *MockGrpc_DropSnapshot_Call) Run(run func(ctx context.Context, db string, collName string, snapshotName string)) *MockGrpc_DropSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockGrpc_DropSnapshot_Call) Return(err error) *MockGrpc_DropSnapshot_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGrpc_DropSnapshot_Call) RunAndReturn(run func(ctx context.Context, db string, collName string, snapshotName string) error) *MockGrpc_DropSnapshot_Call {
	_c.Call.Return(run)
	return _c
}

// ExportSnapshot provides a mock function for the type MockGrpc
func (_mock *MockGrpc) ExportSnapshot(ctx context.Context, input ExportSnapshotInput) (int64, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ExportSnapshot")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ExportSnapshotInput) (int64, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ExportSnapshotInput) int64); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ExportSnapshotInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGrpc_ExportSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportSnapshot'
type MockGrpc_ExportSnapshot_Call struct {
	*mock.Call
}

// ExportSnapshot is a helper method to define mock.On call
//   - ctx context.Context
//   - input ExportSnapshotInput
func (_e *MockGrpc_Expecter) ExportSnapshot(ctx any, input any) *MockGrpc_ExportSnapshot_Call {
	return &MockGrpc_ExportSnapshot_Call{Call: _e.mock.On("ExportSnapshot", ctx, input)}
}

func (_c *MockGrpc_ExportSnapshot_Call) Run(run func(ctx context.Context, input ExportSnapshotInput)) *MockGrpc_ExportSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ExportSnapshotInput
		if args[1] != nil {
			arg1 = args[1].(ExportSnapshotInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGrpc_ExportSnapshot_Call) Return(n int64, err error) *MockGrpc_ExportSnapshot_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockGrpc_ExportSnapshot_Call) RunAndReturn(run func(ctx context.Context, input ExportSnapshotInput) (int64, error)) *MockGrpc_ExportSnapshot_Call {
	_c.Call.Return(run)
	return _c
}

// Flush provides a mock function for the type MockGrpc
func (_mock *MockGrpc) Flush(ctx context.Context, db string, collName string) (*milvuspb.FlushResponse, error) {
	ret := _mock.Called(ctx, db, collName)

	if len(ret) == 0 {
		panic("no return value specified for Flush")
	}

	var r0 *milvuspb.FlushResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*milvuspb.FlushResponse, error)); ok {
		return returnFunc(ctx, db, collName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *milvuspb.FlushResponse); ok {
		r0 = returnFunc(ctx, db, collName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*milvuspb.FlushResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, db, collName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGrpc_Flush_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Flush'
type MockGrpc_Flush_Call struct {
	*mock.Call
}

// Flush is a helper method to define mock.On call
//   - ctx context.Context
//   - db string
//   - collName string
func (_e *MockGrpc_Expecter) Flush(ctx any, db any, collName any) *MockGrpc_Flush_Call {
	return &MockGrpc_Flush_Call{Call: _e.mock.On("Flush", ctx, db, collName)}
}

func (_c *MockGrpc_Flush_Call) Run(run func(ctx context.Context, db string, collName string)) *MockGrpc_Flush_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGrpc_Flush_Call) Return(flushResponse *milvuspb.FlushResponse, err error) *MockGrpc_Flush_Call {
	_c.Call.Return(flushResponse, err)
	return _c
}

func (_c *MockGrpc_Flush_Call) RunAndReturn(run func(ctx context.Context, db string, collName string) (*milvuspb.FlushResponse, error)) *MockGrpc_Flush_Call {
	_c.Call.Return(run)
	return _c
}

// FlushAll provides a mock function for the type MockGrpc
func (_mock *MockGrpc) FlushAll(ctx context.Context) (*milvuspb.FlushAllResponse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FlushAll")
	}

	var r0 *milvuspb.FlushAllResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*milvuspb.FlushAllResponse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *milvuspb.FlushAllResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*milvuspb.FlushAllResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGrpc_FlushAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FlushAll'
type MockGrpc_FlushAll_Call struct {
	*mock.Call
}

// FlushAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGrpc_Expecter) FlushAll(ctx any) *MockGrpc_FlushAll_Call {
	return &MockGrpc_FlushAll_Call{Call: _e.mock.On("FlushAll", ctx)}
}

func (_c *MockGrpc_FlushAll_Call) Run(run func(ctx context.Context)) *MockGrpc_FlushAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGrpc_FlushAll_Call) Return(flushAllResponse *milvuspb.FlushAllResponse, err error) *MockGrpc_FlushAll_Call {
	_c.Call.Return(flushAllResponse, err)
	return _c
}

func (_c *MockGrpc_FlushAll_Call) RunAndReturn(run func(ctx context.Context) (*milvuspb.FlushAllResponse, error)) *MockGrpc_FlushAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetBulkInsertState provides a mock function for the type MockGrpc
func (_mock *MockGrpc) GetBulkInsertState(ctx context.Context, taskID int64) (*milvuspb.GetImportStateResponse, error) {
	ret := _mock.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for GetBulkInsertState")
	}

	var r0 *milvuspb.GetImportStateResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*milvuspb.GetImportStateResponse, error)); ok {
		return returnFunc(ctx, taskID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *milvuspb.GetImportStateResponse); ok {
		r0 = returnFunc(ctx, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*milvuspb.GetImportStateResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, taskID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGrpc_GetBulkInsertState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBulkInsertState'
type MockGrpc_GetBulkInsertState_Call struct {
	*mock.Call
}

// GetBulkInsertState is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID int64
func (_e *MockGrpc_Expecter) GetBulkInsertState(ctx any, taskID any) *MockGrpc_GetBulkInsertState_Call {
	return &MockGrpc_GetBulkInsertState_Call{Call: _e.mock.On("GetBulkInsertState", ctx, taskID)}
}

func (_c *MockGrpc_GetBulkInsertState_Call) Run(run func(ctx context.Context, taskID int64)) *MockGrpc_GetBulkInsertState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGrpc_GetBulkInsertState_Call) Return(getImportStateResponse *milvuspb.GetImportStateResponse, err error) *MockGrpc_GetBulkInsertState_Call {
	_c.Call.Return(getImportStateResponse, err)
	return _c
}

func (_c *MockGrpc_GetBulkInsertState_Call) RunAndReturn(run func(ctx context.Context, taskID int64) (*milvuspb.GetImportStateResponse, error)) *MockGrpc_GetBulkInsertState_Call {
	_c.Call.Return(run)
	return _c
}

// GetExportSnapshotState provides a mock function for the type MockGrpc
func (_mock *MockGrpc) GetExportSnapshotState(ctx context.Context, jobID int64) (*milvuspb.ExportSnapshotInfo, error) {
	ret := _mock.Called(ctx, jobID)

	if len(ret) == 0 {
		panic("no return value specified for GetExportSnapshotState")
	}

	var r0 *milvuspb.ExportSnapshotInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*milvuspb.ExportSnapshotInfo, error)); ok {
		return returnFunc(ctx, jobID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *milvuspb.ExportSnapshotInfo); ok {
		r0 = returnFunc(ctx, jobID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*milvuspb.ExportSnapshotInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, jobID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGrpc_GetExportSnapshotState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExportSnapshotState'
type MockGrpc_GetExportSnapshotState_Call struct {
	*mock.Call
}

// GetExportSnapshotState is a helper method to define mock.On call
//   - ctx context.Context
//   - jobID int64
func (_e *MockGrpc_Expecter) GetExportSnapshotState(ctx any, jobID any) *MockGrpc_GetExportSnapshotState_Call {
	return &MockGrpc_GetExportSnapshotState_Call{Call: _e.mock.On("GetExportSnapshotState", ctx, jobID)}
}

func (_c *MockGrpc_GetExportSnapshotState_Call) Run(run func(ctx context.Context, jobID int64)) *MockGrpc_GetExportSnapshotState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGrpc_GetExportSnapshotState_Call) Return(exportSnapshotInfo *milvuspb.ExportSnapshotInfo, err error) *MockGrpc_GetExportSnapshotState_Call {
	_c.Call.Return(exportSnapshotInfo, err)
	return _c
}

func (_c *MockGrpc_GetExportSnapshotState_Call) RunAndReturn(run func(ctx context.Context, jobID int64) (*milvuspb.ExportSnapshotInfo, error)) *MockGrpc_GetExportSnapshotState_Call {
	_c.Call.Return(run)
	return _c
}

// GetLoadingProgress provides a mock function for the type MockGrpc
func (_mock *MockGrpc) GetLoadingProgress(ctx context.Context, db string, collName string, partitionNames ...string) (int64, error) {
	var tmpRet mock.Arguments
	if len(partitionNames) > 0 {
		tmpRet = _mock.Called(ctx, db, collName, partitionNames)
	} else {
		tmpRet = _mock.Called(ctx, db, collName)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetLoadingProgress")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, ...string) (int64, error)); ok {
		return returnFunc(ctx, db, collName, partitionNames...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, ...string) int64); ok {
		r0 = returnFunc(ctx, db, collName, partitionNames...)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, ...string) error); ok {
		r1 = returnFunc(ctx, db, collName, partitionNames...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGrpc_GetLoadingProgress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLoadingProgress'
type MockGrpc_GetLoadingProgress_Call struct {
	*mock.Call
}

// GetLoadingProgress is a helper method to define mock.On call
//   - ctx context.Context
//   - db string
//   - collName string
//   - partitionNames ...string
func (_e *MockGrpc_Expecter) GetLoadingProgress(ctx any, db any, collName any, partitionNames ...any) *MockGrpc_GetLoadingProgress_Call {
	return &MockGrpc_GetLoadingProgress_Call{Call: _e.mock.On("GetLoadingProgress",
		append([]any{ctx, db, collName}, partitionNames...)...)}
}

func (_c *MockGrpc_GetLoadingProgress_Call) Run(run func(ctx context.Context, db string, collName string, partitionNames ...string)) *MockGrpc_GetLoadingProgress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []string
		var variadicArgs []string
		if len(args) > 3 {
			variadicArgs = args[3].([]string)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockGrpc_GetLoadingProgress_Call) Return(n int64, err error) *MockGrpc_GetLoadingProgress_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockGrpc_GetLoadingProgress_Call) RunAndReturn(run func(ctx context.Context, db string, collName string, partitionNames ...string) (int64, error)) *MockGrpc_GetLoadingProgress_Call {
	_c.Call.Return(run)
	return _c
}

// GetPersistentSegmentInfo provides a mock function for the type MockGrpc
func (_mock *MockGrpc) GetPersistentSegmentInfo(ctx context.Context, db string, collName string) ([]*milvuspb.PersistentSegmentInfo, error) {
	ret := _mock.Called(ctx, db, collName)

	if len(ret) == 0 {
		panic("no return value specified for GetPersistentSegmentInfo")
	}

	var r0 []*milvuspb.PersistentSegmentInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]*milvuspb.PersistentSegmentInfo, error)); ok {
		return returnFunc(ctx, db, collName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []*milvuspb.PersistentSegmentInfo); ok {
		r0 = returnFunc(ctx, db, collName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*milvuspb.PersistentSegmentInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, db, collName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGrpc_GetPersistentSegmentInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPersistentSegmentInfo'
type MockGrpc_GetPersistentSegmentInfo_Call struct {
	*mock.Call
}

// GetPersistentSegmentInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - db string
//   - collName string
func (_e *MockGrpc_Expecter) GetPersistentSegmentInfo(ctx any, db any, collName any) *MockGrpc_GetPersistentSegmentInfo_Call {
	return &MockGrpc_GetPersistentSegmentInfo_Call{Call: _e.mock.On("GetPersistentSegmentInfo", ctx, db, collName)}
}

func (_c *MockGrpc_GetPersistentSegmentInfo_Call) Run(run func(ctx context.Context, db string, collName string)) *MockGrpc_GetPersistentSegmentInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGrpc_GetPersistentSegmentInfo_Call) Return(persistentSegmentInfos []*milvuspb.PersistentSegmentInfo, err error) *MockGrpc_GetPersistentSegmentInfo_Call {
	_c.Call.Return(persistentSegmentInfos, err)
	return _c
}

func (_c *MockGrpc_GetPersistentSegmentInfo_Call) RunAndReturn(run func(ctx context.Context, db string, collName string) ([]*milvuspb.PersistentSegmentInfo, error)) *MockGrpc_GetPersistentSegmentInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetReplicateConfiguration provides a mock function for the type MockGrpc
func (_mock *MockGrpc) GetReplicateConfiguration(ctx context.Context) (*commonpb.ReplicateConfiguration, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetReplicateConfiguration")
	}

	var r0 *commonpb.ReplicateConfiguration
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*commonpb.ReplicateConfiguration, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *commonpb.ReplicateConfiguration); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*commonpb.ReplicateConfiguration)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGrpc_GetReplicateConfiguration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReplicateConfiguration'
type MockGrpc_GetReplicateConfiguration_Call struct {
	*mock.Call
}

// GetReplicateConfiguration is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGrpc_Expecter) GetReplicateConfiguration(ctx any) *MockGrpc_GetReplicateConfiguration_Call {
	return &MockGrpc_GetReplicateConfiguration_Call{Call: _e.mock.On("GetReplicateConfiguration", ctx)}
}

func (_c *MockGrpc_GetReplicateConfiguration_Call) Run(run func(ctx context.Context)) *MockGrpc_GetReplicateConfiguration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGrpc_GetReplicateConfiguration_Call) Return(replicateConfiguration *commonpb.ReplicateConfiguration, err error) *MockGrpc_GetReplicateConfiguration_Call {
	_c.Call.Return(replicateConfiguration, err)
	return _c
}

func (_c *MockGrpc_GetReplicateConfiguration_Call) RunAndReturn(run func(ctx context.Context) (*commonpb.ReplicateConfiguration, error)) *MockGrpc_GetReplicateConfiguration_Call {
	_c.Call.Return(run)
	return _c
}

// GetReplicateInfo provides a mock function for the type MockGrpc
func (_mock *MockGrpc) GetReplicateInfo(ctx context.Context, sourceClusterID string, targetPchannel string) (*milvuspb.GetReplicateInfoResponse, error) {
	ret := _mock.Called(ctx, sourceClusterID, targetPchannel)

	if len(ret) == 0 {
		panic("no return value specified for GetReplicateInfo")
	}

	var r0 *milvuspb.GetReplicateInfoResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*milvuspb.GetReplicateInfoResponse, error)); ok {
		return returnFunc(ctx, sourceClusterID, targetPchannel)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *milvuspb.GetReplicateInfoResponse); ok {
		r0 = returnFunc(ctx, sourceClusterID, targetPchannel)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*milvuspb.GetReplicateInfoResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, sourceClusterID, targetPchannel)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGrpc_GetReplicateInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReplicateInfo'
type MockGrpc_GetReplicateInfo_Call struct {
	*mock.Call
}

// GetReplicateInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - sourceClusterID string
//   - targetPchannel string
func (_e *MockGrpc_Expecter) GetReplicateInfo(ctx any, sourceClusterID any, targetPchannel any) *MockGrpc_GetReplicateInfo_Call {
	return &MockGrpc_GetReplicateInfo_Call{Call: _e.mock.On("GetReplicateInfo", ctx, sourceClusterID, targetPchannel)}
}

func (_c *MockGrpc_GetReplicateInfo_Call) Run(run func(ctx context.Context, sourceClusterID string, targetPchannel string)) *MockGrpc_GetReplicateInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGrpc_GetReplicateInfo_Call) Return(getReplicateInfoResponse *milvuspb.GetReplicateInfoResponse, err error) *MockGrpc_GetReplicateInfo_Call {
	_c.Call.Return(getReplicateInfoResponse, err)
	return _c
}

func (_c *MockGrpc_GetReplicateInfo_Call) RunAndReturn(run func(ctx context.Context, sourceClusterID string, targetPchannel string) (*milvuspb.GetReplicateInfoResponse, error)) *MockGrpc_GetReplicateInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetRestoreSnapshotState provides a mock function for the type MockGrpc
func (_mock *MockGrpc) GetRestoreSnapshotState(ctx context.Context, jobID int64) (*milvuspb.RestoreSnapshotInfo, error) {
	ret := _mock.Called(ctx, jobID)

	if len(ret) == 0 {
		panic("no return value specified for GetRestoreSnapshotState")
	}

	var r0 *milvuspb.RestoreSnapshotInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*milvuspb.RestoreSnapshotInfo, error)); ok {
		return returnFunc(ctx, jobID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *milvuspb.RestoreSnapshotInfo); ok {
		r0 = returnFunc(ctx, jobID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*milvuspb.RestoreSnapshotInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, jobID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGrpc_GetRestoreSnapshotState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRestoreSnapshotState'
type MockGrpc_GetRestoreSnapshotState_Call struct {
	*mock.Call
}

// GetRestoreSnapshotState is a helper method to define mock.On call
//   - ctx context.Context
//   - jobID int64
func (_e *MockGrpc_Expecter) GetRestoreSnapshotState(ctx any, jobID any) *MockGrpc_GetRestoreSnapshotState_Call {
	return &MockGrpc_GetRestoreSnapshotState_Call{Call: _e.mock.On("GetRestoreSnapshotState", ctx, jobID)}
}

func (_c *MockGrpc_GetRestoreSnapshotState_Call) Run(run func(ctx context.Context, jobID int64)) *MockGrpc_GetRestoreSnapshotState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGrpc_GetRestoreSnapshotState_Call) Return(restoreSnapshotInfo *milvuspb.RestoreSnapshotInfo, err error) *MockGrpc_GetRestoreSnapshotState_Call {
	_c.Call.Return(restoreSnapshotInfo, err)
	return _c
}

func (_c *MockGrpc_GetRestoreSnapshotState_Call) RunAndReturn(run func(ctx context.Context, jobID int64) (*milvuspb.RestoreSnapshotInfo, error)) *MockGrpc_GetRestoreSnapshotState_Call {
	_c.Call.Return(run)
	return _c
}

// GetVersion provides a mock function for the type MockGrpc
func (_mock *MockGrpc) GetVersion(ctx context.Context) (string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetVersion")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGrpc_GetVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVersion'
type MockGrpc_GetVersion_Call struct {
	*mock.Call
}

// GetVersion is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGrpc_Expecter) GetVersion(ctx any) *MockGrpc_GetVersion_Call {
	return &MockGrpc_GetVersion_Call{Call: _e.mock.On("GetVersion", ctx)}
}

func (_c *MockGrpc_GetVersion_Call) Run(run func(ctx context.Context)) *MockGrpc_GetVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGrpc_GetVersion_Call) Return(s string, err error) *MockGrpc_GetVersion_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockGrpc_GetVersion_Call) RunAndReturn(run func(ctx context.Context) (string, error)) *MockGrpc_GetVersion_Call {
	_c.Call.Return(run)
	return _c
}

// HasCollection provides a mock function for the type MockGrpc
func (_mock *MockGrpc) HasCollection(ctx context.Context, db string, collName string) (bool, error) {
	ret := _mock.Called(ctx, db, collName)

	if len(ret) == 0 {
		panic("no return value specified for HasCollection")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, db, collName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, db, collName)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, db, collName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGrpc_HasCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasCollection'
type MockGrpc_HasCollection_Call struct {
	*mock.Call
}

// HasCollection is a helper method to define mock.On call
//   - ctx context.Context
//   - db string
//   - collName string
func (_e *MockGrpc_Expecter) HasCollection(ctx any, db any, collName any) *MockGrpc_HasCollection_Call {
	return &MockGrpc_HasCollection_Call{Call: _e.mock.On("HasCollection", ctx, db, collName)}
}

func (_c *MockGrpc_HasCollection_Call) Run(run func(ctx context.Context, db string, collName string)) *MockGrpc_HasCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGrpc_HasCollection_Call) Return(b bool, err error) *MockGrpc_HasCollection_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockGrpc_HasCollection_Call) RunAndReturn(run func(ctx context.Context, db string, collName string) (bool, error)) *MockGrpc_HasCollection_Call {
	_c.Call.Return(run)
	return _c
}

// HasFeature provides a mock function for the type MockGrpc
func (_mock *MockGrpc) HasFeature(flag FeatureFlag) bool {
	ret := _mock.Called(flag)

	if len(ret) == 0 {
		panic("no return value specified for HasFeature")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(FeatureFlag) bool); ok {
		r0 = returnFunc(flag)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockGrpc_HasFeature_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasFeature'
type MockGrpc_HasFeature_Call struct {
	*mock.Call
}

// HasFeature is a helper method to define mock.On call
//   - flag FeatureFlag
func (_e *MockGrpc_Expecter) HasFeature(flag any) *MockGrpc_HasFeature_Call {
	return &MockGrpc_HasFeature_Call{Call: _e.mock.On("HasFeature", flag)}
}

func (_c *MockGrpc_HasFeature_Call) Run(run func(flag FeatureFlag)) *MockGrpc_HasFeature_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 FeatureFlag
		if args[0] != nil {
			arg0 = args[0].(FeatureFlag)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGrpc_HasFeature_Call) Return(b bool) *MockGrpc_HasFeature_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockGrpc_HasFeature_Call) RunAndReturn(run func(flag FeatureFlag) bool) *MockGrpc_HasFeature_Call {
	_c.Call.Return(run)
	return _c
}

// HasPartition provides a mock function for the type MockGrpc
func (_mock *MockGrpc) HasPartition(ctx context.Context, db string, collName string, partitionName string) (bool, error) {
	ret := _mock.Called(ctx, db, collName, partitionName)

	if len(ret) == 0 {
		panic("no return value specified for HasPartition")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (bool, error)); ok {
		return returnFunc(ctx, db, collName, partitionName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) bool); ok {
		r0 = returnFunc(ctx, db, collName, partitionName)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, db, collName, partitionName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGrpc_HasPartition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasPartition'
type MockGrpc_HasPartition_Call struct {
	*mock.Call
}

// HasPartition is a helper method to define mock.On call
//   - ctx context.Context
//   - db string
//   - collName string
//   - partitionName string
func (_e *MockGrpc_Expecter) HasPartition(ctx any, db any, collName any, partitionName any) *MockGrpc_HasPartition_Call {
	return &MockGrpc_HasPartition_Call{Call: _e.mock.On("HasPartition", ctx, db, collName, partitionName)}
}

func (_c *MockGrpc_HasPartition_Call) Run(run func(ctx context.Context, db string, collName string, partitionName string)) *MockGrpc_HasPartition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockGrpc_HasPartition_Call) Return(b bool, err error) *MockGrpc_HasPartition_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockGrpc_HasPartition_Call) RunAndReturn(run func(ctx context.Context, db string, collName string, partitionName string) (bool, error)) *MockGrpc_HasPartition_Call {
	_c.Call.Return(run)
	return _c
}

// ListCollections provides a mock function for the type MockGrpc
func (_mock *MockGrpc) ListCollections(ctx context.Context, db string) (*milvuspb.ShowCollectionsResponse, error) {
	ret := _mock.Called(ctx, db)

	if len(ret) == 0 {
		panic("no return value specified for ListCollections")
	}

	var r0 *milvuspb.ShowCollectionsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*milvuspb.ShowCollectionsResponse, error)); ok {
		return returnFunc(ctx, db)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *milvuspb.ShowCollectionsResponse); ok {
		r0 = returnFunc(ctx, db)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*milvuspb.ShowCollectionsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, db)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGrpc_ListCollections_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCollections'
type MockGrpc_ListCollections_Call struct {
	*mock.Call
}

// ListCollections is a helper method to define mock.On call
//   - ctx context.Context
//   - db string
func (_e *MockGrpc_Expecter) ListCollections(ctx any, db any) *MockGrpc_ListCollections_Call {
	return &MockGrpc_ListCollections_Call{Call: _e.mock.On("ListCollections", ctx, db)}
}

func (_c *MockGrpc_ListCollections_Call) Run(run func(ctx context.Context, db string)) *MockGrpc_ListCollections_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGrpc_ListCollections_Call) Return(showCollectionsResponse *milvuspb.ShowCollectionsResponse, err error) *MockGrpc_ListCollections_Call {
	_c.Call.Return(showCollectionsResponse, err)
	return _c
}

func (_c *MockGrpc_ListCollections_Call) RunAndReturn(run func(ctx context.Context, db string) (*milvuspb.ShowCollectionsResponse, error)) *MockGrpc_ListCollections_Call {
	_c.Call.Return(run)
	return _c
}

// ListDatabases provides a mock function for the type MockGrpc
func (_mock *MockGrpc) ListDatabases(ctx context.Context) ([]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListDatabases")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGrpc_ListDatabases_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDatabases'
type MockGrpc_ListDatabases_Call struct {
	*mock.Call
}

// ListDatabases is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGrpc_Expecter) ListDatabases(ctx any) *MockGrpc_ListDatabases_Call {
	return &MockGrpc_ListDatabases_Call{Call: _e.mock.On("ListDatabases", ctx)}
}

func (_c *MockGrpc_ListDatabases_Call) Run(run func(ctx context.Context)) *MockGrpc_ListDatabases_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGrpc_ListDatabases_Call) Return(strings []string, err error) *MockGrpc_ListDatabases_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockGrpc_ListDatabases_Call) RunAndReturn(run func(ctx context.Context) ([]string, error)) *MockGrpc_ListDatabases_Call {
	_c.Call.Return(run)
	return _c
}

// ListIndex provides a mock function for the type MockGrpc
func (_mock *MockGrpc) ListIndex(ctx context.Context, db string, collName string) ([]*milvuspb.IndexDescription, error) {
	ret := _mock.Called(ctx, db, collName)

	if len(ret) == 0 {
		panic("no return value specified for ListIndex")
	}

	var r0 []*milvuspb.IndexDescription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]*milvuspb.IndexDescription, error)); ok {
		return returnFunc(ctx, db, collName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []*milvuspb.IndexDescription); ok {
		r0 = returnFunc(ctx, db, collName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*milvuspb.IndexDescription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, db, collName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGrpc_ListIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListIndex'
type MockGrpc_ListIndex_Call struct {
	*mock.Call
}

// ListIndex is a helper method to define mock.On call
//   - ctx context.Context
//   - db string
//   - collName string
func (_e *MockGrpc_Expecter) ListIndex(ctx any, db any, collName any) *MockGrpc_ListIndex_Call {
	return &MockGrpc_ListIndex_Call{Call: _e.mock.On("ListIndex", ctx, db, collName)}
}

func (_c *MockGrpc_ListIndex_Call) Run(run func(ctx context.Context, db string, collName string)) *MockGrpc_ListIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGrpc_ListIndex_Call) Return(indexDescriptions []*milvuspb.IndexDescription, err error) *MockGrpc_ListIndex_Call {
	_c.Call.Return(indexDescriptions, err)
	return _c
}

func (_c *MockGrpc_ListIndex_Call) RunAndReturn(run func(ctx context.Context, db string, collName string) ([]*milvuspb.IndexDescription, error)) *MockGrpc_ListIndex_Call {
	_c.Call.Return(run)
	return _c
}

// ReplicateMessage provides a mock function for the type MockGrpc
func (_mock *MockGrpc) ReplicateMessage(ctx context.Context, channelName string) (string, error) {
	ret := _mock.Called(ctx, channelName)

	if len(ret) == 0 {
		panic("no return value specified for ReplicateMessage")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, channelName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, channelName)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, channelName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGrpc_ReplicateMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplicateMessage'
type MockGrpc_ReplicateMessage_Call struct {
	*mock.Call
}

// ReplicateMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - channelName string
func (_e *MockGrpc_Expecter) ReplicateMessage(ctx any, channelName any) *MockGrpc_ReplicateMessage_Call {
	return &MockGrpc_ReplicateMessage_Call{Call: _e.mock.On("ReplicateMessage", ctx, channelName)}
}

func (_c *MockGrpc_ReplicateMessage_Call) Run(run func(ctx context.Context, channelName string)) *MockGrpc_ReplicateMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGrpc_ReplicateMessage_Call) Return(s string, err error) *MockGrpc_ReplicateMessage_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockGrpc_ReplicateMessage_Call) RunAndReturn(run func(ctx context.Context, channelName string) (string, error)) *MockGrpc_ReplicateMessage_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreExternalSnapshot provides a mock function for the type MockGrpc
func (_mock *MockGrpc) RestoreExternalSnapshot(ctx context.Context, input RestoreExternalSnapshotInput) (int64, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for RestoreExternalSnapshot")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, RestoreExternalSnapshotInput) (int64, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, RestoreExternalSnapshotInput) int64); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, RestoreExternalSnapshotInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGrpc_RestoreExternalSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreExternalSnapshot'
type MockGrpc_RestoreExternalSnapshot_Call struct {
	*mock.Call
}

// RestoreExternalSnapshot is a helper method to define mock.On call
//   - ctx context.Context
//   - input RestoreExternalSnapshotInput
func (_e *MockGrpc_Expecter) RestoreExternalSnapshot(ctx any, input any) *MockGrpc_RestoreExternalSnapshot_Call {
	return &MockGrpc_RestoreExternalSnapshot_Call{Call: _e.mock.On("RestoreExternalSnapshot", ctx, input)}
}

func (_c *MockGrpc_RestoreExternalSnapshot_Call) Run(run func(ctx context.Context, input RestoreExternalSnapshotInput)) *MockGrpc_RestoreExternalSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 RestoreExternalSnapshotInput
		if args[1] != nil {
			arg1 = args[1].(RestoreExternalSnapshotInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGrpc_RestoreExternalSnapshot_Call) Return(n int64, err error) *MockGrpc_RestoreExternalSnapshot_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockGrpc_RestoreExternalSnapshot_Call) RunAndReturn(run func(ctx context.Context, input RestoreExternalSnapshotInput) (int64, error)) *MockGrpc_RestoreExternalSnapshot_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreRBAC provides a mock function for the type MockGrpc
func (_mock *MockGrpc) RestoreRBAC(ctx context.Context, rbacMeta *milvuspb.RBACMeta) error {
	ret := _mock.Called(ctx, rbacMeta)

	if len(ret) == 0 {
		panic("no return value specified for RestoreRBAC")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *milvuspb.RBACMeta) error); ok {
		r0 = returnFunc(ctx, rbacMeta)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGrpc_RestoreRBAC_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreRBAC'
type MockGrpc_RestoreRBAC_Call struct {
	*mock.Call
}

// RestoreRBAC is a helper method to define mock.On call
//   - ctx context.Context
//   - rbacMeta *milvuspb.RBACMeta
func (_e *MockGrpc_Expecter) RestoreRBAC(ctx any, rbacMeta any) *MockGrpc_RestoreRBAC_Call {
	return &MockGrpc_RestoreRBAC_Call{Call: _e.mock.On("RestoreRBAC", ctx, rbacMeta)}
}

func (_c *MockGrpc_RestoreRBAC_Call) Run(run func(ctx context.Context, rbacMeta *milvuspb.RBACMeta)) *MockGrpc_RestoreRBAC_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *milvuspb.RBACMeta
		if args[1] != nil {
			arg1 = args[1].(*milvuspb.RBACMeta)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGrpc_RestoreRBAC_Call) Return(err error) *MockGrpc_RestoreRBAC_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGrpc_RestoreRBAC_Call) RunAndReturn(run func(ctx context.Context, rbacMeta *milvuspb.RBACMeta) error) *MockGrpc_RestoreRBAC_Call {
	_c.Call.Return(run)
	return _c
}

// ShowPartitions provides a mock function for the type MockGrpc
func (_mock *MockGrpc) ShowPartitions(ctx context.Context, db string, collName string) (*milvuspb.ShowPartitionsResponse, error) {
	ret := _mock.Called(ctx, db, collName)

	if len(ret) == 0 {
		panic("no return value specified for ShowPartitions")
	}

	var r0 *milvuspb.ShowPartitionsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*milvuspb.ShowPartitionsResponse, error)); ok {
		return returnFunc(ctx, db, collName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *milvuspb.ShowPartitionsResponse); ok {
		r0 = returnFunc(ctx, db, collName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*milvuspb.ShowPartitionsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, db, collName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGrpc_ShowPartitions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShowPartitions'
type MockGrpc_ShowPartitions_Call struct {
	*mock.Call
}

// ShowPartitions is a helper method to define mock.On call
//   - ctx context.Context
//   - db string
//   - collName string
func (_e *MockGrpc_Expecter) ShowPartitions(ctx any, db any, collName any) *MockGrpc_ShowPartitions_Call {
	return &MockGrpc_ShowPartitions_Call{Call: _e.mock.On("ShowPartitions", ctx, db, collName)}
}

func (_c *MockGrpc_ShowPartitions_Call) Run(run func(ctx context.Context, db string, collName string)) *MockGrpc_ShowPartitions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGrpc_ShowPartitions_Call) Return(showPartitionsResponse *milvuspb.ShowPartitionsResponse, err error) *MockGrpc_ShowPartitions_Call {
	_c.Call.Return(showPartitionsResponse, err)
	return _c
}

func (_c *MockGrpc_ShowPartitions_Call) RunAndReturn(run func(ctx context.Context, db string, collName string) (*milvuspb.ShowPartitionsResponse, error)) *MockGrpc_ShowPartitions_Call {
	_c.Call.Return(run)
	return _c
}
