// Code generated by protoc-gen-go. DO NOT EDIT.
// source: backup.proto

package backuppb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MsgType int32

const (
	MsgType_Undefined    MsgType = 0
	MsgType_CreateBackup MsgType = 100
	MsgType_GetBackup    MsgType = 101
	MsgType_ListBackups  MsgType = 102
	MsgType_DeleteBackup MsgType = 103
	MsgType_LoadBackup   MsgType = 104
)

var MsgType_name = map[int32]string{
	0:   "Undefined",
	100: "CreateBackup",
	101: "GetBackup",
	102: "ListBackups",
	103: "DeleteBackup",
	104: "LoadBackup",
}

var MsgType_value = map[string]int32{
	"Undefined":    0,
	"CreateBackup": 100,
	"GetBackup":    101,
	"ListBackups":  102,
	"DeleteBackup": 103,
	"LoadBackup":   104,
}

func (x MsgType) String() string {
	return proto.EnumName(MsgType_name, int32(x))
}

func (MsgType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{0}
}

type StatusCode int32

const (
	StatusCode_Unknown StatusCode = 0
	StatusCode_Success StatusCode = 1
	StatusCode_Fail    StatusCode = 2
	StatusCode_Timeout StatusCode = 3
)

var StatusCode_name = map[int32]string{
	0: "Unknown",
	1: "Success",
	2: "Fail",
	3: "Timeout",
}

var StatusCode_value = map[string]int32{
	"Unknown": 0,
	"Success": 1,
	"Fail":    2,
	"Timeout": 3,
}

func (x StatusCode) String() string {
	return proto.EnumName(StatusCode_name, int32(x))
}

func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{1}
}

type BackupTaskStateCode int32

const (
	BackupTaskStateCode_BACKUP_INITIAL   BackupTaskStateCode = 0
	BackupTaskStateCode_BACKUP_EXECUTING BackupTaskStateCode = 1
	BackupTaskStateCode_BACKUP_SUCCESS   BackupTaskStateCode = 2
	BackupTaskStateCode_BACKUP_FAIL      BackupTaskStateCode = 3
	BackupTaskStateCode_BACKUP_TIMEOUT   BackupTaskStateCode = 4
)

var BackupTaskStateCode_name = map[int32]string{
	0: "BACKUP_INITIAL",
	1: "BACKUP_EXECUTING",
	2: "BACKUP_SUCCESS",
	3: "BACKUP_FAIL",
	4: "BACKUP_TIMEOUT",
}

var BackupTaskStateCode_value = map[string]int32{
	"BACKUP_INITIAL":   0,
	"BACKUP_EXECUTING": 1,
	"BACKUP_SUCCESS":   2,
	"BACKUP_FAIL":      3,
	"BACKUP_TIMEOUT":   4,
}

func (x BackupTaskStateCode) String() string {
	return proto.EnumName(BackupTaskStateCode_name, int32(x))
}

func (BackupTaskStateCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{2}
}

type LoadTaskStateCode int32

const (
	LoadTaskStateCode_LOAD_INITIAL   LoadTaskStateCode = 0
	LoadTaskStateCode_LOAD_EXECUTING LoadTaskStateCode = 1
	LoadTaskStateCode_LOAD_SUCCESS   LoadTaskStateCode = 2
	LoadTaskStateCode_LOAD_FAIL      LoadTaskStateCode = 3
	LoadTaskStateCode_LOAD_TIMEOUT   LoadTaskStateCode = 4
)

var LoadTaskStateCode_name = map[int32]string{
	0: "LOAD_INITIAL",
	1: "LOAD_EXECUTING",
	2: "LOAD_SUCCESS",
	3: "LOAD_FAIL",
	4: "LOAD_TIMEOUT",
}

var LoadTaskStateCode_value = map[string]int32{
	"LOAD_INITIAL":   0,
	"LOAD_EXECUTING": 1,
	"LOAD_SUCCESS":   2,
	"LOAD_FAIL":      3,
	"LOAD_TIMEOUT":   4,
}

func (x LoadTaskStateCode) String() string {
	return proto.EnumName(LoadTaskStateCode_name, int32(x))
}

func (LoadTaskStateCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{3}
}

type ConsistencyLevel int32

const (
	ConsistencyLevel_Strong     ConsistencyLevel = 0
	ConsistencyLevel_Session    ConsistencyLevel = 1
	ConsistencyLevel_Bounded    ConsistencyLevel = 2
	ConsistencyLevel_Eventually ConsistencyLevel = 3
	ConsistencyLevel_Customized ConsistencyLevel = 4
)

var ConsistencyLevel_name = map[int32]string{
	0: "Strong",
	1: "Session",
	2: "Bounded",
	3: "Eventually",
	4: "Customized",
}

var ConsistencyLevel_value = map[string]int32{
	"Strong":     0,
	"Session":    1,
	"Bounded":    2,
	"Eventually": 3,
	"Customized": 4,
}

func (x ConsistencyLevel) String() string {
	return proto.EnumName(ConsistencyLevel_name, int32(x))
}

func (ConsistencyLevel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{4}
}

//*
// @brief Field data type
type DataType int32

const (
	DataType_None         DataType = 0
	DataType_Bool         DataType = 1
	DataType_Int8         DataType = 2
	DataType_Int16        DataType = 3
	DataType_Int32        DataType = 4
	DataType_Int64        DataType = 5
	DataType_Float        DataType = 10
	DataType_Double       DataType = 11
	DataType_String       DataType = 20
	DataType_VarChar      DataType = 21
	DataType_BinaryVector DataType = 100
	DataType_FloatVector  DataType = 101
)

var DataType_name = map[int32]string{
	0:   "None",
	1:   "Bool",
	2:   "Int8",
	3:   "Int16",
	4:   "Int32",
	5:   "Int64",
	10:  "Float",
	11:  "Double",
	20:  "String",
	21:  "VarChar",
	100: "BinaryVector",
	101: "FloatVector",
}

var DataType_value = map[string]int32{
	"None":         0,
	"Bool":         1,
	"Int8":         2,
	"Int16":        3,
	"Int32":        4,
	"Int64":        5,
	"Float":        10,
	"Double":       11,
	"String":       20,
	"VarChar":      21,
	"BinaryVector": 100,
	"FloatVector":  101,
}

func (x DataType) String() string {
	return proto.EnumName(DataType_name, int32(x))
}

func (DataType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{5}
}

type FieldState int32

const (
	FieldState_FieldCreated  FieldState = 0
	FieldState_FieldCreating FieldState = 1
	FieldState_FieldDropping FieldState = 2
	FieldState_FieldDropped  FieldState = 3
)

var FieldState_name = map[int32]string{
	0: "FieldCreated",
	1: "FieldCreating",
	2: "FieldDropping",
	3: "FieldDropped",
}

var FieldState_value = map[string]int32{
	"FieldCreated":  0,
	"FieldCreating": 1,
	"FieldDropping": 2,
	"FieldDropped":  3,
}

func (x FieldState) String() string {
	return proto.EnumName(FieldState_name, int32(x))
}

func (FieldState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{6}
}

type MsgBase struct {
	MsgType              MsgType  `protobuf:"varint,1,opt,name=msg_type,json=msgType,proto3,enum=milvus.proto.backup.MsgType" json:"msg_type,omitempty"`
	MsgID                int64    `protobuf:"varint,2,opt,name=msgID,proto3" json:"msgID,omitempty"`
	Timestamp            uint64   `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgBase) Reset()         { *m = MsgBase{} }
func (m *MsgBase) String() string { return proto.CompactTextString(m) }
func (*MsgBase) ProtoMessage()    {}
func (*MsgBase) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{0}
}

func (m *MsgBase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgBase.Unmarshal(m, b)
}
func (m *MsgBase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgBase.Marshal(b, m, deterministic)
}
func (m *MsgBase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBase.Merge(m, src)
}
func (m *MsgBase) XXX_Size() int {
	return xxx_messageInfo_MsgBase.Size(m)
}
func (m *MsgBase) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBase.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBase proto.InternalMessageInfo

func (m *MsgBase) GetMsgType() MsgType {
	if m != nil {
		return m.MsgType
	}
	return MsgType_Undefined
}

func (m *MsgBase) GetMsgID() int64 {
	if m != nil {
		return m.MsgID
	}
	return 0
}

func (m *MsgBase) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type Status struct {
	StatusCode           StatusCode `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3,enum=milvus.proto.backup.StatusCode" json:"status_code,omitempty"`
	Reason               string     `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{1}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetStatusCode() StatusCode {
	if m != nil {
		return m.StatusCode
	}
	return StatusCode_Unknown
}

func (m *Status) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

//*
// lite version of Collection info
type CollectionBackupInfo struct {
	BackupState      *BackupTaskState  `protobuf:"bytes,1,opt,name=backup_state,json=backupState,proto3" json:"backup_state,omitempty"`
	CollectionId     int64             `protobuf:"varint,2,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	DbName           string            `protobuf:"bytes,3,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	CollectionName   string            `protobuf:"bytes,4,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	Schema           *CollectionSchema `protobuf:"bytes,5,opt,name=schema,proto3" json:"schema,omitempty"`
	ShardsNum        int32             `protobuf:"varint,6,opt,name=shards_num,json=shardsNum,proto3" json:"shards_num,omitempty"`
	ConsistencyLevel ConsistencyLevel  `protobuf:"varint,7,opt,name=consistency_level,json=consistencyLevel,proto3,enum=milvus.proto.backup.ConsistencyLevel" json:"consistency_level,omitempty"`
	// array of partition backup
	PartitionBackups     []*PartitionBackupInfo `protobuf:"bytes,8,rep,name=partition_backups,json=partitionBackups,proto3" json:"partition_backups,omitempty"`
	BackupTimestamp      uint64                 `protobuf:"varint,9,opt,name=backup_timestamp,json=backupTimestamp,proto3" json:"backup_timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *CollectionBackupInfo) Reset()         { *m = CollectionBackupInfo{} }
func (m *CollectionBackupInfo) String() string { return proto.CompactTextString(m) }
func (*CollectionBackupInfo) ProtoMessage()    {}
func (*CollectionBackupInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{2}
}

func (m *CollectionBackupInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectionBackupInfo.Unmarshal(m, b)
}
func (m *CollectionBackupInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectionBackupInfo.Marshal(b, m, deterministic)
}
func (m *CollectionBackupInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectionBackupInfo.Merge(m, src)
}
func (m *CollectionBackupInfo) XXX_Size() int {
	return xxx_messageInfo_CollectionBackupInfo.Size(m)
}
func (m *CollectionBackupInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectionBackupInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CollectionBackupInfo proto.InternalMessageInfo

func (m *CollectionBackupInfo) GetBackupState() *BackupTaskState {
	if m != nil {
		return m.BackupState
	}
	return nil
}

func (m *CollectionBackupInfo) GetCollectionId() int64 {
	if m != nil {
		return m.CollectionId
	}
	return 0
}

func (m *CollectionBackupInfo) GetDbName() string {
	if m != nil {
		return m.DbName
	}
	return ""
}

func (m *CollectionBackupInfo) GetCollectionName() string {
	if m != nil {
		return m.CollectionName
	}
	return ""
}

func (m *CollectionBackupInfo) GetSchema() *CollectionSchema {
	if m != nil {
		return m.Schema
	}
	return nil
}

func (m *CollectionBackupInfo) GetShardsNum() int32 {
	if m != nil {
		return m.ShardsNum
	}
	return 0
}

func (m *CollectionBackupInfo) GetConsistencyLevel() ConsistencyLevel {
	if m != nil {
		return m.ConsistencyLevel
	}
	return ConsistencyLevel_Strong
}

func (m *CollectionBackupInfo) GetPartitionBackups() []*PartitionBackupInfo {
	if m != nil {
		return m.PartitionBackups
	}
	return nil
}

func (m *CollectionBackupInfo) GetBackupTimestamp() uint64 {
	if m != nil {
		return m.BackupTimestamp
	}
	return 0
}

type PartitionBackupInfo struct {
	PartitionId   int64  `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	PartitionName string `protobuf:"bytes,2,opt,name=partition_name,json=partitionName,proto3" json:"partition_name,omitempty"`
	CollectionId  int64  `protobuf:"varint,3,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	// array of segment backup
	SegmentBackups       []*SegmentBackupInfo `protobuf:"bytes,7,rep,name=segment_backups,json=segmentBackups,proto3" json:"segment_backups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PartitionBackupInfo) Reset()         { *m = PartitionBackupInfo{} }
func (m *PartitionBackupInfo) String() string { return proto.CompactTextString(m) }
func (*PartitionBackupInfo) ProtoMessage()    {}
func (*PartitionBackupInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{3}
}

func (m *PartitionBackupInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartitionBackupInfo.Unmarshal(m, b)
}
func (m *PartitionBackupInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartitionBackupInfo.Marshal(b, m, deterministic)
}
func (m *PartitionBackupInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartitionBackupInfo.Merge(m, src)
}
func (m *PartitionBackupInfo) XXX_Size() int {
	return xxx_messageInfo_PartitionBackupInfo.Size(m)
}
func (m *PartitionBackupInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PartitionBackupInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PartitionBackupInfo proto.InternalMessageInfo

func (m *PartitionBackupInfo) GetPartitionId() int64 {
	if m != nil {
		return m.PartitionId
	}
	return 0
}

func (m *PartitionBackupInfo) GetPartitionName() string {
	if m != nil {
		return m.PartitionName
	}
	return ""
}

func (m *PartitionBackupInfo) GetCollectionId() int64 {
	if m != nil {
		return m.CollectionId
	}
	return 0
}

func (m *PartitionBackupInfo) GetSegmentBackups() []*SegmentBackupInfo {
	if m != nil {
		return m.SegmentBackups
	}
	return nil
}

//*
// lite version of datapb.SegmentInfo
type SegmentBackupInfo struct {
	SegmentId            int64          `protobuf:"varint,1,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	CollectionId         int64          `protobuf:"varint,2,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	PartitionId          int64          `protobuf:"varint,3,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	NumOfRows            int64          `protobuf:"varint,4,opt,name=num_of_rows,json=numOfRows,proto3" json:"num_of_rows,omitempty"`
	Binlogs              []*FieldBinlog `protobuf:"bytes,5,rep,name=binlogs,proto3" json:"binlogs,omitempty"`
	Statslogs            []*FieldBinlog `protobuf:"bytes,6,rep,name=statslogs,proto3" json:"statslogs,omitempty"`
	Deltalogs            []*FieldBinlog `protobuf:"bytes,7,rep,name=deltalogs,proto3" json:"deltalogs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SegmentBackupInfo) Reset()         { *m = SegmentBackupInfo{} }
func (m *SegmentBackupInfo) String() string { return proto.CompactTextString(m) }
func (*SegmentBackupInfo) ProtoMessage()    {}
func (*SegmentBackupInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{4}
}

func (m *SegmentBackupInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SegmentBackupInfo.Unmarshal(m, b)
}
func (m *SegmentBackupInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SegmentBackupInfo.Marshal(b, m, deterministic)
}
func (m *SegmentBackupInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SegmentBackupInfo.Merge(m, src)
}
func (m *SegmentBackupInfo) XXX_Size() int {
	return xxx_messageInfo_SegmentBackupInfo.Size(m)
}
func (m *SegmentBackupInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SegmentBackupInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SegmentBackupInfo proto.InternalMessageInfo

func (m *SegmentBackupInfo) GetSegmentId() int64 {
	if m != nil {
		return m.SegmentId
	}
	return 0
}

func (m *SegmentBackupInfo) GetCollectionId() int64 {
	if m != nil {
		return m.CollectionId
	}
	return 0
}

func (m *SegmentBackupInfo) GetPartitionId() int64 {
	if m != nil {
		return m.PartitionId
	}
	return 0
}

func (m *SegmentBackupInfo) GetNumOfRows() int64 {
	if m != nil {
		return m.NumOfRows
	}
	return 0
}

func (m *SegmentBackupInfo) GetBinlogs() []*FieldBinlog {
	if m != nil {
		return m.Binlogs
	}
	return nil
}

func (m *SegmentBackupInfo) GetStatslogs() []*FieldBinlog {
	if m != nil {
		return m.Statslogs
	}
	return nil
}

func (m *SegmentBackupInfo) GetDeltalogs() []*FieldBinlog {
	if m != nil {
		return m.Deltalogs
	}
	return nil
}

//*
// root of backup
type BackupInfo struct {
	BackupState *BackupTaskState `protobuf:"bytes,1,opt,name=backup_state,json=backupState,proto3" json:"backup_state,omitempty"`
	Name        string           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// backup timestamp
	BackupTimestamp uint64 `protobuf:"varint,3,opt,name=backup_timestamp,json=backupTimestamp,proto3" json:"backup_timestamp,omitempty"`
	// array of collection backup
	CollectionBackups    []*CollectionBackupInfo `protobuf:"bytes,4,rep,name=collection_backups,json=collectionBackups,proto3" json:"collection_backups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *BackupInfo) Reset()         { *m = BackupInfo{} }
func (m *BackupInfo) String() string { return proto.CompactTextString(m) }
func (*BackupInfo) ProtoMessage()    {}
func (*BackupInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{5}
}

func (m *BackupInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackupInfo.Unmarshal(m, b)
}
func (m *BackupInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackupInfo.Marshal(b, m, deterministic)
}
func (m *BackupInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackupInfo.Merge(m, src)
}
func (m *BackupInfo) XXX_Size() int {
	return xxx_messageInfo_BackupInfo.Size(m)
}
func (m *BackupInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BackupInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BackupInfo proto.InternalMessageInfo

func (m *BackupInfo) GetBackupState() *BackupTaskState {
	if m != nil {
		return m.BackupState
	}
	return nil
}

func (m *BackupInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BackupInfo) GetBackupTimestamp() uint64 {
	if m != nil {
		return m.BackupTimestamp
	}
	return 0
}

func (m *BackupInfo) GetCollectionBackups() []*CollectionBackupInfo {
	if m != nil {
		return m.CollectionBackups
	}
	return nil
}

//*
// For level storage
type CollectionLevelBackupInfo struct {
	Infos                []*CollectionBackupInfo `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *CollectionLevelBackupInfo) Reset()         { *m = CollectionLevelBackupInfo{} }
func (m *CollectionLevelBackupInfo) String() string { return proto.CompactTextString(m) }
func (*CollectionLevelBackupInfo) ProtoMessage()    {}
func (*CollectionLevelBackupInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{6}
}

func (m *CollectionLevelBackupInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectionLevelBackupInfo.Unmarshal(m, b)
}
func (m *CollectionLevelBackupInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectionLevelBackupInfo.Marshal(b, m, deterministic)
}
func (m *CollectionLevelBackupInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectionLevelBackupInfo.Merge(m, src)
}
func (m *CollectionLevelBackupInfo) XXX_Size() int {
	return xxx_messageInfo_CollectionLevelBackupInfo.Size(m)
}
func (m *CollectionLevelBackupInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectionLevelBackupInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CollectionLevelBackupInfo proto.InternalMessageInfo

func (m *CollectionLevelBackupInfo) GetInfos() []*CollectionBackupInfo {
	if m != nil {
		return m.Infos
	}
	return nil
}

//*
// For level storage
type PartitionLevelBackupInfo struct {
	Infos                []*PartitionBackupInfo `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *PartitionLevelBackupInfo) Reset()         { *m = PartitionLevelBackupInfo{} }
func (m *PartitionLevelBackupInfo) String() string { return proto.CompactTextString(m) }
func (*PartitionLevelBackupInfo) ProtoMessage()    {}
func (*PartitionLevelBackupInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{7}
}

func (m *PartitionLevelBackupInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartitionLevelBackupInfo.Unmarshal(m, b)
}
func (m *PartitionLevelBackupInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartitionLevelBackupInfo.Marshal(b, m, deterministic)
}
func (m *PartitionLevelBackupInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartitionLevelBackupInfo.Merge(m, src)
}
func (m *PartitionLevelBackupInfo) XXX_Size() int {
	return xxx_messageInfo_PartitionLevelBackupInfo.Size(m)
}
func (m *PartitionLevelBackupInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PartitionLevelBackupInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PartitionLevelBackupInfo proto.InternalMessageInfo

func (m *PartitionLevelBackupInfo) GetInfos() []*PartitionBackupInfo {
	if m != nil {
		return m.Infos
	}
	return nil
}

//*
// For level storage
type SegmentLevelBackupInfo struct {
	Infos                []*SegmentBackupInfo `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SegmentLevelBackupInfo) Reset()         { *m = SegmentLevelBackupInfo{} }
func (m *SegmentLevelBackupInfo) String() string { return proto.CompactTextString(m) }
func (*SegmentLevelBackupInfo) ProtoMessage()    {}
func (*SegmentLevelBackupInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{8}
}

func (m *SegmentLevelBackupInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SegmentLevelBackupInfo.Unmarshal(m, b)
}
func (m *SegmentLevelBackupInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SegmentLevelBackupInfo.Marshal(b, m, deterministic)
}
func (m *SegmentLevelBackupInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SegmentLevelBackupInfo.Merge(m, src)
}
func (m *SegmentLevelBackupInfo) XXX_Size() int {
	return xxx_messageInfo_SegmentLevelBackupInfo.Size(m)
}
func (m *SegmentLevelBackupInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SegmentLevelBackupInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SegmentLevelBackupInfo proto.InternalMessageInfo

func (m *SegmentLevelBackupInfo) GetInfos() []*SegmentBackupInfo {
	if m != nil {
		return m.Infos
	}
	return nil
}

//*
// Create Backup in milvus
type CreateBackupRequest struct {
	Base *MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	// backup name, if not set, will generate one
	BackupName string `protobuf:"bytes,2,opt,name=backup_name,json=backupName,proto3" json:"backup_name,omitempty"`
	// collection names to backup, empty to backup all
	CollectionNames      []string `protobuf:"bytes,3,rep,name=collection_names,json=collectionNames,proto3" json:"collection_names,omitempty"`
	Async                bool     `protobuf:"varint,4,opt,name=async,proto3" json:"async,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBackupRequest) Reset()         { *m = CreateBackupRequest{} }
func (m *CreateBackupRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBackupRequest) ProtoMessage()    {}
func (*CreateBackupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{9}
}

func (m *CreateBackupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBackupRequest.Unmarshal(m, b)
}
func (m *CreateBackupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBackupRequest.Marshal(b, m, deterministic)
}
func (m *CreateBackupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBackupRequest.Merge(m, src)
}
func (m *CreateBackupRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBackupRequest.Size(m)
}
func (m *CreateBackupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBackupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBackupRequest proto.InternalMessageInfo

func (m *CreateBackupRequest) GetBase() *MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *CreateBackupRequest) GetBackupName() string {
	if m != nil {
		return m.BackupName
	}
	return ""
}

func (m *CreateBackupRequest) GetCollectionNames() []string {
	if m != nil {
		return m.CollectionNames
	}
	return nil
}

func (m *CreateBackupRequest) GetAsync() bool {
	if m != nil {
		return m.Async
	}
	return false
}

//*
// BackupInfoResponse
type BackupInfoResponse struct {
	Status               *Status     `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	BackupInfo           *BackupInfo `protobuf:"bytes,2,opt,name=backup_info,json=backupInfo,proto3" json:"backup_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *BackupInfoResponse) Reset()         { *m = BackupInfoResponse{} }
func (m *BackupInfoResponse) String() string { return proto.CompactTextString(m) }
func (*BackupInfoResponse) ProtoMessage()    {}
func (*BackupInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{10}
}

func (m *BackupInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackupInfoResponse.Unmarshal(m, b)
}
func (m *BackupInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackupInfoResponse.Marshal(b, m, deterministic)
}
func (m *BackupInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackupInfoResponse.Merge(m, src)
}
func (m *BackupInfoResponse) XXX_Size() int {
	return xxx_messageInfo_BackupInfoResponse.Size(m)
}
func (m *BackupInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BackupInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BackupInfoResponse proto.InternalMessageInfo

func (m *BackupInfoResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *BackupInfoResponse) GetBackupInfo() *BackupInfo {
	if m != nil {
		return m.BackupInfo
	}
	return nil
}

type GetBackupRequest struct {
	Base                 *MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	BackupName           string   `protobuf:"bytes,2,opt,name=backup_name,json=backupName,proto3" json:"backup_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBackupRequest) Reset()         { *m = GetBackupRequest{} }
func (m *GetBackupRequest) String() string { return proto.CompactTextString(m) }
func (*GetBackupRequest) ProtoMessage()    {}
func (*GetBackupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{11}
}

func (m *GetBackupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBackupRequest.Unmarshal(m, b)
}
func (m *GetBackupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBackupRequest.Marshal(b, m, deterministic)
}
func (m *GetBackupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBackupRequest.Merge(m, src)
}
func (m *GetBackupRequest) XXX_Size() int {
	return xxx_messageInfo_GetBackupRequest.Size(m)
}
func (m *GetBackupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBackupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBackupRequest proto.InternalMessageInfo

func (m *GetBackupRequest) GetBase() *MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *GetBackupRequest) GetBackupName() string {
	if m != nil {
		return m.BackupName
	}
	return ""
}

type ListBackupsRequest struct {
	Base                 *MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	CollectionName       string   `protobuf:"bytes,2,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBackupsRequest) Reset()         { *m = ListBackupsRequest{} }
func (m *ListBackupsRequest) String() string { return proto.CompactTextString(m) }
func (*ListBackupsRequest) ProtoMessage()    {}
func (*ListBackupsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{12}
}

func (m *ListBackupsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBackupsRequest.Unmarshal(m, b)
}
func (m *ListBackupsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBackupsRequest.Marshal(b, m, deterministic)
}
func (m *ListBackupsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBackupsRequest.Merge(m, src)
}
func (m *ListBackupsRequest) XXX_Size() int {
	return xxx_messageInfo_ListBackupsRequest.Size(m)
}
func (m *ListBackupsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBackupsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListBackupsRequest proto.InternalMessageInfo

func (m *ListBackupsRequest) GetBase() *MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *ListBackupsRequest) GetCollectionName() string {
	if m != nil {
		return m.CollectionName
	}
	return ""
}

type ListBackupsResponse struct {
	Status               *Status       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	BackupInfos          []*BackupInfo `protobuf:"bytes,2,rep,name=backup_infos,json=backupInfos,proto3" json:"backup_infos,omitempty"`
	FailBackups          []string      `protobuf:"bytes,3,rep,name=failBackups,proto3" json:"failBackups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListBackupsResponse) Reset()         { *m = ListBackupsResponse{} }
func (m *ListBackupsResponse) String() string { return proto.CompactTextString(m) }
func (*ListBackupsResponse) ProtoMessage()    {}
func (*ListBackupsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{13}
}

func (m *ListBackupsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBackupsResponse.Unmarshal(m, b)
}
func (m *ListBackupsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBackupsResponse.Marshal(b, m, deterministic)
}
func (m *ListBackupsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBackupsResponse.Merge(m, src)
}
func (m *ListBackupsResponse) XXX_Size() int {
	return xxx_messageInfo_ListBackupsResponse.Size(m)
}
func (m *ListBackupsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBackupsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListBackupsResponse proto.InternalMessageInfo

func (m *ListBackupsResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ListBackupsResponse) GetBackupInfos() []*BackupInfo {
	if m != nil {
		return m.BackupInfos
	}
	return nil
}

func (m *ListBackupsResponse) GetFailBackups() []string {
	if m != nil {
		return m.FailBackups
	}
	return nil
}

type DeleteBackupRequest struct {
	Base                 *MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	BackupName           string   `protobuf:"bytes,2,opt,name=backup_name,json=backupName,proto3" json:"backup_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBackupRequest) Reset()         { *m = DeleteBackupRequest{} }
func (m *DeleteBackupRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteBackupRequest) ProtoMessage()    {}
func (*DeleteBackupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{14}
}

func (m *DeleteBackupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBackupRequest.Unmarshal(m, b)
}
func (m *DeleteBackupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBackupRequest.Marshal(b, m, deterministic)
}
func (m *DeleteBackupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBackupRequest.Merge(m, src)
}
func (m *DeleteBackupRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteBackupRequest.Size(m)
}
func (m *DeleteBackupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBackupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBackupRequest proto.InternalMessageInfo

func (m *DeleteBackupRequest) GetBase() *MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *DeleteBackupRequest) GetBackupName() string {
	if m != nil {
		return m.BackupName
	}
	return ""
}

type DeleteBackupResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBackupResponse) Reset()         { *m = DeleteBackupResponse{} }
func (m *DeleteBackupResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteBackupResponse) ProtoMessage()    {}
func (*DeleteBackupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{15}
}

func (m *DeleteBackupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBackupResponse.Unmarshal(m, b)
}
func (m *DeleteBackupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBackupResponse.Marshal(b, m, deterministic)
}
func (m *DeleteBackupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBackupResponse.Merge(m, src)
}
func (m *DeleteBackupResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteBackupResponse.Size(m)
}
func (m *DeleteBackupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBackupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBackupResponse proto.InternalMessageInfo

func (m *DeleteBackupResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type BackupTaskState struct {
	Id                   int64               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code                 BackupTaskStateCode `protobuf:"varint,2,opt,name=code,proto3,enum=milvus.proto.backup.BackupTaskStateCode" json:"code,omitempty"`
	ErrorMessage         string              `protobuf:"bytes,3,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	StartTime            int64               `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              int64               `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Progress             int32               `protobuf:"varint,6,opt,name=progress,proto3" json:"progress,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *BackupTaskState) Reset()         { *m = BackupTaskState{} }
func (m *BackupTaskState) String() string { return proto.CompactTextString(m) }
func (*BackupTaskState) ProtoMessage()    {}
func (*BackupTaskState) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{16}
}

func (m *BackupTaskState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackupTaskState.Unmarshal(m, b)
}
func (m *BackupTaskState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackupTaskState.Marshal(b, m, deterministic)
}
func (m *BackupTaskState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackupTaskState.Merge(m, src)
}
func (m *BackupTaskState) XXX_Size() int {
	return xxx_messageInfo_BackupTaskState.Size(m)
}
func (m *BackupTaskState) XXX_DiscardUnknown() {
	xxx_messageInfo_BackupTaskState.DiscardUnknown(m)
}

var xxx_messageInfo_BackupTaskState proto.InternalMessageInfo

func (m *BackupTaskState) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BackupTaskState) GetCode() BackupTaskStateCode {
	if m != nil {
		return m.Code
	}
	return BackupTaskStateCode_BACKUP_INITIAL
}

func (m *BackupTaskState) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *BackupTaskState) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *BackupTaskState) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *BackupTaskState) GetProgress() int32 {
	if m != nil {
		return m.Progress
	}
	return 0
}

type LoadTaskState struct {
	Id                   int64             `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code                 LoadTaskStateCode `protobuf:"varint,2,opt,name=code,proto3,enum=milvus.proto.backup.LoadTaskStateCode" json:"code,omitempty"`
	ErrorMessage         string            `protobuf:"bytes,3,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	StartTime            int64             `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              int64             `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Progress             int32             `protobuf:"varint,6,opt,name=progress,proto3" json:"progress,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *LoadTaskState) Reset()         { *m = LoadTaskState{} }
func (m *LoadTaskState) String() string { return proto.CompactTextString(m) }
func (*LoadTaskState) ProtoMessage()    {}
func (*LoadTaskState) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{17}
}

func (m *LoadTaskState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadTaskState.Unmarshal(m, b)
}
func (m *LoadTaskState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadTaskState.Marshal(b, m, deterministic)
}
func (m *LoadTaskState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadTaskState.Merge(m, src)
}
func (m *LoadTaskState) XXX_Size() int {
	return xxx_messageInfo_LoadTaskState.Size(m)
}
func (m *LoadTaskState) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadTaskState.DiscardUnknown(m)
}

var xxx_messageInfo_LoadTaskState proto.InternalMessageInfo

func (m *LoadTaskState) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *LoadTaskState) GetCode() LoadTaskStateCode {
	if m != nil {
		return m.Code
	}
	return LoadTaskStateCode_LOAD_INITIAL
}

func (m *LoadTaskState) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *LoadTaskState) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *LoadTaskState) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *LoadTaskState) GetProgress() int32 {
	if m != nil {
		return m.Progress
	}
	return 0
}

type LoadPartitionTask struct {
	LoadState            *LoadTaskState       `protobuf:"bytes,1,opt,name=load_state,json=loadState,proto3" json:"load_state,omitempty"`
	PartBackup           *PartitionBackupInfo `protobuf:"bytes,2,opt,name=part_backup,json=partBackup,proto3" json:"part_backup,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *LoadPartitionTask) Reset()         { *m = LoadPartitionTask{} }
func (m *LoadPartitionTask) String() string { return proto.CompactTextString(m) }
func (*LoadPartitionTask) ProtoMessage()    {}
func (*LoadPartitionTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{18}
}

func (m *LoadPartitionTask) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadPartitionTask.Unmarshal(m, b)
}
func (m *LoadPartitionTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadPartitionTask.Marshal(b, m, deterministic)
}
func (m *LoadPartitionTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadPartitionTask.Merge(m, src)
}
func (m *LoadPartitionTask) XXX_Size() int {
	return xxx_messageInfo_LoadPartitionTask.Size(m)
}
func (m *LoadPartitionTask) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadPartitionTask.DiscardUnknown(m)
}

var xxx_messageInfo_LoadPartitionTask proto.InternalMessageInfo

func (m *LoadPartitionTask) GetLoadState() *LoadTaskState {
	if m != nil {
		return m.LoadState
	}
	return nil
}

func (m *LoadPartitionTask) GetPartBackup() *PartitionBackupInfo {
	if m != nil {
		return m.PartBackup
	}
	return nil
}

type LoadCollectionTask struct {
	LoadState            *LoadTaskState        `protobuf:"bytes,1,opt,name=load_state,json=loadState,proto3" json:"load_state,omitempty"`
	CollBackup           *CollectionBackupInfo `protobuf:"bytes,2,opt,name=coll_backup,json=collBackup,proto3" json:"coll_backup,omitempty"`
	TargetCollectionName string                `protobuf:"bytes,3,opt,name=target_collection_name,json=targetCollectionName,proto3" json:"target_collection_name,omitempty"`
	PartitionLoadTasks   []*LoadPartitionTask  `protobuf:"bytes,4,rep,name=partition_load_tasks,json=partitionLoadTasks,proto3" json:"partition_load_tasks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *LoadCollectionTask) Reset()         { *m = LoadCollectionTask{} }
func (m *LoadCollectionTask) String() string { return proto.CompactTextString(m) }
func (*LoadCollectionTask) ProtoMessage()    {}
func (*LoadCollectionTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{19}
}

func (m *LoadCollectionTask) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadCollectionTask.Unmarshal(m, b)
}
func (m *LoadCollectionTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadCollectionTask.Marshal(b, m, deterministic)
}
func (m *LoadCollectionTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadCollectionTask.Merge(m, src)
}
func (m *LoadCollectionTask) XXX_Size() int {
	return xxx_messageInfo_LoadCollectionTask.Size(m)
}
func (m *LoadCollectionTask) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadCollectionTask.DiscardUnknown(m)
}

var xxx_messageInfo_LoadCollectionTask proto.InternalMessageInfo

func (m *LoadCollectionTask) GetLoadState() *LoadTaskState {
	if m != nil {
		return m.LoadState
	}
	return nil
}

func (m *LoadCollectionTask) GetCollBackup() *CollectionBackupInfo {
	if m != nil {
		return m.CollBackup
	}
	return nil
}

func (m *LoadCollectionTask) GetTargetCollectionName() string {
	if m != nil {
		return m.TargetCollectionName
	}
	return ""
}

func (m *LoadCollectionTask) GetPartitionLoadTasks() []*LoadPartitionTask {
	if m != nil {
		return m.PartitionLoadTasks
	}
	return nil
}

type LoadBackupRequest struct {
	Base            *MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	BackupName      string   `protobuf:"bytes,2,opt,name=backup_name,json=backupName,proto3" json:"backup_name,omitempty"`
	CollectionNames []string `protobuf:"bytes,3,rep,name=collection_names,json=collectionNames,proto3" json:"collection_names,omitempty"`
	// Support two ways to rename the collections while recover
	// 1, set a suffix
	CollectionSuffix string `protobuf:"bytes,4,opt,name=collection_suffix,json=collectionSuffix,proto3" json:"collection_suffix,omitempty"`
	// 2, give a map to rename the collections, if not given, use the original name
	CollectionRenames    map[string]string `protobuf:"bytes,5,rep,name=collection_renames,json=collectionRenames,proto3" json:"collection_renames,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Async                bool              `protobuf:"varint,6,opt,name=async,proto3" json:"async,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *LoadBackupRequest) Reset()         { *m = LoadBackupRequest{} }
func (m *LoadBackupRequest) String() string { return proto.CompactTextString(m) }
func (*LoadBackupRequest) ProtoMessage()    {}
func (*LoadBackupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{20}
}

func (m *LoadBackupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadBackupRequest.Unmarshal(m, b)
}
func (m *LoadBackupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadBackupRequest.Marshal(b, m, deterministic)
}
func (m *LoadBackupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadBackupRequest.Merge(m, src)
}
func (m *LoadBackupRequest) XXX_Size() int {
	return xxx_messageInfo_LoadBackupRequest.Size(m)
}
func (m *LoadBackupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadBackupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoadBackupRequest proto.InternalMessageInfo

func (m *LoadBackupRequest) GetBase() *MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *LoadBackupRequest) GetBackupName() string {
	if m != nil {
		return m.BackupName
	}
	return ""
}

func (m *LoadBackupRequest) GetCollectionNames() []string {
	if m != nil {
		return m.CollectionNames
	}
	return nil
}

func (m *LoadBackupRequest) GetCollectionSuffix() string {
	if m != nil {
		return m.CollectionSuffix
	}
	return ""
}

func (m *LoadBackupRequest) GetCollectionRenames() map[string]string {
	if m != nil {
		return m.CollectionRenames
	}
	return nil
}

func (m *LoadBackupRequest) GetAsync() bool {
	if m != nil {
		return m.Async
	}
	return false
}

type LoadBackupResponse struct {
	Status               *Status               `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	LoadState            *LoadTaskState        `protobuf:"bytes,2,opt,name=load_state,json=loadState,proto3" json:"load_state,omitempty"`
	BackupInfo           *BackupInfo           `protobuf:"bytes,3,opt,name=backup_info,json=backupInfo,proto3" json:"backup_info,omitempty"`
	CollectionLoadTasks  []*LoadCollectionTask `protobuf:"bytes,4,rep,name=collection_load_tasks,json=collectionLoadTasks,proto3" json:"collection_load_tasks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *LoadBackupResponse) Reset()         { *m = LoadBackupResponse{} }
func (m *LoadBackupResponse) String() string { return proto.CompactTextString(m) }
func (*LoadBackupResponse) ProtoMessage()    {}
func (*LoadBackupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{21}
}

func (m *LoadBackupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadBackupResponse.Unmarshal(m, b)
}
func (m *LoadBackupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadBackupResponse.Marshal(b, m, deterministic)
}
func (m *LoadBackupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadBackupResponse.Merge(m, src)
}
func (m *LoadBackupResponse) XXX_Size() int {
	return xxx_messageInfo_LoadBackupResponse.Size(m)
}
func (m *LoadBackupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadBackupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoadBackupResponse proto.InternalMessageInfo

func (m *LoadBackupResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *LoadBackupResponse) GetLoadState() *LoadTaskState {
	if m != nil {
		return m.LoadState
	}
	return nil
}

func (m *LoadBackupResponse) GetBackupInfo() *BackupInfo {
	if m != nil {
		return m.BackupInfo
	}
	return nil
}

func (m *LoadBackupResponse) GetCollectionLoadTasks() []*LoadCollectionTask {
	if m != nil {
		return m.CollectionLoadTasks
	}
	return nil
}

type GetLoadBackupStateRequest struct {
	Base                 *MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLoadBackupStateRequest) Reset()         { *m = GetLoadBackupStateRequest{} }
func (m *GetLoadBackupStateRequest) String() string { return proto.CompactTextString(m) }
func (*GetLoadBackupStateRequest) ProtoMessage()    {}
func (*GetLoadBackupStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{22}
}

func (m *GetLoadBackupStateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLoadBackupStateRequest.Unmarshal(m, b)
}
func (m *GetLoadBackupStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLoadBackupStateRequest.Marshal(b, m, deterministic)
}
func (m *GetLoadBackupStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLoadBackupStateRequest.Merge(m, src)
}
func (m *GetLoadBackupStateRequest) XXX_Size() int {
	return xxx_messageInfo_GetLoadBackupStateRequest.Size(m)
}
func (m *GetLoadBackupStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLoadBackupStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLoadBackupStateRequest proto.InternalMessageInfo

func (m *GetLoadBackupStateRequest) GetBase() *MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *GetLoadBackupStateRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// copied from milvus data_coord.proto
type FieldBinlog struct {
	FieldID              int64     `protobuf:"varint,1,opt,name=fieldID,proto3" json:"fieldID,omitempty"`
	Binlogs              []*Binlog `protobuf:"bytes,2,rep,name=binlogs,proto3" json:"binlogs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *FieldBinlog) Reset()         { *m = FieldBinlog{} }
func (m *FieldBinlog) String() string { return proto.CompactTextString(m) }
func (*FieldBinlog) ProtoMessage()    {}
func (*FieldBinlog) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{23}
}

func (m *FieldBinlog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldBinlog.Unmarshal(m, b)
}
func (m *FieldBinlog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldBinlog.Marshal(b, m, deterministic)
}
func (m *FieldBinlog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldBinlog.Merge(m, src)
}
func (m *FieldBinlog) XXX_Size() int {
	return xxx_messageInfo_FieldBinlog.Size(m)
}
func (m *FieldBinlog) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldBinlog.DiscardUnknown(m)
}

var xxx_messageInfo_FieldBinlog proto.InternalMessageInfo

func (m *FieldBinlog) GetFieldID() int64 {
	if m != nil {
		return m.FieldID
	}
	return 0
}

func (m *FieldBinlog) GetBinlogs() []*Binlog {
	if m != nil {
		return m.Binlogs
	}
	return nil
}

type Binlog struct {
	EntriesNum           int64    `protobuf:"varint,1,opt,name=entries_num,json=entriesNum,proto3" json:"entries_num,omitempty"`
	TimestampFrom        uint64   `protobuf:"varint,2,opt,name=timestamp_from,json=timestampFrom,proto3" json:"timestamp_from,omitempty"`
	TimestampTo          uint64   `protobuf:"varint,3,opt,name=timestamp_to,json=timestampTo,proto3" json:"timestamp_to,omitempty"`
	LogPath              string   `protobuf:"bytes,4,opt,name=log_path,json=logPath,proto3" json:"log_path,omitempty"`
	LogSize              int64    `protobuf:"varint,5,opt,name=log_size,json=logSize,proto3" json:"log_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Binlog) Reset()         { *m = Binlog{} }
func (m *Binlog) String() string { return proto.CompactTextString(m) }
func (*Binlog) ProtoMessage()    {}
func (*Binlog) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{24}
}

func (m *Binlog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Binlog.Unmarshal(m, b)
}
func (m *Binlog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Binlog.Marshal(b, m, deterministic)
}
func (m *Binlog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Binlog.Merge(m, src)
}
func (m *Binlog) XXX_Size() int {
	return xxx_messageInfo_Binlog.Size(m)
}
func (m *Binlog) XXX_DiscardUnknown() {
	xxx_messageInfo_Binlog.DiscardUnknown(m)
}

var xxx_messageInfo_Binlog proto.InternalMessageInfo

func (m *Binlog) GetEntriesNum() int64 {
	if m != nil {
		return m.EntriesNum
	}
	return 0
}

func (m *Binlog) GetTimestampFrom() uint64 {
	if m != nil {
		return m.TimestampFrom
	}
	return 0
}

func (m *Binlog) GetTimestampTo() uint64 {
	if m != nil {
		return m.TimestampTo
	}
	return 0
}

func (m *Binlog) GetLogPath() string {
	if m != nil {
		return m.LogPath
	}
	return ""
}

func (m *Binlog) GetLogSize() int64 {
	if m != nil {
		return m.LogSize
	}
	return 0
}

// copied from milvus common.proto
type KeyValuePair struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyValuePair) Reset()         { *m = KeyValuePair{} }
func (m *KeyValuePair) String() string { return proto.CompactTextString(m) }
func (*KeyValuePair) ProtoMessage()    {}
func (*KeyValuePair) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{25}
}

func (m *KeyValuePair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyValuePair.Unmarshal(m, b)
}
func (m *KeyValuePair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyValuePair.Marshal(b, m, deterministic)
}
func (m *KeyValuePair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyValuePair.Merge(m, src)
}
func (m *KeyValuePair) XXX_Size() int {
	return xxx_messageInfo_KeyValuePair.Size(m)
}
func (m *KeyValuePair) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyValuePair.DiscardUnknown(m)
}

var xxx_messageInfo_KeyValuePair proto.InternalMessageInfo

func (m *KeyValuePair) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KeyValuePair) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

//*
// @brief Field schema
type FieldSchema struct {
	FieldID              int64           `protobuf:"varint,1,opt,name=fieldID,proto3" json:"fieldID,omitempty"`
	Name                 string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsPrimaryKey         bool            `protobuf:"varint,3,opt,name=is_primary_key,json=isPrimaryKey,proto3" json:"is_primary_key,omitempty"`
	Description          string          `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	DataType             DataType        `protobuf:"varint,5,opt,name=data_type,json=dataType,proto3,enum=milvus.proto.backup.DataType" json:"data_type,omitempty"`
	TypeParams           []*KeyValuePair `protobuf:"bytes,6,rep,name=type_params,json=typeParams,proto3" json:"type_params,omitempty"`
	IndexParams          []*KeyValuePair `protobuf:"bytes,7,rep,name=index_params,json=indexParams,proto3" json:"index_params,omitempty"`
	AutoID               bool            `protobuf:"varint,8,opt,name=autoID,proto3" json:"autoID,omitempty"`
	State                FieldState      `protobuf:"varint,9,opt,name=state,proto3,enum=milvus.proto.backup.FieldState" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *FieldSchema) Reset()         { *m = FieldSchema{} }
func (m *FieldSchema) String() string { return proto.CompactTextString(m) }
func (*FieldSchema) ProtoMessage()    {}
func (*FieldSchema) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{26}
}

func (m *FieldSchema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldSchema.Unmarshal(m, b)
}
func (m *FieldSchema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldSchema.Marshal(b, m, deterministic)
}
func (m *FieldSchema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldSchema.Merge(m, src)
}
func (m *FieldSchema) XXX_Size() int {
	return xxx_messageInfo_FieldSchema.Size(m)
}
func (m *FieldSchema) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldSchema.DiscardUnknown(m)
}

var xxx_messageInfo_FieldSchema proto.InternalMessageInfo

func (m *FieldSchema) GetFieldID() int64 {
	if m != nil {
		return m.FieldID
	}
	return 0
}

func (m *FieldSchema) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FieldSchema) GetIsPrimaryKey() bool {
	if m != nil {
		return m.IsPrimaryKey
	}
	return false
}

func (m *FieldSchema) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *FieldSchema) GetDataType() DataType {
	if m != nil {
		return m.DataType
	}
	return DataType_None
}

func (m *FieldSchema) GetTypeParams() []*KeyValuePair {
	if m != nil {
		return m.TypeParams
	}
	return nil
}

func (m *FieldSchema) GetIndexParams() []*KeyValuePair {
	if m != nil {
		return m.IndexParams
	}
	return nil
}

func (m *FieldSchema) GetAutoID() bool {
	if m != nil {
		return m.AutoID
	}
	return false
}

func (m *FieldSchema) GetState() FieldState {
	if m != nil {
		return m.State
	}
	return FieldState_FieldCreated
}

//*
// @brief Collection schema
type CollectionSchema struct {
	Name                 string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string         `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	AutoID               bool           `protobuf:"varint,3,opt,name=autoID,proto3" json:"autoID,omitempty"`
	Fields               []*FieldSchema `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CollectionSchema) Reset()         { *m = CollectionSchema{} }
func (m *CollectionSchema) String() string { return proto.CompactTextString(m) }
func (*CollectionSchema) ProtoMessage()    {}
func (*CollectionSchema) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{27}
}

func (m *CollectionSchema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectionSchema.Unmarshal(m, b)
}
func (m *CollectionSchema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectionSchema.Marshal(b, m, deterministic)
}
func (m *CollectionSchema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectionSchema.Merge(m, src)
}
func (m *CollectionSchema) XXX_Size() int {
	return xxx_messageInfo_CollectionSchema.Size(m)
}
func (m *CollectionSchema) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectionSchema.DiscardUnknown(m)
}

var xxx_messageInfo_CollectionSchema proto.InternalMessageInfo

func (m *CollectionSchema) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CollectionSchema) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CollectionSchema) GetAutoID() bool {
	if m != nil {
		return m.AutoID
	}
	return false
}

func (m *CollectionSchema) GetFields() []*FieldSchema {
	if m != nil {
		return m.Fields
	}
	return nil
}

func init() {
	proto.RegisterEnum("milvus.proto.backup.MsgType", MsgType_name, MsgType_value)
	proto.RegisterEnum("milvus.proto.backup.StatusCode", StatusCode_name, StatusCode_value)
	proto.RegisterEnum("milvus.proto.backup.BackupTaskStateCode", BackupTaskStateCode_name, BackupTaskStateCode_value)
	proto.RegisterEnum("milvus.proto.backup.LoadTaskStateCode", LoadTaskStateCode_name, LoadTaskStateCode_value)
	proto.RegisterEnum("milvus.proto.backup.ConsistencyLevel", ConsistencyLevel_name, ConsistencyLevel_value)
	proto.RegisterEnum("milvus.proto.backup.DataType", DataType_name, DataType_value)
	proto.RegisterEnum("milvus.proto.backup.FieldState", FieldState_name, FieldState_value)
	proto.RegisterType((*MsgBase)(nil), "milvus.proto.backup.MsgBase")
	proto.RegisterType((*Status)(nil), "milvus.proto.backup.Status")
	proto.RegisterType((*CollectionBackupInfo)(nil), "milvus.proto.backup.CollectionBackupInfo")
	proto.RegisterType((*PartitionBackupInfo)(nil), "milvus.proto.backup.PartitionBackupInfo")
	proto.RegisterType((*SegmentBackupInfo)(nil), "milvus.proto.backup.SegmentBackupInfo")
	proto.RegisterType((*BackupInfo)(nil), "milvus.proto.backup.BackupInfo")
	proto.RegisterType((*CollectionLevelBackupInfo)(nil), "milvus.proto.backup.CollectionLevelBackupInfo")
	proto.RegisterType((*PartitionLevelBackupInfo)(nil), "milvus.proto.backup.PartitionLevelBackupInfo")
	proto.RegisterType((*SegmentLevelBackupInfo)(nil), "milvus.proto.backup.SegmentLevelBackupInfo")
	proto.RegisterType((*CreateBackupRequest)(nil), "milvus.proto.backup.CreateBackupRequest")
	proto.RegisterType((*BackupInfoResponse)(nil), "milvus.proto.backup.BackupInfoResponse")
	proto.RegisterType((*GetBackupRequest)(nil), "milvus.proto.backup.GetBackupRequest")
	proto.RegisterType((*ListBackupsRequest)(nil), "milvus.proto.backup.ListBackupsRequest")
	proto.RegisterType((*ListBackupsResponse)(nil), "milvus.proto.backup.ListBackupsResponse")
	proto.RegisterType((*DeleteBackupRequest)(nil), "milvus.proto.backup.DeleteBackupRequest")
	proto.RegisterType((*DeleteBackupResponse)(nil), "milvus.proto.backup.DeleteBackupResponse")
	proto.RegisterType((*BackupTaskState)(nil), "milvus.proto.backup.BackupTaskState")
	proto.RegisterType((*LoadTaskState)(nil), "milvus.proto.backup.LoadTaskState")
	proto.RegisterType((*LoadPartitionTask)(nil), "milvus.proto.backup.LoadPartitionTask")
	proto.RegisterType((*LoadCollectionTask)(nil), "milvus.proto.backup.LoadCollectionTask")
	proto.RegisterType((*LoadBackupRequest)(nil), "milvus.proto.backup.LoadBackupRequest")
	proto.RegisterMapType((map[string]string)(nil), "milvus.proto.backup.LoadBackupRequest.CollectionRenamesEntry")
	proto.RegisterType((*LoadBackupResponse)(nil), "milvus.proto.backup.LoadBackupResponse")
	proto.RegisterType((*GetLoadBackupStateRequest)(nil), "milvus.proto.backup.GetLoadBackupStateRequest")
	proto.RegisterType((*FieldBinlog)(nil), "milvus.proto.backup.FieldBinlog")
	proto.RegisterType((*Binlog)(nil), "milvus.proto.backup.Binlog")
	proto.RegisterType((*KeyValuePair)(nil), "milvus.proto.backup.KeyValuePair")
	proto.RegisterType((*FieldSchema)(nil), "milvus.proto.backup.FieldSchema")
	proto.RegisterType((*CollectionSchema)(nil), "milvus.proto.backup.CollectionSchema")
}

func init() { proto.RegisterFile("backup.proto", fileDescriptor_65240d19de191688) }

var fileDescriptor_65240d19de191688 = []byte{
	// 2089 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x38, 0x5b, 0x6f, 0x1b, 0xc7,
	0xd5, 0x5e, 0x2e, 0x2f, 0xe2, 0xa1, 0x44, 0xad, 0x46, 0x8a, 0x3f, 0x5a, 0x5f, 0x52, 0x2b, 0xdb,
	0x38, 0x96, 0x55, 0x54, 0x6e, 0xed, 0xc4, 0x71, 0x8d, 0x38, 0xad, 0x49, 0xca, 0x06, 0x6b, 0x59,
	0x16, 0x56, 0x17, 0x18, 0x69, 0x53, 0x62, 0xc8, 0x1d, 0x52, 0x0b, 0xed, 0xee, 0xb0, 0x3b, 0x4b,
	0xd9, 0xd4, 0x2f, 0x28, 0xd0, 0x3f, 0x50, 0x14, 0x7d, 0xe9, 0x63, 0xd1, 0x97, 0x02, 0xfd, 0x2d,
	0x2d, 0xd0, 0x3f, 0xd1, 0xc7, 0x3e, 0xf4, 0xa9, 0x98, 0xcb, 0xde, 0xa8, 0xa5, 0x45, 0x39, 0x31,
	0x90, 0xb7, 0x9d, 0xb3, 0xe7, 0x7e, 0xce, 0x9c, 0xcb, 0xc0, 0x62, 0x0f, 0xf7, 0x4f, 0xc7, 0xa3,
	0xed, 0x51, 0x40, 0x43, 0x8a, 0x56, 0x3d, 0xc7, 0x3d, 0x1b, 0x33, 0x79, 0xda, 0x96, 0xbf, 0xcc,
	0x33, 0xa8, 0xbc, 0x60, 0xc3, 0x26, 0x66, 0x04, 0x7d, 0x01, 0x0b, 0x1e, 0x1b, 0x76, 0xc3, 0xc9,
	0x88, 0x34, 0xb4, 0x0d, 0x6d, 0xb3, 0x7e, 0xef, 0xc3, 0xed, 0x1c, 0x92, 0xed, 0x17, 0x6c, 0x78,
	0x38, 0x19, 0x11, 0xab, 0xe2, 0xc9, 0x0f, 0xb4, 0x06, 0x25, 0x8f, 0x0d, 0x3b, 0xed, 0x46, 0x61,
	0x43, 0xdb, 0xd4, 0x2d, 0x79, 0x40, 0x1f, 0x42, 0x35, 0x74, 0x3c, 0xc2, 0x42, 0xec, 0x8d, 0x1a,
	0xfa, 0x86, 0xb6, 0x59, 0xb4, 0x12, 0x80, 0xd9, 0x83, 0xf2, 0x41, 0x88, 0xc3, 0x31, 0x43, 0xbf,
	0x80, 0x1a, 0x13, 0x5f, 0xdd, 0x3e, 0xb5, 0x23, 0xc9, 0x37, 0x73, 0x25, 0x4b, 0x8a, 0x16, 0xb5,
	0x89, 0x05, 0x2c, 0xfe, 0x46, 0xd7, 0xa1, 0x1c, 0x10, 0xcc, 0xa8, 0x2f, 0x14, 0xa8, 0x5a, 0xea,
	0x64, 0xfe, 0x57, 0x87, 0xb5, 0x16, 0x75, 0x5d, 0xd2, 0x0f, 0x1d, 0xea, 0x37, 0x05, 0x8f, 0x8e,
	0x3f, 0xa0, 0xe8, 0x59, 0xe4, 0x99, 0x2e, 0xe7, 0x22, 0x65, 0xd6, 0xee, 0x7d, 0x92, 0x2b, 0x53,
	0x92, 0x1d, 0x62, 0x76, 0xca, 0xa5, 0x13, 0xab, 0x26, 0xe1, 0xe2, 0x80, 0x7e, 0x08, 0x4b, 0xfd,
	0x58, 0x40, 0xd7, 0xb1, 0x95, 0x07, 0x16, 0x13, 0x60, 0xc7, 0x46, 0xff, 0x07, 0x15, 0xbb, 0xd7,
	0xf5, 0xb1, 0x47, 0x84, 0x1b, 0xaa, 0x56, 0xd9, 0xee, 0xed, 0x61, 0x8f, 0xa0, 0xdb, 0xb0, 0x9c,
	0xa2, 0x16, 0x08, 0x45, 0x81, 0x50, 0x4f, 0xc0, 0x02, 0xf1, 0x31, 0x94, 0x59, 0xff, 0x84, 0x78,
	0xb8, 0x51, 0x12, 0x9a, 0xde, 0xca, 0xd5, 0x34, 0x31, 0xf5, 0x40, 0x20, 0x5b, 0x8a, 0x08, 0x7d,
	0x04, 0xc0, 0x4e, 0x70, 0x60, 0xb3, 0xae, 0x3f, 0xf6, 0x1a, 0xe5, 0x0d, 0x6d, 0xb3, 0x64, 0x55,
	0x25, 0x64, 0x6f, 0xec, 0x21, 0x0b, 0x56, 0xfa, 0xd4, 0x67, 0x0e, 0x0b, 0x89, 0xdf, 0x9f, 0x74,
	0x5d, 0x72, 0x46, 0xdc, 0x46, 0x45, 0x84, 0x61, 0x96, 0xa0, 0x18, 0x7b, 0x97, 0x23, 0x5b, 0x46,
	0x7f, 0x0a, 0x82, 0x8e, 0x60, 0x65, 0x84, 0x83, 0xd0, 0x11, 0x96, 0x49, 0x32, 0xd6, 0x58, 0xd8,
	0xd0, 0x37, 0x6b, 0xf7, 0x36, 0x73, 0x79, 0xee, 0x47, 0xd8, 0x49, 0x98, 0x2c, 0x63, 0x94, 0x05,
	0x32, 0x74, 0x07, 0x0c, 0x15, 0xb8, 0x24, 0xb5, 0xaa, 0x22, 0xb5, 0x96, 0x25, 0xfc, 0x30, 0x4e,
	0xb0, 0x7f, 0x68, 0xb0, 0x9a, 0xc3, 0x14, 0x7d, 0x0c, 0x8b, 0x89, 0x66, 0x8e, 0x2d, 0x62, 0xaf,
	0x5b, 0xb5, 0x18, 0xd6, 0xb1, 0xd1, 0x2d, 0xa8, 0x27, 0x28, 0x22, 0x2c, 0x32, 0xaf, 0x96, 0x62,
	0xa8, 0x88, 0xca, 0x85, 0xe0, 0xeb, 0x39, 0xc1, 0x7f, 0x09, 0xcb, 0x8c, 0x0c, 0x3d, 0xe2, 0x87,
	0xb1, 0x1b, 0x2a, 0xc2, 0x0d, 0x9f, 0xe6, 0x67, 0xb8, 0xc4, 0x4d, 0x39, 0xa1, 0xce, 0xd2, 0x20,
	0x66, 0xfe, 0xb3, 0x00, 0x2b, 0x17, 0xb0, 0x44, 0x88, 0x95, 0x98, 0xd8, 0xa6, 0xaa, 0x82, 0x74,
	0xec, 0xf9, 0xf2, 0x74, 0xda, 0x33, 0xfa, 0x45, 0xcf, 0xfc, 0x00, 0x6a, 0xfe, 0xd8, 0xeb, 0xd2,
	0x41, 0x37, 0xa0, 0xaf, 0x99, 0xc8, 0x56, 0xdd, 0xaa, 0xfa, 0x63, 0xef, 0xe5, 0xc0, 0xa2, 0xaf,
	0x19, 0x7a, 0x04, 0x95, 0x9e, 0xe3, 0xbb, 0x74, 0xc8, 0x1a, 0x25, 0x61, 0xe5, 0x46, 0xae, 0x95,
	0x4f, 0x1d, 0xe2, 0xda, 0x4d, 0x81, 0x68, 0x45, 0x04, 0xe8, 0x2b, 0xa8, 0xf2, 0xdb, 0xc8, 0x04,
	0x75, 0x79, 0x4e, 0xea, 0x84, 0x84, 0xd3, 0xdb, 0xc4, 0x0d, 0xb1, 0xa0, 0xaf, 0xcc, 0x4b, 0x1f,
	0x93, 0x98, 0xff, 0xd6, 0x00, 0xde, 0x47, 0x8d, 0x40, 0x50, 0x4c, 0xe5, 0x90, 0xf8, 0xce, 0xcd,
	0x63, 0x3d, 0x37, 0x8f, 0xd1, 0x2b, 0x40, 0xa9, 0xd0, 0x45, 0x39, 0x54, 0x14, 0xf6, 0xdd, 0xb9,
	0xa4, 0x0e, 0xa4, 0xd2, 0x68, 0xa5, 0x3f, 0x05, 0x65, 0xe6, 0xaf, 0xe1, 0x46, 0x82, 0x2a, 0xae,
	0x6d, 0xca, 0xfc, 0x9f, 0x43, 0xc9, 0xf1, 0x07, 0x94, 0x35, 0xb4, 0xab, 0x4a, 0x92, 0x74, 0xe6,
	0xd7, 0xd0, 0x88, 0xaf, 0xdf, 0x34, 0xf3, 0xaf, 0xb2, 0xcc, 0xe7, 0xaf, 0x08, 0x8a, 0xf7, 0x31,
	0x5c, 0x57, 0x57, 0x60, 0x9a, 0xf3, 0x97, 0x59, 0xce, 0xf3, 0x5e, 0x32, 0xc5, 0xf7, 0x2f, 0x1a,
	0xac, 0xb6, 0x02, 0x82, 0x43, 0x22, 0xff, 0x59, 0xe4, 0xb7, 0x63, 0xc2, 0x42, 0xf4, 0x13, 0x28,
	0xf6, 0x30, 0x8b, 0x72, 0x60, 0x66, 0x57, 0xe4, 0x5d, 0xd4, 0x12, 0x98, 0xe8, 0x26, 0xa8, 0x1c,
	0x48, 0xd7, 0x0f, 0x90, 0xa0, 0x3d, 0x95, 0x01, 0x53, 0xb5, 0x9f, 0x35, 0xf4, 0x0d, 0x7d, 0xb3,
	0x6a, 0x2d, 0x67, 0x8b, 0x3f, 0xe3, 0xed, 0x15, 0xb3, 0x89, 0xdf, 0x17, 0xd7, 0x6d, 0xc1, 0x92,
	0x07, 0xf3, 0xf7, 0x1a, 0xa0, 0x94, 0x05, 0x84, 0x8d, 0xa8, 0xcf, 0x08, 0xba, 0x0f, 0x65, 0xd9,
	0x19, 0x95, 0xb2, 0xff, 0xff, 0x96, 0x46, 0x6a, 0x29, 0x54, 0xde, 0x82, 0x95, 0xb6, 0xdc, 0x0f,
	0x42, 0xdb, 0xda, 0x8c, 0x16, 0x9c, 0x12, 0xa9, 0xcc, 0xe1, 0xdf, 0x26, 0x01, 0xe3, 0x19, 0x09,
	0xdf, 0xb7, 0xd7, 0x4c, 0x0a, 0x68, 0xd7, 0x61, 0x51, 0x2d, 0x7c, 0x77, 0x41, 0x39, 0x9d, 0xb7,
	0x90, 0xd7, 0x79, 0xcd, 0xbf, 0x69, 0xb0, 0x9a, 0x91, 0xf8, 0x6d, 0xdc, 0xdc, 0x8c, 0x4b, 0x8a,
	0xcc, 0xd1, 0x82, 0xc8, 0xd1, 0x4b, 0xfd, 0x5c, 0x4b, 0xfc, 0xcc, 0xd0, 0x06, 0xd4, 0x06, 0xd8,
	0x51, 0x29, 0x1f, 0xa5, 0x4c, 0x1a, 0x64, 0x9e, 0xc0, 0x6a, 0x9b, 0xb8, 0xe4, 0xfd, 0xe7, 0xb0,
	0xf9, 0x1c, 0xd6, 0xb2, 0x92, 0xbe, 0x85, 0x73, 0xcc, 0x7f, 0x69, 0xb0, 0x3c, 0x55, 0x47, 0x51,
	0x1d, 0x0a, 0x71, 0x37, 0x2b, 0x38, 0x36, 0xfa, 0x12, 0x8a, 0x62, 0x46, 0x2c, 0x88, 0xe1, 0x64,
	0x73, 0x9e, 0x5a, 0x2c, 0x86, 0x45, 0x41, 0x85, 0x4c, 0x58, 0x24, 0x41, 0x40, 0x83, 0x17, 0x84,
	0x31, 0x3c, 0x8c, 0x86, 0xb1, 0x0c, 0x4c, 0xf4, 0xd1, 0x10, 0x07, 0xa1, 0xa8, 0xcb, 0x51, 0x7f,
	0x13, 0x10, 0x5e, 0x91, 0xd1, 0x0d, 0x58, 0x20, 0xbe, 0x2d, 0x7f, 0x96, 0xc4, 0xcf, 0x0a, 0xf1,
	0x6d, 0xf1, 0x6b, 0x1d, 0x16, 0x46, 0x01, 0x1d, 0x06, 0x84, 0x31, 0x35, 0x62, 0xc5, 0x67, 0x3e,
	0x8b, 0x2c, 0xed, 0x52, 0x6c, 0xcf, 0xb6, 0xec, 0x51, 0xc6, 0xb2, 0xfc, 0xb2, 0x95, 0xe1, 0xf0,
	0xbd, 0xb0, 0xeb, 0xcf, 0x1a, 0xac, 0x70, 0xad, 0xe2, 0x52, 0xcd, 0xd5, 0x43, 0x4f, 0x00, 0x5c,
	0x8a, 0xed, 0x4c, 0xdf, 0x34, 0x2f, 0xb7, 0xc8, 0xaa, 0x72, 0x2a, 0xe9, 0x9e, 0x0e, 0x88, 0xb1,
	0x43, 0xb5, 0x3b, 0x55, 0x90, 0xe6, 0x6f, 0x13, 0xc0, 0x89, 0xe5, 0xd9, 0xfc, 0x7b, 0x01, 0x10,
	0x97, 0x93, 0xf4, 0xaa, 0xef, 0x4a, 0xc9, 0x5f, 0x42, 0x8d, 0x57, 0x8b, 0xac, 0x92, 0x57, 0x68,
	0x94, 0xc0, 0xa9, 0xe5, 0x19, 0x7d, 0x06, 0xd7, 0x43, 0x1c, 0x0c, 0x49, 0xd8, 0x9d, 0xae, 0x4b,
	0x32, 0x9a, 0x6b, 0xf2, 0x6f, 0x2b, 0xbb, 0x17, 0xbc, 0x82, 0xb5, 0x64, 0x62, 0x13, 0xe6, 0x84,
	0x98, 0x9d, 0x46, 0xd3, 0xc1, 0xec, 0x2c, 0xca, 0xc4, 0xcb, 0x42, 0x31, 0x8f, 0xc8, 0x54, 0x66,
	0xfe, 0x4e, 0x97, 0x91, 0xfd, 0x3e, 0xf5, 0xc1, 0x1f, 0x41, 0x6a, 0x88, 0xe9, 0xb2, 0xf1, 0x60,
	0xe0, 0xbc, 0x51, 0x0b, 0x53, 0x8a, 0xc7, 0x81, 0x80, 0x23, 0x37, 0x33, 0x36, 0x05, 0x44, 0x72,
	0x96, 0x43, 0xe9, 0xe3, 0x99, 0x8e, 0xc9, 0x98, 0x9b, 0x8a, 0x9a, 0x25, 0xe9, 0x77, 0xfc, 0x30,
	0x98, 0xa4, 0x47, 0x29, 0x05, 0x4f, 0x5a, 0x74, 0x39, 0xd5, 0xa2, 0xd7, 0xdb, 0x70, 0x3d, 0x9f,
	0x05, 0x32, 0x40, 0x3f, 0x25, 0x13, 0xe1, 0xc7, 0xaa, 0xc5, 0x3f, 0x39, 0x87, 0x33, 0xec, 0x8e,
	0x23, 0x17, 0xc9, 0xc3, 0xa3, 0xc2, 0x43, 0xcd, 0xfc, 0xab, 0x4a, 0xe0, 0xef, 0xa0, 0xc8, 0x4e,
	0x65, 0x7d, 0xe1, 0x5d, 0xb2, 0x7e, 0x6a, 0x56, 0xd0, 0xaf, 0x3c, 0x2b, 0xa0, 0x5f, 0xc1, 0x07,
	0xa9, 0xd0, 0x5c, 0x48, 0xdb, 0xdb, 0x33, 0xf5, 0xc9, 0x5e, 0x61, 0x6b, 0x35, 0xe1, 0x92, 0x24,
	0xee, 0x37, 0x70, 0xe3, 0x19, 0x09, 0x13, 0x7f, 0x49, 0xfd, 0xdf, 0x39, 0x7f, 0x65, 0x9d, 0x2e,
	0x44, 0x75, 0xda, 0xfc, 0x0d, 0xd4, 0x52, 0xeb, 0x03, 0x6a, 0x40, 0x65, 0xc0, 0x8f, 0x9d, 0xb6,
	0xaa, 0xe5, 0xd1, 0x11, 0x7d, 0x9e, 0x6c, 0x42, 0xb2, 0xcd, 0xe7, 0xc7, 0x67, 0x6a, 0x09, 0xe2,
	0x13, 0x68, 0x59, 0xf1, 0xbe, 0x09, 0x35, 0xe2, 0x87, 0x81, 0x43, 0xe4, 0xda, 0x2e, 0xf9, 0x83,
	0x02, 0xf1, 0xbd, 0xfd, 0x16, 0xd4, 0xe3, 0xed, 0xa1, 0x3b, 0x08, 0xa8, 0x27, 0xf4, 0x2c, 0x5a,
	0x4b, 0x31, 0xf4, 0x69, 0x40, 0x3d, 0xbe, 0xd6, 0x25, 0x68, 0x21, 0x55, 0x7b, 0x46, 0x2d, 0x86,
	0x1d, 0x52, 0x5e, 0xfe, 0x5d, 0x3a, 0xec, 0x8e, 0x70, 0x78, 0xa2, 0x2e, 0x54, 0xc5, 0xa5, 0xc3,
	0x7d, 0x1c, 0x9e, 0x44, 0xbf, 0x98, 0x73, 0x1e, 0x77, 0x06, 0x97, 0x0e, 0x0f, 0x9c, 0x73, 0x62,
	0x3e, 0x80, 0xc5, 0xe7, 0x64, 0x72, 0xcc, 0x13, 0x75, 0x1f, 0x3b, 0xc1, 0xbc, 0x49, 0x6d, 0xfe,
	0x41, 0x57, 0x4e, 0x94, 0xcf, 0x14, 0x6f, 0x71, 0x62, 0xde, 0xea, 0xf4, 0x09, 0xd4, 0x1d, 0xd6,
	0x1d, 0x05, 0x8e, 0x87, 0x83, 0x49, 0x97, 0x0b, 0xd4, 0xc5, 0x9d, 0x5b, 0x74, 0xd8, 0xbe, 0x04,
	0x3e, 0x27, 0x13, 0x3e, 0x26, 0xd9, 0x84, 0xf5, 0x03, 0x67, 0xc4, 0xd3, 0x43, 0x19, 0x95, 0x06,
	0xa1, 0x47, 0x50, 0xb5, 0x71, 0x88, 0xe5, 0x73, 0x57, 0x49, 0xb4, 0xdd, 0x8f, 0x72, 0x43, 0xd4,
	0xc6, 0x21, 0x16, 0xef, 0x5d, 0x0b, 0xb6, 0xfa, 0x42, 0x4d, 0xa8, 0x71, 0xb2, 0xee, 0x08, 0x07,
	0xd8, 0x8b, 0x96, 0xd5, 0x8f, 0x73, 0xa9, 0xd3, 0x1e, 0xb2, 0x80, 0x53, 0xed, 0x0b, 0x22, 0xd4,
	0x86, 0x45, 0xc7, 0xb7, 0xc9, 0x9b, 0x88, 0x49, 0x65, 0x5e, 0x26, 0x35, 0x41, 0xa6, 0xb8, 0x5c,
	0x87, 0x32, 0x1e, 0x87, 0xb4, 0xd3, 0x6e, 0x2c, 0x08, 0x2f, 0xa8, 0x13, 0xfa, 0x1c, 0x4a, 0xf2,
	0x8e, 0x57, 0xdf, 0xf2, 0x9c, 0x26, 0x83, 0x20, 0x2e, 0x88, 0xc4, 0x36, 0xff, 0xa8, 0x81, 0x31,
	0xfd, 0x8c, 0x14, 0x47, 0x41, 0x4b, 0x45, 0x61, 0xca, 0xbf, 0x85, 0x8b, 0xfe, 0x4d, 0x34, 0xd3,
	0x33, 0x9a, 0x3d, 0x84, 0xb2, 0x08, 0x6f, 0x74, 0xdd, 0xdf, 0xb2, 0xa3, 0x47, 0xcf, 0x58, 0x12,
	0x7f, 0xcb, 0x15, 0x4f, 0x95, 0x22, 0x00, 0x4b, 0x50, 0x3d, 0xf2, 0x6d, 0x32, 0x70, 0x7c, 0x62,
	0x1b, 0xd7, 0x90, 0x01, 0x8b, 0xe9, 0xb5, 0xcd, 0xb0, 0x39, 0x42, 0xbc, 0x8f, 0x18, 0x04, 0x2d,
	0x43, 0x2d, 0x35, 0xc5, 0x1b, 0x03, 0x4e, 0x91, 0x1e, 0x5d, 0x8d, 0x21, 0xaa, 0x03, 0x24, 0x55,
	0xc3, 0x38, 0xd9, 0x7a, 0x0c, 0x90, 0x3c, 0x37, 0xa2, 0x1a, 0x54, 0x8e, 0xfc, 0x53, 0x9f, 0xbe,
	0xf6, 0x8d, 0x6b, 0xfc, 0x70, 0x30, 0xee, 0xf7, 0x09, 0x63, 0x86, 0x86, 0x16, 0xa0, 0xf8, 0x14,
	0x3b, 0xae, 0x51, 0xe0, 0x60, 0x3e, 0x31, 0xd1, 0x71, 0x68, 0xe8, 0x5b, 0x6f, 0x60, 0x35, 0x67,
	0x12, 0x45, 0x08, 0xea, 0xcd, 0x27, 0xad, 0xe7, 0x47, 0xfb, 0xdd, 0xce, 0x5e, 0xe7, 0xb0, 0xf3,
	0x64, 0xd7, 0xb8, 0x86, 0xd6, 0xc0, 0x50, 0xb0, 0x9d, 0x57, 0x3b, 0xad, 0xa3, 0xc3, 0xce, 0xde,
	0x33, 0x43, 0x4b, 0x61, 0x1e, 0x1c, 0xb5, 0x5a, 0x3b, 0x07, 0x07, 0x46, 0x81, 0x9b, 0xa1, 0x60,
	0x4f, 0x9f, 0x74, 0x76, 0x0d, 0x3d, 0x85, 0x74, 0xd8, 0x79, 0xb1, 0xf3, 0xf2, 0xe8, 0xd0, 0x28,
	0x6e, 0xb9, 0xb2, 0x73, 0x67, 0xe5, 0x1a, 0xb0, 0xb8, 0xfb, 0xf2, 0x49, 0x3b, 0x25, 0x15, 0x41,
	0x5d, 0x40, 0xd2, 0x32, 0x23, 0xac, 0x44, 0xe2, 0x12, 0x54, 0x05, 0x44, 0xc9, 0x8b, 0x10, 0x12,
	0x69, 0xaf, 0x78, 0xc2, 0x4c, 0x3d, 0xfe, 0x01, 0x94, 0x0f, 0xc2, 0x80, 0xfa, 0x43, 0xe5, 0x2b,
	0xc2, 0x98, 0x43, 0x7d, 0x43, 0xe3, 0x87, 0x26, 0x1d, 0xfb, 0x36, 0xb1, 0x8d, 0x02, 0x77, 0xf8,
	0xce, 0x19, 0xf1, 0xc3, 0x31, 0x76, 0xdd, 0x89, 0xa1, 0xf3, 0x73, 0x6b, 0xcc, 0x42, 0xea, 0x39,
	0xe7, 0xc4, 0x36, 0x8a, 0x5b, 0x7f, 0xd2, 0x60, 0x21, 0xba, 0x7b, 0xdc, 0xcb, 0x7b, 0xd4, 0x27,
	0xc6, 0x35, 0xfe, 0xd5, 0xa4, 0xd4, 0x95, 0x9e, 0xef, 0xf8, 0xe1, 0x43, 0xa3, 0x80, 0xaa, 0x50,
	0xea, 0xf8, 0xe1, 0x4f, 0x1f, 0x18, 0xba, 0xfa, 0xbc, 0x7f, 0xcf, 0x28, 0xaa, 0xcf, 0x07, 0x9f,
	0x19, 0x25, 0xfe, 0xf9, 0xd4, 0xa5, 0x38, 0x34, 0x80, 0x2b, 0xd7, 0xa6, 0xe3, 0x9e, 0x4b, 0x8c,
	0x9a, 0x52, 0xd4, 0xf1, 0x87, 0xc6, 0x1a, 0xd7, 0xed, 0x18, 0x07, 0xad, 0x13, 0x1c, 0x18, 0x1f,
	0x70, 0x3b, 0x9b, 0x8e, 0x8f, 0x83, 0xc9, 0x31, 0xe9, 0x87, 0x34, 0x30, 0x6c, 0xee, 0x7a, 0xc1,
	0x41, 0x01, 0xc8, 0xd6, 0x31, 0x40, 0x72, 0x7f, 0x38, 0x81, 0x38, 0xc9, 0x34, 0xe4, 0x39, 0xb9,
	0x02, 0x4b, 0x09, 0x84, 0x8b, 0xd0, 0x62, 0x50, 0x3b, 0xa0, 0xa3, 0x11, 0x07, 0x15, 0x62, 0x3a,
	0x01, 0x22, 0xb6, 0xa1, 0xdf, 0xfb, 0x4f, 0x11, 0x56, 0x5f, 0x88, 0x1b, 0xa1, 0x1a, 0x18, 0x09,
	0xce, 0x9c, 0x3e, 0x41, 0xfd, 0x6c, 0x8e, 0xa3, 0xfc, 0x69, 0x38, 0xe7, 0xf5, 0x62, 0xfd, 0xf6,
	0x65, 0xcd, 0x59, 0x8d, 0x14, 0xe6, 0x35, 0xf4, 0x4d, 0xea, 0xda, 0xa0, 0xfc, 0xc7, 0xdf, 0xe9,
	0x35, 0xff, 0x2a, 0xec, 0x7b, 0x99, 0x6b, 0x88, 0x66, 0x74, 0xfa, 0x0b, 0x0b, 0xfe, 0xfa, 0xe6,
	0xe5, 0x88, 0xb1, 0x0c, 0x92, 0xbd, 0xd9, 0x33, 0xfc, 0x94, 0xb3, 0x21, 0xaf, 0xdf, 0x99, 0x03,
	0x33, 0x16, 0xd3, 0x4d, 0x97, 0x0b, 0xf4, 0xe9, 0x7c, 0x13, 0xe5, 0xfa, 0xed, 0x4b, 0xf1, 0x62,
	0x01, 0x14, 0xd0, 0xc5, 0x41, 0x06, 0x6d, 0xcf, 0x8a, 0x49, 0xfe, 0xc4, 0x73, 0x05, 0x81, 0xcd,
	0x9f, 0x7d, 0xfd, 0xc5, 0xd0, 0x09, 0x4f, 0xc6, 0xbd, 0xed, 0x3e, 0xf5, 0xee, 0x9e, 0x3b, 0xae,
	0xeb, 0x9c, 0x87, 0xa4, 0x7f, 0x72, 0x57, 0x72, 0xf8, 0xb1, 0xa4, 0xbd, 0xdb, 0xa7, 0x01, 0xb9,
	0x2b, 0xb8, 0xdd, 0x95, 0x90, 0x51, 0xaf, 0x57, 0x16, 0xe7, 0xfb, 0xff, 0x0b, 0x00, 0x00, 0xff,
	0xff, 0x5a, 0x30, 0x72, 0x7f, 0x70, 0x1a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MilvusBackupServiceClient is the client API for MilvusBackupService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MilvusBackupServiceClient interface {
	// Create backup
	CreateBackup(ctx context.Context, in *CreateBackupRequest, opts ...grpc.CallOption) (*BackupInfoResponse, error)
	// Get backup with the chosen name
	GetBackup(ctx context.Context, in *GetBackupRequest, opts ...grpc.CallOption) (*BackupInfoResponse, error)
	// List backups that contains the given collection name, if collection is not given, return all backups in the cluster
	ListBackups(ctx context.Context, in *ListBackupsRequest, opts ...grpc.CallOption) (*ListBackupsResponse, error)
	// Delete backup by given backup name
	DeleteBackup(ctx context.Context, in *DeleteBackupRequest, opts ...grpc.CallOption) (*DeleteBackupResponse, error)
	// Load backup to milvus, return backup load report
	LoadBackup(ctx context.Context, in *LoadBackupRequest, opts ...grpc.CallOption) (*LoadBackupResponse, error)
	GetLoadBackupState(ctx context.Context, in *GetLoadBackupStateRequest, opts ...grpc.CallOption) (*LoadBackupResponse, error)
}

type milvusBackupServiceClient struct {
	cc *grpc.ClientConn
}

func NewMilvusBackupServiceClient(cc *grpc.ClientConn) MilvusBackupServiceClient {
	return &milvusBackupServiceClient{cc}
}

func (c *milvusBackupServiceClient) CreateBackup(ctx context.Context, in *CreateBackupRequest, opts ...grpc.CallOption) (*BackupInfoResponse, error) {
	out := new(BackupInfoResponse)
	err := c.cc.Invoke(ctx, "/milvus.proto.backup.MilvusBackupService/CreateBackup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *milvusBackupServiceClient) GetBackup(ctx context.Context, in *GetBackupRequest, opts ...grpc.CallOption) (*BackupInfoResponse, error) {
	out := new(BackupInfoResponse)
	err := c.cc.Invoke(ctx, "/milvus.proto.backup.MilvusBackupService/GetBackup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *milvusBackupServiceClient) ListBackups(ctx context.Context, in *ListBackupsRequest, opts ...grpc.CallOption) (*ListBackupsResponse, error) {
	out := new(ListBackupsResponse)
	err := c.cc.Invoke(ctx, "/milvus.proto.backup.MilvusBackupService/ListBackups", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *milvusBackupServiceClient) DeleteBackup(ctx context.Context, in *DeleteBackupRequest, opts ...grpc.CallOption) (*DeleteBackupResponse, error) {
	out := new(DeleteBackupResponse)
	err := c.cc.Invoke(ctx, "/milvus.proto.backup.MilvusBackupService/DeleteBackup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *milvusBackupServiceClient) LoadBackup(ctx context.Context, in *LoadBackupRequest, opts ...grpc.CallOption) (*LoadBackupResponse, error) {
	out := new(LoadBackupResponse)
	err := c.cc.Invoke(ctx, "/milvus.proto.backup.MilvusBackupService/LoadBackup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *milvusBackupServiceClient) GetLoadBackupState(ctx context.Context, in *GetLoadBackupStateRequest, opts ...grpc.CallOption) (*LoadBackupResponse, error) {
	out := new(LoadBackupResponse)
	err := c.cc.Invoke(ctx, "/milvus.proto.backup.MilvusBackupService/GetLoadBackupState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MilvusBackupServiceServer is the server API for MilvusBackupService service.
type MilvusBackupServiceServer interface {
	// Create backup
	CreateBackup(context.Context, *CreateBackupRequest) (*BackupInfoResponse, error)
	// Get backup with the chosen name
	GetBackup(context.Context, *GetBackupRequest) (*BackupInfoResponse, error)
	// List backups that contains the given collection name, if collection is not given, return all backups in the cluster
	ListBackups(context.Context, *ListBackupsRequest) (*ListBackupsResponse, error)
	// Delete backup by given backup name
	DeleteBackup(context.Context, *DeleteBackupRequest) (*DeleteBackupResponse, error)
	// Load backup to milvus, return backup load report
	LoadBackup(context.Context, *LoadBackupRequest) (*LoadBackupResponse, error)
	GetLoadBackupState(context.Context, *GetLoadBackupStateRequest) (*LoadBackupResponse, error)
}

// UnimplementedMilvusBackupServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMilvusBackupServiceServer struct {
}

func (*UnimplementedMilvusBackupServiceServer) CreateBackup(ctx context.Context, req *CreateBackupRequest) (*BackupInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBackup not implemented")
}
func (*UnimplementedMilvusBackupServiceServer) GetBackup(ctx context.Context, req *GetBackupRequest) (*BackupInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBackup not implemented")
}
func (*UnimplementedMilvusBackupServiceServer) ListBackups(ctx context.Context, req *ListBackupsRequest) (*ListBackupsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBackups not implemented")
}
func (*UnimplementedMilvusBackupServiceServer) DeleteBackup(ctx context.Context, req *DeleteBackupRequest) (*DeleteBackupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBackup not implemented")
}
func (*UnimplementedMilvusBackupServiceServer) LoadBackup(ctx context.Context, req *LoadBackupRequest) (*LoadBackupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadBackup not implemented")
}
func (*UnimplementedMilvusBackupServiceServer) GetLoadBackupState(ctx context.Context, req *GetLoadBackupStateRequest) (*LoadBackupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLoadBackupState not implemented")
}

func RegisterMilvusBackupServiceServer(s *grpc.Server, srv MilvusBackupServiceServer) {
	s.RegisterService(&_MilvusBackupService_serviceDesc, srv)
}

func _MilvusBackupService_CreateBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MilvusBackupServiceServer).CreateBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.proto.backup.MilvusBackupService/CreateBackup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MilvusBackupServiceServer).CreateBackup(ctx, req.(*CreateBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MilvusBackupService_GetBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MilvusBackupServiceServer).GetBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.proto.backup.MilvusBackupService/GetBackup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MilvusBackupServiceServer).GetBackup(ctx, req.(*GetBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MilvusBackupService_ListBackups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBackupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MilvusBackupServiceServer).ListBackups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.proto.backup.MilvusBackupService/ListBackups",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MilvusBackupServiceServer).ListBackups(ctx, req.(*ListBackupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MilvusBackupService_DeleteBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MilvusBackupServiceServer).DeleteBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.proto.backup.MilvusBackupService/DeleteBackup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MilvusBackupServiceServer).DeleteBackup(ctx, req.(*DeleteBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MilvusBackupService_LoadBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MilvusBackupServiceServer).LoadBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.proto.backup.MilvusBackupService/LoadBackup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MilvusBackupServiceServer).LoadBackup(ctx, req.(*LoadBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MilvusBackupService_GetLoadBackupState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLoadBackupStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MilvusBackupServiceServer).GetLoadBackupState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.proto.backup.MilvusBackupService/GetLoadBackupState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MilvusBackupServiceServer).GetLoadBackupState(ctx, req.(*GetLoadBackupStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MilvusBackupService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "milvus.proto.backup.MilvusBackupService",
	HandlerType: (*MilvusBackupServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBackup",
			Handler:    _MilvusBackupService_CreateBackup_Handler,
		},
		{
			MethodName: "GetBackup",
			Handler:    _MilvusBackupService_GetBackup_Handler,
		},
		{
			MethodName: "ListBackups",
			Handler:    _MilvusBackupService_ListBackups_Handler,
		},
		{
			MethodName: "DeleteBackup",
			Handler:    _MilvusBackupService_DeleteBackup_Handler,
		},
		{
			MethodName: "LoadBackup",
			Handler:    _MilvusBackupService_LoadBackup_Handler,
		},
		{
			MethodName: "GetLoadBackupState",
			Handler:    _MilvusBackupService_GetLoadBackupState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backup.proto",
}
