// Code generated by protoc-gen-go. DO NOT EDIT.
// source: backup.proto

package backuppb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	commonpb "github.com/zilliztech/milvus-backup/internal/proto/commonpb"
	datapb "github.com/zilliztech/milvus-backup/internal/proto/datapb"
	schemapb "github.com/zilliztech/milvus-backup/internal/proto/schemapb"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MsgType int32

const (
	MsgType_Undefined    MsgType = 0
	MsgType_CreateBackup MsgType = 100
	MsgType_GetBackup    MsgType = 101
	MsgType_ListBackups  MsgType = 102
	MsgType_DeleteBackup MsgType = 103
	MsgType_LoadBackup   MsgType = 104
)

var MsgType_name = map[int32]string{
	0:   "Undefined",
	100: "CreateBackup",
	101: "GetBackup",
	102: "ListBackups",
	103: "DeleteBackup",
	104: "LoadBackup",
}

var MsgType_value = map[string]int32{
	"Undefined":    0,
	"CreateBackup": 100,
	"GetBackup":    101,
	"ListBackups":  102,
	"DeleteBackup": 103,
	"LoadBackup":   104,
}

func (x MsgType) String() string {
	return proto.EnumName(MsgType_name, int32(x))
}

func (MsgType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{0}
}

type StatusCode int32

const (
	StatusCode_Success          StatusCode = 0
	StatusCode_UnexpectedError  StatusCode = 1
	StatusCode_ConnectFailed    StatusCode = 2
	StatusCode_PermissionDenied StatusCode = 3
)

var StatusCode_name = map[int32]string{
	0: "Success",
	1: "UnexpectedError",
	2: "ConnectFailed",
	3: "PermissionDenied",
}

var StatusCode_value = map[string]int32{
	"Success":          0,
	"UnexpectedError":  1,
	"ConnectFailed":    2,
	"PermissionDenied": 3,
}

func (x StatusCode) String() string {
	return proto.EnumName(StatusCode_name, int32(x))
}

func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{1}
}

type LoadState int32

const (
	LoadState_INTI      LoadState = 0
	LoadState_EXECUTING LoadState = 1
	LoadState_SUCCESS   LoadState = 2
	LoadState_FAIL      LoadState = 3
	LoadState_TIMEOUT   LoadState = 4
)

var LoadState_name = map[int32]string{
	0: "INTI",
	1: "EXECUTING",
	2: "SUCCESS",
	3: "FAIL",
	4: "TIMEOUT",
}

var LoadState_value = map[string]int32{
	"INTI":      0,
	"EXECUTING": 1,
	"SUCCESS":   2,
	"FAIL":      3,
	"TIMEOUT":   4,
}

func (x LoadState) String() string {
	return proto.EnumName(LoadState_name, int32(x))
}

func (LoadState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{2}
}

type MsgBase struct {
	MsgType              MsgType  `protobuf:"varint,1,opt,name=msg_type,json=msgType,proto3,enum=milvus.proto.backup.MsgType" json:"msg_type,omitempty"`
	MsgID                int64    `protobuf:"varint,2,opt,name=msgID,proto3" json:"msgID,omitempty"`
	Timestamp            uint64   `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgBase) Reset()         { *m = MsgBase{} }
func (m *MsgBase) String() string { return proto.CompactTextString(m) }
func (*MsgBase) ProtoMessage()    {}
func (*MsgBase) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{0}
}

func (m *MsgBase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgBase.Unmarshal(m, b)
}
func (m *MsgBase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgBase.Marshal(b, m, deterministic)
}
func (m *MsgBase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBase.Merge(m, src)
}
func (m *MsgBase) XXX_Size() int {
	return xxx_messageInfo_MsgBase.Size(m)
}
func (m *MsgBase) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBase.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBase proto.InternalMessageInfo

func (m *MsgBase) GetMsgType() MsgType {
	if m != nil {
		return m.MsgType
	}
	return MsgType_Undefined
}

func (m *MsgBase) GetMsgID() int64 {
	if m != nil {
		return m.MsgID
	}
	return 0
}

func (m *MsgBase) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type Status struct {
	StatusCode           StatusCode `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3,enum=milvus.proto.backup.StatusCode" json:"status_code,omitempty"`
	Reason               string     `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{1}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetStatusCode() StatusCode {
	if m != nil {
		return m.StatusCode
	}
	return StatusCode_Success
}

func (m *Status) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

//*
// lite version of Collection info
type CollectionBackupInfo struct {
	CollectionId     int64                      `protobuf:"varint,1,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	DbName           string                     `protobuf:"bytes,2,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	CollectionName   string                     `protobuf:"bytes,3,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	Schema           *schemapb.CollectionSchema `protobuf:"bytes,4,opt,name=schema,proto3" json:"schema,omitempty"`
	ShardsNum        int32                      `protobuf:"varint,5,opt,name=shards_num,json=shardsNum,proto3" json:"shards_num,omitempty"`
	ConsistencyLevel commonpb.ConsistencyLevel  `protobuf:"varint,6,opt,name=consistency_level,json=consistencyLevel,proto3,enum=milvus.proto.common.ConsistencyLevel" json:"consistency_level,omitempty"`
	// array of partition backup
	PartitionBackups []*PartitionBackupInfo `protobuf:"bytes,7,rep,name=partition_backups,json=partitionBackups,proto3" json:"partition_backups,omitempty"`
	BackupTimestamp  uint64                 `protobuf:"varint,8,opt,name=backup_timestamp,json=backupTimestamp,proto3" json:"backup_timestamp,omitempty"`
	// backup progress status
	BackupStatus StatusCode `protobuf:"varint,9,opt,name=backup_status,json=backupStatus,proto3,enum=milvus.proto.backup.StatusCode" json:"backup_status,omitempty"`
	// backup progress error
	BackupError string `protobuf:"bytes,10,opt,name=backup_error,json=backupError,proto3" json:"backup_error,omitempty"`
	// whether the backup is able to recover
	Health               string   `protobuf:"bytes,11,opt,name=health,proto3" json:"health,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollectionBackupInfo) Reset()         { *m = CollectionBackupInfo{} }
func (m *CollectionBackupInfo) String() string { return proto.CompactTextString(m) }
func (*CollectionBackupInfo) ProtoMessage()    {}
func (*CollectionBackupInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{2}
}

func (m *CollectionBackupInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectionBackupInfo.Unmarshal(m, b)
}
func (m *CollectionBackupInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectionBackupInfo.Marshal(b, m, deterministic)
}
func (m *CollectionBackupInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectionBackupInfo.Merge(m, src)
}
func (m *CollectionBackupInfo) XXX_Size() int {
	return xxx_messageInfo_CollectionBackupInfo.Size(m)
}
func (m *CollectionBackupInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectionBackupInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CollectionBackupInfo proto.InternalMessageInfo

func (m *CollectionBackupInfo) GetCollectionId() int64 {
	if m != nil {
		return m.CollectionId
	}
	return 0
}

func (m *CollectionBackupInfo) GetDbName() string {
	if m != nil {
		return m.DbName
	}
	return ""
}

func (m *CollectionBackupInfo) GetCollectionName() string {
	if m != nil {
		return m.CollectionName
	}
	return ""
}

func (m *CollectionBackupInfo) GetSchema() *schemapb.CollectionSchema {
	if m != nil {
		return m.Schema
	}
	return nil
}

func (m *CollectionBackupInfo) GetShardsNum() int32 {
	if m != nil {
		return m.ShardsNum
	}
	return 0
}

func (m *CollectionBackupInfo) GetConsistencyLevel() commonpb.ConsistencyLevel {
	if m != nil {
		return m.ConsistencyLevel
	}
	return commonpb.ConsistencyLevel_Strong
}

func (m *CollectionBackupInfo) GetPartitionBackups() []*PartitionBackupInfo {
	if m != nil {
		return m.PartitionBackups
	}
	return nil
}

func (m *CollectionBackupInfo) GetBackupTimestamp() uint64 {
	if m != nil {
		return m.BackupTimestamp
	}
	return 0
}

func (m *CollectionBackupInfo) GetBackupStatus() StatusCode {
	if m != nil {
		return m.BackupStatus
	}
	return StatusCode_Success
}

func (m *CollectionBackupInfo) GetBackupError() string {
	if m != nil {
		return m.BackupError
	}
	return ""
}

func (m *CollectionBackupInfo) GetHealth() string {
	if m != nil {
		return m.Health
	}
	return ""
}

type PartitionBackupInfo struct {
	PartitionId   int64  `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	PartitionName string `protobuf:"bytes,2,opt,name=partition_name,json=partitionName,proto3" json:"partition_name,omitempty"`
	CollectionId  int64  `protobuf:"varint,3,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	// array of segment backup
	SegmentBackups       []*SegmentBackupInfo `protobuf:"bytes,7,rep,name=segment_backups,json=segmentBackups,proto3" json:"segment_backups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PartitionBackupInfo) Reset()         { *m = PartitionBackupInfo{} }
func (m *PartitionBackupInfo) String() string { return proto.CompactTextString(m) }
func (*PartitionBackupInfo) ProtoMessage()    {}
func (*PartitionBackupInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{3}
}

func (m *PartitionBackupInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartitionBackupInfo.Unmarshal(m, b)
}
func (m *PartitionBackupInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartitionBackupInfo.Marshal(b, m, deterministic)
}
func (m *PartitionBackupInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartitionBackupInfo.Merge(m, src)
}
func (m *PartitionBackupInfo) XXX_Size() int {
	return xxx_messageInfo_PartitionBackupInfo.Size(m)
}
func (m *PartitionBackupInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PartitionBackupInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PartitionBackupInfo proto.InternalMessageInfo

func (m *PartitionBackupInfo) GetPartitionId() int64 {
	if m != nil {
		return m.PartitionId
	}
	return 0
}

func (m *PartitionBackupInfo) GetPartitionName() string {
	if m != nil {
		return m.PartitionName
	}
	return ""
}

func (m *PartitionBackupInfo) GetCollectionId() int64 {
	if m != nil {
		return m.CollectionId
	}
	return 0
}

func (m *PartitionBackupInfo) GetSegmentBackups() []*SegmentBackupInfo {
	if m != nil {
		return m.SegmentBackups
	}
	return nil
}

//*
// lite version of datapb.SegmentInfo
type SegmentBackupInfo struct {
	SegmentId            int64                 `protobuf:"varint,1,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	CollectionId         int64                 `protobuf:"varint,2,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	PartitionId          int64                 `protobuf:"varint,3,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	NumOfRows            int64                 `protobuf:"varint,4,opt,name=num_of_rows,json=numOfRows,proto3" json:"num_of_rows,omitempty"`
	Binlogs              []*datapb.FieldBinlog `protobuf:"bytes,5,rep,name=binlogs,proto3" json:"binlogs,omitempty"`
	Statslogs            []*datapb.FieldBinlog `protobuf:"bytes,6,rep,name=statslogs,proto3" json:"statslogs,omitempty"`
	Deltalogs            []*datapb.FieldBinlog `protobuf:"bytes,7,rep,name=deltalogs,proto3" json:"deltalogs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *SegmentBackupInfo) Reset()         { *m = SegmentBackupInfo{} }
func (m *SegmentBackupInfo) String() string { return proto.CompactTextString(m) }
func (*SegmentBackupInfo) ProtoMessage()    {}
func (*SegmentBackupInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{4}
}

func (m *SegmentBackupInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SegmentBackupInfo.Unmarshal(m, b)
}
func (m *SegmentBackupInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SegmentBackupInfo.Marshal(b, m, deterministic)
}
func (m *SegmentBackupInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SegmentBackupInfo.Merge(m, src)
}
func (m *SegmentBackupInfo) XXX_Size() int {
	return xxx_messageInfo_SegmentBackupInfo.Size(m)
}
func (m *SegmentBackupInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SegmentBackupInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SegmentBackupInfo proto.InternalMessageInfo

func (m *SegmentBackupInfo) GetSegmentId() int64 {
	if m != nil {
		return m.SegmentId
	}
	return 0
}

func (m *SegmentBackupInfo) GetCollectionId() int64 {
	if m != nil {
		return m.CollectionId
	}
	return 0
}

func (m *SegmentBackupInfo) GetPartitionId() int64 {
	if m != nil {
		return m.PartitionId
	}
	return 0
}

func (m *SegmentBackupInfo) GetNumOfRows() int64 {
	if m != nil {
		return m.NumOfRows
	}
	return 0
}

func (m *SegmentBackupInfo) GetBinlogs() []*datapb.FieldBinlog {
	if m != nil {
		return m.Binlogs
	}
	return nil
}

func (m *SegmentBackupInfo) GetStatslogs() []*datapb.FieldBinlog {
	if m != nil {
		return m.Statslogs
	}
	return nil
}

func (m *SegmentBackupInfo) GetDeltalogs() []*datapb.FieldBinlog {
	if m != nil {
		return m.Deltalogs
	}
	return nil
}

//*
// root of backup
type BackupInfo struct {
	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// backup timestamp
	BackupTimestamp uint64 `protobuf:"varint,3,opt,name=backup_timestamp,json=backupTimestamp,proto3" json:"backup_timestamp,omitempty"`
	// array of collection backup
	CollectionBackups []*CollectionBackupInfo `protobuf:"bytes,4,rep,name=collection_backups,json=collectionBackups,proto3" json:"collection_backups,omitempty"`
	// backup progress status
	BackupStatus StatusCode `protobuf:"varint,5,opt,name=backup_status,json=backupStatus,proto3,enum=milvus.proto.backup.StatusCode" json:"backup_status,omitempty"`
	// backup progress error
	BackupError string `protobuf:"bytes,6,opt,name=backup_error,json=backupError,proto3" json:"backup_error,omitempty"`
	// whether the backup is able to recover
	Health               string   `protobuf:"bytes,7,opt,name=health,proto3" json:"health,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BackupInfo) Reset()         { *m = BackupInfo{} }
func (m *BackupInfo) String() string { return proto.CompactTextString(m) }
func (*BackupInfo) ProtoMessage()    {}
func (*BackupInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{5}
}

func (m *BackupInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackupInfo.Unmarshal(m, b)
}
func (m *BackupInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackupInfo.Marshal(b, m, deterministic)
}
func (m *BackupInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackupInfo.Merge(m, src)
}
func (m *BackupInfo) XXX_Size() int {
	return xxx_messageInfo_BackupInfo.Size(m)
}
func (m *BackupInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BackupInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BackupInfo proto.InternalMessageInfo

func (m *BackupInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BackupInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BackupInfo) GetBackupTimestamp() uint64 {
	if m != nil {
		return m.BackupTimestamp
	}
	return 0
}

func (m *BackupInfo) GetCollectionBackups() []*CollectionBackupInfo {
	if m != nil {
		return m.CollectionBackups
	}
	return nil
}

func (m *BackupInfo) GetBackupStatus() StatusCode {
	if m != nil {
		return m.BackupStatus
	}
	return StatusCode_Success
}

func (m *BackupInfo) GetBackupError() string {
	if m != nil {
		return m.BackupError
	}
	return ""
}

func (m *BackupInfo) GetHealth() string {
	if m != nil {
		return m.Health
	}
	return ""
}

//*
// For level storage
type CollectionLevelBackupInfo struct {
	Infos                []*CollectionBackupInfo `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *CollectionLevelBackupInfo) Reset()         { *m = CollectionLevelBackupInfo{} }
func (m *CollectionLevelBackupInfo) String() string { return proto.CompactTextString(m) }
func (*CollectionLevelBackupInfo) ProtoMessage()    {}
func (*CollectionLevelBackupInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{6}
}

func (m *CollectionLevelBackupInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectionLevelBackupInfo.Unmarshal(m, b)
}
func (m *CollectionLevelBackupInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectionLevelBackupInfo.Marshal(b, m, deterministic)
}
func (m *CollectionLevelBackupInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectionLevelBackupInfo.Merge(m, src)
}
func (m *CollectionLevelBackupInfo) XXX_Size() int {
	return xxx_messageInfo_CollectionLevelBackupInfo.Size(m)
}
func (m *CollectionLevelBackupInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectionLevelBackupInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CollectionLevelBackupInfo proto.InternalMessageInfo

func (m *CollectionLevelBackupInfo) GetInfos() []*CollectionBackupInfo {
	if m != nil {
		return m.Infos
	}
	return nil
}

//*
// For level storage
type PartitionLevelBackupInfo struct {
	Infos                []*PartitionBackupInfo `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *PartitionLevelBackupInfo) Reset()         { *m = PartitionLevelBackupInfo{} }
func (m *PartitionLevelBackupInfo) String() string { return proto.CompactTextString(m) }
func (*PartitionLevelBackupInfo) ProtoMessage()    {}
func (*PartitionLevelBackupInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{7}
}

func (m *PartitionLevelBackupInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartitionLevelBackupInfo.Unmarshal(m, b)
}
func (m *PartitionLevelBackupInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartitionLevelBackupInfo.Marshal(b, m, deterministic)
}
func (m *PartitionLevelBackupInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartitionLevelBackupInfo.Merge(m, src)
}
func (m *PartitionLevelBackupInfo) XXX_Size() int {
	return xxx_messageInfo_PartitionLevelBackupInfo.Size(m)
}
func (m *PartitionLevelBackupInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PartitionLevelBackupInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PartitionLevelBackupInfo proto.InternalMessageInfo

func (m *PartitionLevelBackupInfo) GetInfos() []*PartitionBackupInfo {
	if m != nil {
		return m.Infos
	}
	return nil
}

//*
// For level storage
type SegmentLevelBackupInfo struct {
	Infos                []*SegmentBackupInfo `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SegmentLevelBackupInfo) Reset()         { *m = SegmentLevelBackupInfo{} }
func (m *SegmentLevelBackupInfo) String() string { return proto.CompactTextString(m) }
func (*SegmentLevelBackupInfo) ProtoMessage()    {}
func (*SegmentLevelBackupInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{8}
}

func (m *SegmentLevelBackupInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SegmentLevelBackupInfo.Unmarshal(m, b)
}
func (m *SegmentLevelBackupInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SegmentLevelBackupInfo.Marshal(b, m, deterministic)
}
func (m *SegmentLevelBackupInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SegmentLevelBackupInfo.Merge(m, src)
}
func (m *SegmentLevelBackupInfo) XXX_Size() int {
	return xxx_messageInfo_SegmentLevelBackupInfo.Size(m)
}
func (m *SegmentLevelBackupInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SegmentLevelBackupInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SegmentLevelBackupInfo proto.InternalMessageInfo

func (m *SegmentLevelBackupInfo) GetInfos() []*SegmentBackupInfo {
	if m != nil {
		return m.Infos
	}
	return nil
}

//*
// Create Backup in milvus
type CreateBackupRequest struct {
	Base *MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	// backup name, if not set, will generate one
	BackupName string `protobuf:"bytes,2,opt,name=backup_name,json=backupName,proto3" json:"backup_name,omitempty"`
	// collection names to backup, empty to backup all
	CollectionNames      []string `protobuf:"bytes,3,rep,name=collection_names,json=collectionNames,proto3" json:"collection_names,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBackupRequest) Reset()         { *m = CreateBackupRequest{} }
func (m *CreateBackupRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBackupRequest) ProtoMessage()    {}
func (*CreateBackupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{9}
}

func (m *CreateBackupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBackupRequest.Unmarshal(m, b)
}
func (m *CreateBackupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBackupRequest.Marshal(b, m, deterministic)
}
func (m *CreateBackupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBackupRequest.Merge(m, src)
}
func (m *CreateBackupRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBackupRequest.Size(m)
}
func (m *CreateBackupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBackupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBackupRequest proto.InternalMessageInfo

func (m *CreateBackupRequest) GetBase() *MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *CreateBackupRequest) GetBackupName() string {
	if m != nil {
		return m.BackupName
	}
	return ""
}

func (m *CreateBackupRequest) GetCollectionNames() []string {
	if m != nil {
		return m.CollectionNames
	}
	return nil
}

//*
// CreateBackupResponse
type CreateBackupResponse struct {
	Status               *Status     `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	BackupInfo           *BackupInfo `protobuf:"bytes,2,opt,name=backup_info,json=backupInfo,proto3" json:"backup_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateBackupResponse) Reset()         { *m = CreateBackupResponse{} }
func (m *CreateBackupResponse) String() string { return proto.CompactTextString(m) }
func (*CreateBackupResponse) ProtoMessage()    {}
func (*CreateBackupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{10}
}

func (m *CreateBackupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBackupResponse.Unmarshal(m, b)
}
func (m *CreateBackupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBackupResponse.Marshal(b, m, deterministic)
}
func (m *CreateBackupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBackupResponse.Merge(m, src)
}
func (m *CreateBackupResponse) XXX_Size() int {
	return xxx_messageInfo_CreateBackupResponse.Size(m)
}
func (m *CreateBackupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBackupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBackupResponse proto.InternalMessageInfo

func (m *CreateBackupResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *CreateBackupResponse) GetBackupInfo() *BackupInfo {
	if m != nil {
		return m.BackupInfo
	}
	return nil
}

type GetBackupRequest struct {
	Base                 *MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	BackupName           string   `protobuf:"bytes,2,opt,name=backup_name,json=backupName,proto3" json:"backup_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBackupRequest) Reset()         { *m = GetBackupRequest{} }
func (m *GetBackupRequest) String() string { return proto.CompactTextString(m) }
func (*GetBackupRequest) ProtoMessage()    {}
func (*GetBackupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{11}
}

func (m *GetBackupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBackupRequest.Unmarshal(m, b)
}
func (m *GetBackupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBackupRequest.Marshal(b, m, deterministic)
}
func (m *GetBackupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBackupRequest.Merge(m, src)
}
func (m *GetBackupRequest) XXX_Size() int {
	return xxx_messageInfo_GetBackupRequest.Size(m)
}
func (m *GetBackupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBackupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBackupRequest proto.InternalMessageInfo

func (m *GetBackupRequest) GetBase() *MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *GetBackupRequest) GetBackupName() string {
	if m != nil {
		return m.BackupName
	}
	return ""
}

type GetBackupResponse struct {
	Status               *Status     `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	BackupInfo           *BackupInfo `protobuf:"bytes,2,opt,name=backup_info,json=backupInfo,proto3" json:"backup_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetBackupResponse) Reset()         { *m = GetBackupResponse{} }
func (m *GetBackupResponse) String() string { return proto.CompactTextString(m) }
func (*GetBackupResponse) ProtoMessage()    {}
func (*GetBackupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{12}
}

func (m *GetBackupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBackupResponse.Unmarshal(m, b)
}
func (m *GetBackupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBackupResponse.Marshal(b, m, deterministic)
}
func (m *GetBackupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBackupResponse.Merge(m, src)
}
func (m *GetBackupResponse) XXX_Size() int {
	return xxx_messageInfo_GetBackupResponse.Size(m)
}
func (m *GetBackupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBackupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBackupResponse proto.InternalMessageInfo

func (m *GetBackupResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetBackupResponse) GetBackupInfo() *BackupInfo {
	if m != nil {
		return m.BackupInfo
	}
	return nil
}

type ListBackupsRequest struct {
	Base                 *MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	CollectionName       string   `protobuf:"bytes,2,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBackupsRequest) Reset()         { *m = ListBackupsRequest{} }
func (m *ListBackupsRequest) String() string { return proto.CompactTextString(m) }
func (*ListBackupsRequest) ProtoMessage()    {}
func (*ListBackupsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{13}
}

func (m *ListBackupsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBackupsRequest.Unmarshal(m, b)
}
func (m *ListBackupsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBackupsRequest.Marshal(b, m, deterministic)
}
func (m *ListBackupsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBackupsRequest.Merge(m, src)
}
func (m *ListBackupsRequest) XXX_Size() int {
	return xxx_messageInfo_ListBackupsRequest.Size(m)
}
func (m *ListBackupsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBackupsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListBackupsRequest proto.InternalMessageInfo

func (m *ListBackupsRequest) GetBase() *MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *ListBackupsRequest) GetCollectionName() string {
	if m != nil {
		return m.CollectionName
	}
	return ""
}

type ListBackupsResponse struct {
	Status               *Status       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	BackupInfos          []*BackupInfo `protobuf:"bytes,2,rep,name=backup_infos,json=backupInfos,proto3" json:"backup_infos,omitempty"`
	FailBackups          []string      `protobuf:"bytes,3,rep,name=failBackups,proto3" json:"failBackups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListBackupsResponse) Reset()         { *m = ListBackupsResponse{} }
func (m *ListBackupsResponse) String() string { return proto.CompactTextString(m) }
func (*ListBackupsResponse) ProtoMessage()    {}
func (*ListBackupsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{14}
}

func (m *ListBackupsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBackupsResponse.Unmarshal(m, b)
}
func (m *ListBackupsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBackupsResponse.Marshal(b, m, deterministic)
}
func (m *ListBackupsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBackupsResponse.Merge(m, src)
}
func (m *ListBackupsResponse) XXX_Size() int {
	return xxx_messageInfo_ListBackupsResponse.Size(m)
}
func (m *ListBackupsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBackupsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListBackupsResponse proto.InternalMessageInfo

func (m *ListBackupsResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ListBackupsResponse) GetBackupInfos() []*BackupInfo {
	if m != nil {
		return m.BackupInfos
	}
	return nil
}

func (m *ListBackupsResponse) GetFailBackups() []string {
	if m != nil {
		return m.FailBackups
	}
	return nil
}

type DeleteBackupRequest struct {
	Base                 *MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	BackupName           string   `protobuf:"bytes,2,opt,name=backup_name,json=backupName,proto3" json:"backup_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBackupRequest) Reset()         { *m = DeleteBackupRequest{} }
func (m *DeleteBackupRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteBackupRequest) ProtoMessage()    {}
func (*DeleteBackupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{15}
}

func (m *DeleteBackupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBackupRequest.Unmarshal(m, b)
}
func (m *DeleteBackupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBackupRequest.Marshal(b, m, deterministic)
}
func (m *DeleteBackupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBackupRequest.Merge(m, src)
}
func (m *DeleteBackupRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteBackupRequest.Size(m)
}
func (m *DeleteBackupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBackupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBackupRequest proto.InternalMessageInfo

func (m *DeleteBackupRequest) GetBase() *MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *DeleteBackupRequest) GetBackupName() string {
	if m != nil {
		return m.BackupName
	}
	return ""
}

type DeleteBackupResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBackupResponse) Reset()         { *m = DeleteBackupResponse{} }
func (m *DeleteBackupResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteBackupResponse) ProtoMessage()    {}
func (*DeleteBackupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{16}
}

func (m *DeleteBackupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBackupResponse.Unmarshal(m, b)
}
func (m *DeleteBackupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBackupResponse.Marshal(b, m, deterministic)
}
func (m *DeleteBackupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBackupResponse.Merge(m, src)
}
func (m *DeleteBackupResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteBackupResponse.Size(m)
}
func (m *DeleteBackupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBackupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBackupResponse proto.InternalMessageInfo

func (m *DeleteBackupResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type LoadCollectionBackupTask struct {
	State                LoadState             `protobuf:"varint,1,opt,name=state,proto3,enum=milvus.proto.backup.LoadState" json:"state,omitempty"`
	ErrorMessage         string                `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	CollBackup           *CollectionBackupInfo `protobuf:"bytes,3,opt,name=coll_backup,json=collBackup,proto3" json:"coll_backup,omitempty"`
	TargetCollectionName string                `protobuf:"bytes,4,opt,name=target_collection_name,json=targetCollectionName,proto3" json:"target_collection_name,omitempty"`
	UnloadedSegments     []int64               `protobuf:"varint,5,rep,packed,name=unloaded_segments,json=unloadedSegments,proto3" json:"unloaded_segments,omitempty"`
	LoadedSegments       []int64               `protobuf:"varint,6,rep,packed,name=loaded_segments,json=loadedSegments,proto3" json:"loaded_segments,omitempty"`
	Duration             int64                 `protobuf:"varint,7,opt,name=duration,proto3" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *LoadCollectionBackupTask) Reset()         { *m = LoadCollectionBackupTask{} }
func (m *LoadCollectionBackupTask) String() string { return proto.CompactTextString(m) }
func (*LoadCollectionBackupTask) ProtoMessage()    {}
func (*LoadCollectionBackupTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{17}
}

func (m *LoadCollectionBackupTask) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadCollectionBackupTask.Unmarshal(m, b)
}
func (m *LoadCollectionBackupTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadCollectionBackupTask.Marshal(b, m, deterministic)
}
func (m *LoadCollectionBackupTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadCollectionBackupTask.Merge(m, src)
}
func (m *LoadCollectionBackupTask) XXX_Size() int {
	return xxx_messageInfo_LoadCollectionBackupTask.Size(m)
}
func (m *LoadCollectionBackupTask) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadCollectionBackupTask.DiscardUnknown(m)
}

var xxx_messageInfo_LoadCollectionBackupTask proto.InternalMessageInfo

func (m *LoadCollectionBackupTask) GetState() LoadState {
	if m != nil {
		return m.State
	}
	return LoadState_INTI
}

func (m *LoadCollectionBackupTask) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *LoadCollectionBackupTask) GetCollBackup() *CollectionBackupInfo {
	if m != nil {
		return m.CollBackup
	}
	return nil
}

func (m *LoadCollectionBackupTask) GetTargetCollectionName() string {
	if m != nil {
		return m.TargetCollectionName
	}
	return ""
}

func (m *LoadCollectionBackupTask) GetUnloadedSegments() []int64 {
	if m != nil {
		return m.UnloadedSegments
	}
	return nil
}

func (m *LoadCollectionBackupTask) GetLoadedSegments() []int64 {
	if m != nil {
		return m.LoadedSegments
	}
	return nil
}

func (m *LoadCollectionBackupTask) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

type LoadBackupRequest struct {
	Base            *MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	BackupName      string   `protobuf:"bytes,2,opt,name=backup_name,json=backupName,proto3" json:"backup_name,omitempty"`
	CollectionNames []string `protobuf:"bytes,3,rep,name=collection_names,json=collectionNames,proto3" json:"collection_names,omitempty"`
	// Support two ways to rename the collections while recover
	// 1, set a suffix
	CollectionSuffix string `protobuf:"bytes,4,opt,name=collection_suffix,json=collectionSuffix,proto3" json:"collection_suffix,omitempty"`
	// 2, give a map to rename the collections, if not given, use the original name
	CollectionRenames    map[string]string `protobuf:"bytes,5,rep,name=collection_renames,json=collectionRenames,proto3" json:"collection_renames,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *LoadBackupRequest) Reset()         { *m = LoadBackupRequest{} }
func (m *LoadBackupRequest) String() string { return proto.CompactTextString(m) }
func (*LoadBackupRequest) ProtoMessage()    {}
func (*LoadBackupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{18}
}

func (m *LoadBackupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadBackupRequest.Unmarshal(m, b)
}
func (m *LoadBackupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadBackupRequest.Marshal(b, m, deterministic)
}
func (m *LoadBackupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadBackupRequest.Merge(m, src)
}
func (m *LoadBackupRequest) XXX_Size() int {
	return xxx_messageInfo_LoadBackupRequest.Size(m)
}
func (m *LoadBackupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadBackupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoadBackupRequest proto.InternalMessageInfo

func (m *LoadBackupRequest) GetBase() *MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *LoadBackupRequest) GetBackupName() string {
	if m != nil {
		return m.BackupName
	}
	return ""
}

func (m *LoadBackupRequest) GetCollectionNames() []string {
	if m != nil {
		return m.CollectionNames
	}
	return nil
}

func (m *LoadBackupRequest) GetCollectionSuffix() string {
	if m != nil {
		return m.CollectionSuffix
	}
	return ""
}

func (m *LoadBackupRequest) GetCollectionRenames() map[string]string {
	if m != nil {
		return m.CollectionRenames
	}
	return nil
}

type LoadBackupResponse struct {
	Status                *Status                     `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	BackupInfo            *BackupInfo                 `protobuf:"bytes,2,opt,name=backup_info,json=backupInfo,proto3" json:"backup_info,omitempty"`
	CollectionBackupTasks []*LoadCollectionBackupTask `protobuf:"bytes,3,rep,name=collection_backup_tasks,json=collectionBackupTasks,proto3" json:"collection_backup_tasks,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                    `json:"-"`
	XXX_unrecognized      []byte                      `json:"-"`
	XXX_sizecache         int32                       `json:"-"`
}

func (m *LoadBackupResponse) Reset()         { *m = LoadBackupResponse{} }
func (m *LoadBackupResponse) String() string { return proto.CompactTextString(m) }
func (*LoadBackupResponse) ProtoMessage()    {}
func (*LoadBackupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{19}
}

func (m *LoadBackupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadBackupResponse.Unmarshal(m, b)
}
func (m *LoadBackupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadBackupResponse.Marshal(b, m, deterministic)
}
func (m *LoadBackupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadBackupResponse.Merge(m, src)
}
func (m *LoadBackupResponse) XXX_Size() int {
	return xxx_messageInfo_LoadBackupResponse.Size(m)
}
func (m *LoadBackupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadBackupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoadBackupResponse proto.InternalMessageInfo

func (m *LoadBackupResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *LoadBackupResponse) GetBackupInfo() *BackupInfo {
	if m != nil {
		return m.BackupInfo
	}
	return nil
}

func (m *LoadBackupResponse) GetCollectionBackupTasks() []*LoadCollectionBackupTask {
	if m != nil {
		return m.CollectionBackupTasks
	}
	return nil
}

func init() {
	proto.RegisterEnum("milvus.proto.backup.MsgType", MsgType_name, MsgType_value)
	proto.RegisterEnum("milvus.proto.backup.StatusCode", StatusCode_name, StatusCode_value)
	proto.RegisterEnum("milvus.proto.backup.LoadState", LoadState_name, LoadState_value)
	proto.RegisterType((*MsgBase)(nil), "milvus.proto.backup.MsgBase")
	proto.RegisterType((*Status)(nil), "milvus.proto.backup.Status")
	proto.RegisterType((*CollectionBackupInfo)(nil), "milvus.proto.backup.CollectionBackupInfo")
	proto.RegisterType((*PartitionBackupInfo)(nil), "milvus.proto.backup.PartitionBackupInfo")
	proto.RegisterType((*SegmentBackupInfo)(nil), "milvus.proto.backup.SegmentBackupInfo")
	proto.RegisterType((*BackupInfo)(nil), "milvus.proto.backup.BackupInfo")
	proto.RegisterType((*CollectionLevelBackupInfo)(nil), "milvus.proto.backup.CollectionLevelBackupInfo")
	proto.RegisterType((*PartitionLevelBackupInfo)(nil), "milvus.proto.backup.PartitionLevelBackupInfo")
	proto.RegisterType((*SegmentLevelBackupInfo)(nil), "milvus.proto.backup.SegmentLevelBackupInfo")
	proto.RegisterType((*CreateBackupRequest)(nil), "milvus.proto.backup.CreateBackupRequest")
	proto.RegisterType((*CreateBackupResponse)(nil), "milvus.proto.backup.CreateBackupResponse")
	proto.RegisterType((*GetBackupRequest)(nil), "milvus.proto.backup.GetBackupRequest")
	proto.RegisterType((*GetBackupResponse)(nil), "milvus.proto.backup.GetBackupResponse")
	proto.RegisterType((*ListBackupsRequest)(nil), "milvus.proto.backup.ListBackupsRequest")
	proto.RegisterType((*ListBackupsResponse)(nil), "milvus.proto.backup.ListBackupsResponse")
	proto.RegisterType((*DeleteBackupRequest)(nil), "milvus.proto.backup.DeleteBackupRequest")
	proto.RegisterType((*DeleteBackupResponse)(nil), "milvus.proto.backup.DeleteBackupResponse")
	proto.RegisterType((*LoadCollectionBackupTask)(nil), "milvus.proto.backup.LoadCollectionBackupTask")
	proto.RegisterType((*LoadBackupRequest)(nil), "milvus.proto.backup.LoadBackupRequest")
	proto.RegisterMapType((map[string]string)(nil), "milvus.proto.backup.LoadBackupRequest.CollectionRenamesEntry")
	proto.RegisterType((*LoadBackupResponse)(nil), "milvus.proto.backup.LoadBackupResponse")
}

func init() { proto.RegisterFile("backup.proto", fileDescriptor_65240d19de191688) }

var fileDescriptor_65240d19de191688 = []byte{
	// 1497 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x57, 0xdb, 0x6e, 0xdb, 0xc6,
	0x16, 0x35, 0x45, 0x59, 0xb2, 0x36, 0x7d, 0xa1, 0x46, 0x3e, 0x0e, 0x8f, 0x4e, 0x4e, 0xa2, 0xb2,
	0x48, 0xa2, 0xa4, 0x88, 0x5d, 0x38, 0x01, 0x92, 0x16, 0x49, 0x2f, 0x96, 0x9d, 0x54, 0xad, 0xed,
	0x04, 0x94, 0xdc, 0x06, 0x41, 0x00, 0x82, 0x22, 0x47, 0x12, 0x61, 0x5e, 0x54, 0x0e, 0xe9, 0xc4,
	0xf9, 0x80, 0x3e, 0x14, 0xe8, 0x53, 0x7f, 0xa4, 0xe8, 0x43, 0xbf, 0xa3, 0x2f, 0xfd, 0x87, 0x3e,
	0xe7, 0x0b, 0x0a, 0xce, 0xf0, 0x2a, 0xd1, 0xb1, 0xd2, 0x34, 0x48, 0xdf, 0x38, 0x5b, 0x6b, 0xef,
	0x99, 0x59, 0xb3, 0xf6, 0x45, 0xb0, 0x3c, 0xd0, 0xf4, 0xe3, 0x60, 0xb2, 0x39, 0xf1, 0x5c, 0xdf,
	0x45, 0x0d, 0xdb, 0xb4, 0x4e, 0x02, 0xc2, 0x56, 0x9b, 0xec, 0xa7, 0xe6, 0x32, 0xd1, 0xc7, 0xd8,
	0xd6, 0x98, 0xb1, 0xb9, 0xac, 0xbb, 0xb6, 0xed, 0x3a, 0xd1, 0x4a, 0x34, 0x34, 0x5f, 0x53, 0x75,
	0xd7, 0xf5, 0x0c, 0x66, 0x91, 0x4f, 0xa0, 0x7a, 0x40, 0x46, 0x3b, 0x1a, 0xc1, 0xe8, 0x0e, 0x2c,
	0xd9, 0x64, 0xa4, 0xfa, 0xa7, 0x13, 0x2c, 0x71, 0x2d, 0xae, 0xbd, 0xba, 0x7d, 0x71, 0xb3, 0x60,
	0x83, 0xcd, 0x03, 0x32, 0xea, 0x9f, 0x4e, 0xb0, 0x52, 0xb5, 0xd9, 0x07, 0x5a, 0x87, 0x45, 0x9b,
	0x8c, 0xba, 0xbb, 0x52, 0xa9, 0xc5, 0xb5, 0x79, 0x85, 0x2d, 0xd0, 0x45, 0xa8, 0xf9, 0xa6, 0x8d,
	0x89, 0xaf, 0xd9, 0x13, 0x89, 0x6f, 0x71, 0xed, 0xb2, 0x92, 0x1a, 0xe4, 0x01, 0x54, 0x7a, 0xbe,
	0xe6, 0x07, 0x04, 0x7d, 0x01, 0x02, 0xa1, 0x5f, 0xaa, 0xee, 0x1a, 0xf1, 0xce, 0x97, 0x0b, 0x77,
	0x66, 0x1e, 0x1d, 0xd7, 0xc0, 0x0a, 0x90, 0xe4, 0x1b, 0x6d, 0x40, 0xc5, 0xc3, 0x1a, 0x71, 0x1d,
	0x7a, 0x80, 0x9a, 0x12, 0xad, 0xe4, 0x5f, 0xcb, 0xb0, 0xde, 0x71, 0x2d, 0x0b, 0xeb, 0xbe, 0xe9,
	0x3a, 0x3b, 0x34, 0x46, 0xd7, 0x19, 0xba, 0xe8, 0x43, 0x58, 0xd1, 0x13, 0xbb, 0x6a, 0x1a, 0x74,
	0x53, 0x5e, 0x59, 0x4e, 0x8d, 0x5d, 0x03, 0x5d, 0x80, 0xaa, 0x31, 0x50, 0x1d, 0xcd, 0xc6, 0x71,
	0x58, 0x63, 0x70, 0xa8, 0xd9, 0x18, 0x5d, 0x83, 0xb5, 0x8c, 0x37, 0x05, 0xf0, 0x14, 0xb0, 0x9a,
	0x9a, 0x29, 0xf0, 0x3e, 0x54, 0xd8, 0x5b, 0x48, 0xe5, 0x16, 0xd7, 0x16, 0xb6, 0xaf, 0xe4, 0x2f,
	0x15, 0xbd, 0x53, 0x7a, 0xc2, 0x1e, 0x35, 0x28, 0x91, 0x13, 0xfa, 0x3f, 0x00, 0x19, 0x6b, 0x9e,
	0x41, 0x54, 0x27, 0xb0, 0xa5, 0xc5, 0x16, 0xd7, 0x5e, 0x54, 0x6a, 0xcc, 0x72, 0x18, 0xd8, 0x48,
	0x81, 0xba, 0xee, 0x3a, 0xc4, 0x24, 0x3e, 0x76, 0xf4, 0x53, 0xd5, 0xc2, 0x27, 0xd8, 0x92, 0x2a,
	0x94, 0xbd, 0xa9, 0x8d, 0x22, 0x09, 0x74, 0x52, 0xf4, 0x7e, 0x08, 0x56, 0x44, 0x7d, 0xca, 0x82,
	0x8e, 0xa0, 0x3e, 0xd1, 0x3c, 0xdf, 0xa4, 0x37, 0x63, 0xa4, 0x13, 0xa9, 0xda, 0xe2, 0xdb, 0xc2,
	0x76, 0xbb, 0xf0, 0x45, 0x1e, 0xc7, 0xe8, 0x94, 0x5d, 0x45, 0x9c, 0xe4, 0x8d, 0x04, 0x5d, 0x07,
	0x91, 0xe1, 0xd5, 0x54, 0x11, 0x4b, 0x54, 0x11, 0x6b, 0xcc, 0xde, 0x8f, 0xcd, 0x68, 0x17, 0x56,
	0x22, 0x28, 0x7b, 0x60, 0xa9, 0x36, 0x9f, 0x1e, 0xa2, 0xc4, 0x88, 0x34, 0xf5, 0x41, 0x9c, 0x28,
	0x2a, 0xf6, 0x3c, 0xd7, 0x93, 0x80, 0xbe, 0x8f, 0xc0, 0x6c, 0x7b, 0xa1, 0x29, 0x14, 0xcd, 0x18,
	0x6b, 0x96, 0x3f, 0x96, 0x04, 0xf6, 0xba, 0x6c, 0x25, 0xff, 0xc1, 0x41, 0xa3, 0xe0, 0x56, 0x61,
	0xc8, 0x94, 0x9a, 0x44, 0x32, 0x42, 0x62, 0xeb, 0x1a, 0xe8, 0x0a, 0xac, 0xa6, 0x90, 0x8c, 0x70,
	0x56, 0x12, 0x2b, 0x95, 0xc5, 0x8c, 0xfa, 0xf8, 0x02, 0xf5, 0x3d, 0x82, 0x35, 0x82, 0x47, 0x36,
	0x76, 0xfc, 0xa9, 0x77, 0xb8, 0x5a, 0xcc, 0x04, 0xc3, 0x66, 0x5e, 0x61, 0x95, 0x64, 0x4d, 0x44,
	0xfe, 0xbd, 0x04, 0xf5, 0x19, 0x14, 0xd5, 0x58, 0xb4, 0x4d, 0x72, 0xa7, 0x5a, 0x64, 0xe9, 0x1a,
	0xb3, 0x47, 0x2d, 0x15, 0x1c, 0x75, 0x9a, 0x19, 0x7e, 0x96, 0x99, 0x4b, 0x20, 0x38, 0x81, 0xad,
	0xba, 0x43, 0xd5, 0x73, 0x9f, 0x13, 0x9a, 0x0e, 0xbc, 0x52, 0x73, 0x02, 0xfb, 0xd1, 0x50, 0x71,
	0x9f, 0x13, 0x74, 0x17, 0xaa, 0x03, 0xd3, 0xb1, 0xdc, 0x11, 0x91, 0x16, 0xe9, 0x2d, 0x2f, 0xe5,
	0x6f, 0x19, 0x96, 0xad, 0xcd, 0x07, 0x26, 0xb6, 0x8c, 0x1d, 0x0a, 0x53, 0x62, 0x38, 0xba, 0x07,
	0xb5, 0x50, 0x28, 0x84, 0xfa, 0x56, 0xe6, 0xf2, 0x4d, 0x1d, 0x42, 0x6f, 0x03, 0x5b, 0xbe, 0x46,
	0xbd, 0xab, 0xf3, 0x79, 0x27, 0x0e, 0xf2, 0x6f, 0x25, 0x80, 0x0c, 0x97, 0xab, 0x50, 0x4a, 0x38,
	0x2c, 0x99, 0x06, 0x42, 0x50, 0xce, 0x88, 0x80, 0x7e, 0x17, 0x66, 0x02, 0x5f, 0x9c, 0x09, 0x4f,
	0x00, 0x65, 0xb8, 0x8f, 0x45, 0x50, 0xa6, 0x87, 0xbc, 0x5e, 0x28, 0x82, 0xa2, 0x5a, 0xa7, 0xd4,
	0xf5, 0x29, 0x2b, 0x99, 0xcd, 0xb1, 0xc5, 0x7f, 0x22, 0xc7, 0x2a, 0xaf, 0xcb, 0xb1, 0x6a, 0x2e,
	0xc7, 0x9e, 0xc1, 0x7f, 0xd3, 0xb3, 0xd2, 0xca, 0x93, 0xa1, 0xf1, 0x73, 0x58, 0x34, 0x9d, 0xa1,
	0x4b, 0x24, 0xee, 0x4d, 0xaf, 0xca, 0xfc, 0xe4, 0xa7, 0x20, 0x25, 0x09, 0x3c, 0x1d, 0xfc, 0xb3,
	0x7c, 0xf0, 0xf9, 0x8b, 0x5a, 0x14, 0xfb, 0x5b, 0xd8, 0x88, 0x92, 0x68, 0x3a, 0xf2, 0xbd, 0x7c,
	0xe4, 0x79, 0xd3, 0x34, 0x8a, 0xfb, 0x33, 0x07, 0x8d, 0x8e, 0x87, 0x35, 0x1f, 0xb3, 0xdf, 0x14,
	0xfc, 0x7d, 0x80, 0x89, 0x8f, 0x3e, 0x86, 0xf2, 0x40, 0x23, 0xac, 0x2b, 0x0a, 0x67, 0xf7, 0xe3,
	0xb0, 0x7f, 0x2b, 0x14, 0x89, 0x2e, 0x43, 0xf4, 0x04, 0xd9, 0x0a, 0x04, 0xcc, 0x74, 0x18, 0x49,
	0x70, 0xaa, 0x7d, 0x11, 0x89, 0x6f, 0xf1, 0xed, 0x9a, 0xb2, 0x96, 0xef, 0x5f, 0x44, 0xfe, 0x89,
	0x83, 0xf5, 0xfc, 0xa9, 0xc8, 0xc4, 0x75, 0x08, 0x46, 0xb7, 0xa0, 0x12, 0x49, 0x87, 0x1d, 0xec,
	0x7f, 0xaf, 0x91, 0x8e, 0x12, 0x41, 0xc3, 0x46, 0x1f, 0x9d, 0x2c, 0xbc, 0x33, 0x3d, 0x99, 0x70,
	0x86, 0xe8, 0x32, 0x04, 0x45, 0x47, 0x0f, 0xbf, 0x65, 0x0c, 0xe2, 0x43, 0xec, 0xbf, 0x6b, 0x86,
	0xe4, 0x1f, 0x39, 0xa8, 0x67, 0xf6, 0x79, 0xbf, 0x77, 0x76, 0x01, 0xed, 0x9b, 0x24, 0x2e, 0xe3,
	0x7f, 0xff, 0xd6, 0x05, 0x53, 0x4b, 0xa9, 0x68, 0x6a, 0x91, 0x7f, 0xe1, 0xa0, 0x91, 0xdb, 0xf1,
	0x6d, 0xee, 0xbf, 0x93, 0x14, 0x09, 0x96, 0x1c, 0x25, 0x9a, 0x1c, 0xe7, 0x12, 0x20, 0xa4, 0x04,
	0x10, 0xd4, 0x02, 0x61, 0xa8, 0x99, 0x51, 0xae, 0xc5, 0x5a, 0xcd, 0x9a, 0xe4, 0x31, 0x34, 0x76,
	0xb1, 0x85, 0xdf, 0x7d, 0xf2, 0xc8, 0xdf, 0xc0, 0x7a, 0x7e, 0xa7, 0xb7, 0x20, 0x47, 0xfe, 0xb3,
	0x04, 0xd2, 0xbe, 0xab, 0x19, 0xd3, 0xc5, 0xac, 0xaf, 0x91, 0x63, 0x74, 0x1b, 0x16, 0x43, 0x58,
	0x3c, 0x10, 0x5f, 0x2a, 0x0c, 0x18, 0x7a, 0x87, 0x41, 0xb1, 0xc2, 0xc0, 0x48, 0x86, 0x65, 0x5a,
	0x8d, 0x0f, 0x30, 0x21, 0xda, 0x28, 0xbe, 0x41, 0xce, 0x86, 0xbe, 0x06, 0x21, 0x7c, 0xf2, 0xa8,
	0xa5, 0xd0, 0xf6, 0xf3, 0x46, 0x65, 0x16, 0x42, 0x6f, 0xb6, 0x46, 0xb7, 0x61, 0xc3, 0xd7, 0xbc,
	0x11, 0xf6, 0xd5, 0x69, 0x71, 0x95, 0xe9, 0xce, 0xeb, 0xec, 0xd7, 0x4e, 0x7e, 0x30, 0xfe, 0x08,
	0xea, 0x81, 0x63, 0xb9, 0x9a, 0x81, 0x0d, 0x35, 0x1a, 0x36, 0x58, 0xe3, 0xe7, 0x15, 0x31, 0xfe,
	0x21, 0x2a, 0x95, 0x24, 0x14, 0xee, 0x34, 0xb4, 0x42, 0xa1, 0xab, 0x53, 0xc0, 0x26, 0x2c, 0x19,
	0x81, 0xa7, 0x85, 0xbb, 0xd0, 0x7e, 0xc3, 0x2b, 0xc9, 0x5a, 0x7e, 0x55, 0x82, 0x7a, 0x48, 0xd6,
	0xbf, 0xa8, 0xba, 0x86, 0x2c, 0x64, 0xa0, 0x24, 0x18, 0x0e, 0xcd, 0x17, 0x11, 0x6d, 0x99, 0x18,
	0x3d, 0x6a, 0x47, 0x56, 0x6e, 0x1a, 0xf0, 0x30, 0x8b, 0xcc, 0x86, 0xa5, 0xfb, 0x67, 0x6a, 0x23,
	0x77, 0xdd, 0xcc, 0x6b, 0x2a, 0xcc, 0x7f, 0xcf, 0xf1, 0xbd, 0xd3, 0xec, 0x84, 0x10, 0xd9, 0x9b,
	0xbb, 0xb0, 0x51, 0x0c, 0x46, 0x22, 0xf0, 0xc7, 0xf8, 0x94, 0x32, 0x56, 0x53, 0xc2, 0xcf, 0xf0,
	0xdf, 0xdf, 0x89, 0x66, 0x05, 0x31, 0x19, 0x6c, 0xf1, 0x69, 0xe9, 0x2e, 0x27, 0xbf, 0xe2, 0x00,
	0x65, 0x4f, 0xf1, 0x5e, 0x0b, 0x29, 0xc2, 0x70, 0x61, 0x66, 0x9e, 0x52, 0x7d, 0x8d, 0x1c, 0xb3,
	0x07, 0x12, 0xb6, 0x6f, 0x9e, 0x49, 0x63, 0x51, 0x82, 0x2a, 0xff, 0xd1, 0x0b, 0xac, 0xe4, 0x86,
	0x45, 0xff, 0x50, 0xd3, 0xff, 0xc5, 0x2b, 0x50, 0x3b, 0x72, 0x0c, 0x3c, 0x34, 0x1d, 0x6c, 0x88,
	0x0b, 0x48, 0x84, 0xe5, 0x6c, 0x33, 0x15, 0x8d, 0x10, 0x90, 0xf4, 0x19, 0x11, 0xa3, 0x35, 0x10,
	0x32, 0x85, 0x57, 0x1c, 0x86, 0x1e, 0xd9, 0x6a, 0x23, 0x8e, 0xd0, 0x2a, 0x40, 0xca, 0xa8, 0x38,
	0xbe, 0xf1, 0x1d, 0x40, 0x3a, 0xa0, 0x21, 0x01, 0xaa, 0xbd, 0x40, 0xd7, 0x31, 0x21, 0xe2, 0x02,
	0x6a, 0xc0, 0xda, 0x91, 0x83, 0x5f, 0x4c, 0xb0, 0xee, 0x63, 0x83, 0xce, 0x63, 0x22, 0x87, 0xea,
	0xb0, 0xd2, 0x71, 0x1d, 0x07, 0xeb, 0xfe, 0x03, 0xcd, 0xb4, 0xb0, 0x21, 0x96, 0xd0, 0x3a, 0x88,
	0x8f, 0xb1, 0x67, 0x9b, 0x84, 0x98, 0xae, 0xb3, 0x8b, 0x1d, 0x13, 0x1b, 0x22, 0x7f, 0xe3, 0x2b,
	0xa8, 0x25, 0xc5, 0x05, 0x2d, 0x41, 0xb9, 0x7b, 0xd8, 0xef, 0x8a, 0x0b, 0xe1, 0x89, 0xf7, 0x9e,
	0xec, 0x75, 0x8e, 0xfa, 0xdd, 0xc3, 0x87, 0x22, 0x47, 0x37, 0x3c, 0xea, 0x74, 0xf6, 0x7a, 0x3d,
	0xb1, 0x14, 0xa2, 0x1e, 0x7c, 0xd9, 0xdd, 0x17, 0xf9, 0xd0, 0xdc, 0xef, 0x1e, 0xec, 0x3d, 0x3a,
	0xea, 0x8b, 0xe5, 0xed, 0x1f, 0xca, 0xd0, 0x38, 0xa0, 0xc4, 0xb2, 0x53, 0xf7, 0xb0, 0x77, 0x62,
	0xea, 0x18, 0xe1, 0x3c, 0x1d, 0xa8, 0x78, 0x16, 0x2b, 0x18, 0x8a, 0x9a, 0xd7, 0xe7, 0x40, 0x32,
	0xad, 0xc9, 0x0b, 0xe8, 0x59, 0x86, 0x63, 0x74, 0xa5, 0xd0, 0x73, 0x7a, 0xa6, 0x68, 0x5e, 0x3d,
	0x0f, 0x96, 0x44, 0x1f, 0xe4, 0x9e, 0x0c, 0x5d, 0x2b, 0x96, 0xd0, 0x4c, 0xff, 0x6e, 0xb6, 0xcf,
	0x07, 0x26, 0x7b, 0xe0, 0xbc, 0x0a, 0xce, 0x20, 0xaa, 0xa0, 0x01, 0x9e, 0x41, 0x54, 0x51, 0x03,
	0x93, 0x17, 0x90, 0x9a, 0x95, 0x16, 0xba, 0x3a, 0x5f, 0x4d, 0x69, 0x5e, 0x3b, 0x17, 0x17, 0x6f,
	0xb0, 0xf3, 0xc9, 0xd3, 0x3b, 0x23, 0xd3, 0x1f, 0x07, 0x83, 0x4d, 0xdd, 0xb5, 0xb7, 0x5e, 0x9a,
	0x96, 0x65, 0xbe, 0xf4, 0xb1, 0x3e, 0xde, 0x62, 0x11, 0x6e, 0x32, 0xdf, 0x2d, 0xdd, 0xf5, 0xf0,
	0x16, 0x8d, 0xb6, 0xc5, 0x2c, 0x93, 0xc1, 0xa0, 0x42, 0xd7, 0xb7, 0xfe, 0x0a, 0x00, 0x00, 0xff,
	0xff, 0x67, 0x49, 0xc1, 0x4a, 0xff, 0x12, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MilvusBackupServiceClient is the client API for MilvusBackupService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MilvusBackupServiceClient interface {
	// Create backup
	CreateBackup(ctx context.Context, in *CreateBackupRequest, opts ...grpc.CallOption) (*CreateBackupResponse, error)
	// Get backup with the chosen name
	GetBackup(ctx context.Context, in *GetBackupRequest, opts ...grpc.CallOption) (*GetBackupResponse, error)
	// List backups that contains the given collection name, if collection is not given, return all backups in the cluster
	ListBackups(ctx context.Context, in *ListBackupsRequest, opts ...grpc.CallOption) (*ListBackupsResponse, error)
	// Delete backup by given backup name
	DeleteBackup(ctx context.Context, in *DeleteBackupRequest, opts ...grpc.CallOption) (*DeleteBackupResponse, error)
	// Load backup to milvus, return backup load report
	LoadBackup(ctx context.Context, in *LoadBackupRequest, opts ...grpc.CallOption) (*LoadBackupResponse, error)
}

type milvusBackupServiceClient struct {
	cc *grpc.ClientConn
}

func NewMilvusBackupServiceClient(cc *grpc.ClientConn) MilvusBackupServiceClient {
	return &milvusBackupServiceClient{cc}
}

func (c *milvusBackupServiceClient) CreateBackup(ctx context.Context, in *CreateBackupRequest, opts ...grpc.CallOption) (*CreateBackupResponse, error) {
	out := new(CreateBackupResponse)
	err := c.cc.Invoke(ctx, "/milvus.proto.backup.MilvusBackupService/CreateBackup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *milvusBackupServiceClient) GetBackup(ctx context.Context, in *GetBackupRequest, opts ...grpc.CallOption) (*GetBackupResponse, error) {
	out := new(GetBackupResponse)
	err := c.cc.Invoke(ctx, "/milvus.proto.backup.MilvusBackupService/GetBackup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *milvusBackupServiceClient) ListBackups(ctx context.Context, in *ListBackupsRequest, opts ...grpc.CallOption) (*ListBackupsResponse, error) {
	out := new(ListBackupsResponse)
	err := c.cc.Invoke(ctx, "/milvus.proto.backup.MilvusBackupService/ListBackups", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *milvusBackupServiceClient) DeleteBackup(ctx context.Context, in *DeleteBackupRequest, opts ...grpc.CallOption) (*DeleteBackupResponse, error) {
	out := new(DeleteBackupResponse)
	err := c.cc.Invoke(ctx, "/milvus.proto.backup.MilvusBackupService/DeleteBackup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *milvusBackupServiceClient) LoadBackup(ctx context.Context, in *LoadBackupRequest, opts ...grpc.CallOption) (*LoadBackupResponse, error) {
	out := new(LoadBackupResponse)
	err := c.cc.Invoke(ctx, "/milvus.proto.backup.MilvusBackupService/LoadBackup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MilvusBackupServiceServer is the server API for MilvusBackupService service.
type MilvusBackupServiceServer interface {
	// Create backup
	CreateBackup(context.Context, *CreateBackupRequest) (*CreateBackupResponse, error)
	// Get backup with the chosen name
	GetBackup(context.Context, *GetBackupRequest) (*GetBackupResponse, error)
	// List backups that contains the given collection name, if collection is not given, return all backups in the cluster
	ListBackups(context.Context, *ListBackupsRequest) (*ListBackupsResponse, error)
	// Delete backup by given backup name
	DeleteBackup(context.Context, *DeleteBackupRequest) (*DeleteBackupResponse, error)
	// Load backup to milvus, return backup load report
	LoadBackup(context.Context, *LoadBackupRequest) (*LoadBackupResponse, error)
}

// UnimplementedMilvusBackupServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMilvusBackupServiceServer struct {
}

func (*UnimplementedMilvusBackupServiceServer) CreateBackup(ctx context.Context, req *CreateBackupRequest) (*CreateBackupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBackup not implemented")
}
func (*UnimplementedMilvusBackupServiceServer) GetBackup(ctx context.Context, req *GetBackupRequest) (*GetBackupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBackup not implemented")
}
func (*UnimplementedMilvusBackupServiceServer) ListBackups(ctx context.Context, req *ListBackupsRequest) (*ListBackupsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBackups not implemented")
}
func (*UnimplementedMilvusBackupServiceServer) DeleteBackup(ctx context.Context, req *DeleteBackupRequest) (*DeleteBackupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBackup not implemented")
}
func (*UnimplementedMilvusBackupServiceServer) LoadBackup(ctx context.Context, req *LoadBackupRequest) (*LoadBackupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadBackup not implemented")
}

func RegisterMilvusBackupServiceServer(s *grpc.Server, srv MilvusBackupServiceServer) {
	s.RegisterService(&_MilvusBackupService_serviceDesc, srv)
}

func _MilvusBackupService_CreateBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MilvusBackupServiceServer).CreateBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.proto.backup.MilvusBackupService/CreateBackup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MilvusBackupServiceServer).CreateBackup(ctx, req.(*CreateBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MilvusBackupService_GetBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MilvusBackupServiceServer).GetBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.proto.backup.MilvusBackupService/GetBackup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MilvusBackupServiceServer).GetBackup(ctx, req.(*GetBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MilvusBackupService_ListBackups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBackupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MilvusBackupServiceServer).ListBackups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.proto.backup.MilvusBackupService/ListBackups",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MilvusBackupServiceServer).ListBackups(ctx, req.(*ListBackupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MilvusBackupService_DeleteBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MilvusBackupServiceServer).DeleteBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.proto.backup.MilvusBackupService/DeleteBackup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MilvusBackupServiceServer).DeleteBackup(ctx, req.(*DeleteBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MilvusBackupService_LoadBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MilvusBackupServiceServer).LoadBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.proto.backup.MilvusBackupService/LoadBackup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MilvusBackupServiceServer).LoadBackup(ctx, req.(*LoadBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MilvusBackupService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "milvus.proto.backup.MilvusBackupService",
	HandlerType: (*MilvusBackupServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBackup",
			Handler:    _MilvusBackupService_CreateBackup_Handler,
		},
		{
			MethodName: "GetBackup",
			Handler:    _MilvusBackupService_GetBackup_Handler,
		},
		{
			MethodName: "ListBackups",
			Handler:    _MilvusBackupService_ListBackups_Handler,
		},
		{
			MethodName: "DeleteBackup",
			Handler:    _MilvusBackupService_DeleteBackup_Handler,
		},
		{
			MethodName: "LoadBackup",
			Handler:    _MilvusBackupService_LoadBackup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backup.proto",
}
