// Code generated by protoc-gen-go. DO NOT EDIT.
// source: backup.proto

package backuppb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResponseCode int32

const (
	ResponseCode_Success                  ResponseCode = 0
	ResponseCode_Not_Support              ResponseCode = 1
	ResponseCode_No_Permission            ResponseCode = 2
	ResponseCode_Fail                     ResponseCode = 3
	ResponseCode_Parameter_Error          ResponseCode = 400
	ResponseCode_Request_Object_Not_Found ResponseCode = 404
)

var ResponseCode_name = map[int32]string{
	0:   "Success",
	1:   "Not_Support",
	2:   "No_Permission",
	3:   "Fail",
	400: "Parameter_Error",
	404: "Request_Object_Not_Found",
}

var ResponseCode_value = map[string]int32{
	"Success":                  0,
	"Not_Support":              1,
	"No_Permission":            2,
	"Fail":                     3,
	"Parameter_Error":          400,
	"Request_Object_Not_Found": 404,
}

func (x ResponseCode) String() string {
	return proto.EnumName(ResponseCode_name, int32(x))
}

func (ResponseCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{0}
}

type BackupTaskStateCode int32

const (
	BackupTaskStateCode_BACKUP_INITIAL   BackupTaskStateCode = 0
	BackupTaskStateCode_BACKUP_EXECUTING BackupTaskStateCode = 1
	BackupTaskStateCode_BACKUP_SUCCESS   BackupTaskStateCode = 2
	BackupTaskStateCode_BACKUP_FAIL      BackupTaskStateCode = 3
	BackupTaskStateCode_BACKUP_TIMEOUT   BackupTaskStateCode = 4
)

var BackupTaskStateCode_name = map[int32]string{
	0: "BACKUP_INITIAL",
	1: "BACKUP_EXECUTING",
	2: "BACKUP_SUCCESS",
	3: "BACKUP_FAIL",
	4: "BACKUP_TIMEOUT",
}

var BackupTaskStateCode_value = map[string]int32{
	"BACKUP_INITIAL":   0,
	"BACKUP_EXECUTING": 1,
	"BACKUP_SUCCESS":   2,
	"BACKUP_FAIL":      3,
	"BACKUP_TIMEOUT":   4,
}

func (x BackupTaskStateCode) String() string {
	return proto.EnumName(BackupTaskStateCode_name, int32(x))
}

func (BackupTaskStateCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{1}
}

type RestoreTaskStateCode int32

const (
	RestoreTaskStateCode_INITIAL   RestoreTaskStateCode = 0
	RestoreTaskStateCode_EXECUTING RestoreTaskStateCode = 1
	RestoreTaskStateCode_SUCCESS   RestoreTaskStateCode = 2
	RestoreTaskStateCode_FAIL      RestoreTaskStateCode = 3
	RestoreTaskStateCode_TIMEOUT   RestoreTaskStateCode = 4
)

var RestoreTaskStateCode_name = map[int32]string{
	0: "INITIAL",
	1: "EXECUTING",
	2: "SUCCESS",
	3: "FAIL",
	4: "TIMEOUT",
}

var RestoreTaskStateCode_value = map[string]int32{
	"INITIAL":   0,
	"EXECUTING": 1,
	"SUCCESS":   2,
	"FAIL":      3,
	"TIMEOUT":   4,
}

func (x RestoreTaskStateCode) String() string {
	return proto.EnumName(RestoreTaskStateCode_name, int32(x))
}

func (RestoreTaskStateCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{2}
}

type ConsistencyLevel int32

const (
	ConsistencyLevel_Strong     ConsistencyLevel = 0
	ConsistencyLevel_Session    ConsistencyLevel = 1
	ConsistencyLevel_Bounded    ConsistencyLevel = 2
	ConsistencyLevel_Eventually ConsistencyLevel = 3
	ConsistencyLevel_Customized ConsistencyLevel = 4
)

var ConsistencyLevel_name = map[int32]string{
	0: "Strong",
	1: "Session",
	2: "Bounded",
	3: "Eventually",
	4: "Customized",
}

var ConsistencyLevel_value = map[string]int32{
	"Strong":     0,
	"Session":    1,
	"Bounded":    2,
	"Eventually": 3,
	"Customized": 4,
}

func (x ConsistencyLevel) String() string {
	return proto.EnumName(ConsistencyLevel_name, int32(x))
}

func (ConsistencyLevel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{3}
}

//*
// @brief Field data type
type DataType int32

const (
	DataType_None         DataType = 0
	DataType_Bool         DataType = 1
	DataType_Int8         DataType = 2
	DataType_Int16        DataType = 3
	DataType_Int32        DataType = 4
	DataType_Int64        DataType = 5
	DataType_Float        DataType = 10
	DataType_Double       DataType = 11
	DataType_String       DataType = 20
	DataType_VarChar      DataType = 21
	DataType_BinaryVector DataType = 100
	DataType_FloatVector  DataType = 101
)

var DataType_name = map[int32]string{
	0:   "None",
	1:   "Bool",
	2:   "Int8",
	3:   "Int16",
	4:   "Int32",
	5:   "Int64",
	10:  "Float",
	11:  "Double",
	20:  "String",
	21:  "VarChar",
	100: "BinaryVector",
	101: "FloatVector",
}

var DataType_value = map[string]int32{
	"None":         0,
	"Bool":         1,
	"Int8":         2,
	"Int16":        3,
	"Int32":        4,
	"Int64":        5,
	"Float":        10,
	"Double":       11,
	"String":       20,
	"VarChar":      21,
	"BinaryVector": 100,
	"FloatVector":  101,
}

func (x DataType) String() string {
	return proto.EnumName(DataType_name, int32(x))
}

func (DataType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{4}
}

type FieldState int32

const (
	FieldState_FieldCreated  FieldState = 0
	FieldState_FieldCreating FieldState = 1
	FieldState_FieldDropping FieldState = 2
	FieldState_FieldDropped  FieldState = 3
)

var FieldState_name = map[int32]string{
	0: "FieldCreated",
	1: "FieldCreating",
	2: "FieldDropping",
	3: "FieldDropped",
}

var FieldState_value = map[string]int32{
	"FieldCreated":  0,
	"FieldCreating": 1,
	"FieldDropping": 2,
	"FieldDropped":  3,
}

func (x FieldState) String() string {
	return proto.EnumName(FieldState_name, int32(x))
}

func (FieldState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{5}
}

//*
// lite version of Collection info
type CollectionBackupInfo struct {
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StateCode            BackupTaskStateCode    `protobuf:"varint,2,opt,name=state_code,json=stateCode,proto3,enum=milvus.proto.backup.BackupTaskStateCode" json:"state_code,omitempty"`
	ErrorMessage         string                 `protobuf:"bytes,3,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	StartTime            int64                  `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              int64                  `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Progress             int32                  `protobuf:"varint,6,opt,name=progress,proto3" json:"progress,omitempty"`
	CollectionId         int64                  `protobuf:"varint,7,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	DbName               string                 `protobuf:"bytes,8,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	CollectionName       string                 `protobuf:"bytes,9,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	Schema               *CollectionSchema      `protobuf:"bytes,10,opt,name=schema,proto3" json:"schema,omitempty"`
	ShardsNum            int32                  `protobuf:"varint,11,opt,name=shards_num,json=shardsNum,proto3" json:"shards_num,omitempty"`
	ConsistencyLevel     ConsistencyLevel       `protobuf:"varint,12,opt,name=consistency_level,json=consistencyLevel,proto3,enum=milvus.proto.backup.ConsistencyLevel" json:"consistency_level,omitempty"`
	PartitionBackups     []*PartitionBackupInfo `protobuf:"bytes,13,rep,name=partition_backups,json=partitionBackups,proto3" json:"partition_backups,omitempty"`
	BackupTimestamp      uint64                 `protobuf:"varint,14,opt,name=backup_timestamp,json=backupTimestamp,proto3" json:"backup_timestamp,omitempty"`
	Size                 int64                  `protobuf:"varint,15,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *CollectionBackupInfo) Reset()         { *m = CollectionBackupInfo{} }
func (m *CollectionBackupInfo) String() string { return proto.CompactTextString(m) }
func (*CollectionBackupInfo) ProtoMessage()    {}
func (*CollectionBackupInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{0}
}

func (m *CollectionBackupInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectionBackupInfo.Unmarshal(m, b)
}
func (m *CollectionBackupInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectionBackupInfo.Marshal(b, m, deterministic)
}
func (m *CollectionBackupInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectionBackupInfo.Merge(m, src)
}
func (m *CollectionBackupInfo) XXX_Size() int {
	return xxx_messageInfo_CollectionBackupInfo.Size(m)
}
func (m *CollectionBackupInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectionBackupInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CollectionBackupInfo proto.InternalMessageInfo

func (m *CollectionBackupInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CollectionBackupInfo) GetStateCode() BackupTaskStateCode {
	if m != nil {
		return m.StateCode
	}
	return BackupTaskStateCode_BACKUP_INITIAL
}

func (m *CollectionBackupInfo) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *CollectionBackupInfo) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *CollectionBackupInfo) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *CollectionBackupInfo) GetProgress() int32 {
	if m != nil {
		return m.Progress
	}
	return 0
}

func (m *CollectionBackupInfo) GetCollectionId() int64 {
	if m != nil {
		return m.CollectionId
	}
	return 0
}

func (m *CollectionBackupInfo) GetDbName() string {
	if m != nil {
		return m.DbName
	}
	return ""
}

func (m *CollectionBackupInfo) GetCollectionName() string {
	if m != nil {
		return m.CollectionName
	}
	return ""
}

func (m *CollectionBackupInfo) GetSchema() *CollectionSchema {
	if m != nil {
		return m.Schema
	}
	return nil
}

func (m *CollectionBackupInfo) GetShardsNum() int32 {
	if m != nil {
		return m.ShardsNum
	}
	return 0
}

func (m *CollectionBackupInfo) GetConsistencyLevel() ConsistencyLevel {
	if m != nil {
		return m.ConsistencyLevel
	}
	return ConsistencyLevel_Strong
}

func (m *CollectionBackupInfo) GetPartitionBackups() []*PartitionBackupInfo {
	if m != nil {
		return m.PartitionBackups
	}
	return nil
}

func (m *CollectionBackupInfo) GetBackupTimestamp() uint64 {
	if m != nil {
		return m.BackupTimestamp
	}
	return 0
}

func (m *CollectionBackupInfo) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type PartitionBackupInfo struct {
	PartitionId   int64  `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	PartitionName string `protobuf:"bytes,2,opt,name=partition_name,json=partitionName,proto3" json:"partition_name,omitempty"`
	CollectionId  int64  `protobuf:"varint,3,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	// array of segment backup
	SegmentBackups       []*SegmentBackupInfo `protobuf:"bytes,7,rep,name=segment_backups,json=segmentBackups,proto3" json:"segment_backups,omitempty"`
	Size                 int64                `protobuf:"varint,8,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PartitionBackupInfo) Reset()         { *m = PartitionBackupInfo{} }
func (m *PartitionBackupInfo) String() string { return proto.CompactTextString(m) }
func (*PartitionBackupInfo) ProtoMessage()    {}
func (*PartitionBackupInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{1}
}

func (m *PartitionBackupInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartitionBackupInfo.Unmarshal(m, b)
}
func (m *PartitionBackupInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartitionBackupInfo.Marshal(b, m, deterministic)
}
func (m *PartitionBackupInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartitionBackupInfo.Merge(m, src)
}
func (m *PartitionBackupInfo) XXX_Size() int {
	return xxx_messageInfo_PartitionBackupInfo.Size(m)
}
func (m *PartitionBackupInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PartitionBackupInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PartitionBackupInfo proto.InternalMessageInfo

func (m *PartitionBackupInfo) GetPartitionId() int64 {
	if m != nil {
		return m.PartitionId
	}
	return 0
}

func (m *PartitionBackupInfo) GetPartitionName() string {
	if m != nil {
		return m.PartitionName
	}
	return ""
}

func (m *PartitionBackupInfo) GetCollectionId() int64 {
	if m != nil {
		return m.CollectionId
	}
	return 0
}

func (m *PartitionBackupInfo) GetSegmentBackups() []*SegmentBackupInfo {
	if m != nil {
		return m.SegmentBackups
	}
	return nil
}

func (m *PartitionBackupInfo) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

//*
// lite version of datapb.SegmentInfo
type SegmentBackupInfo struct {
	SegmentId            int64          `protobuf:"varint,1,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	CollectionId         int64          `protobuf:"varint,2,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	PartitionId          int64          `protobuf:"varint,3,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	NumOfRows            int64          `protobuf:"varint,4,opt,name=num_of_rows,json=numOfRows,proto3" json:"num_of_rows,omitempty"`
	Binlogs              []*FieldBinlog `protobuf:"bytes,5,rep,name=binlogs,proto3" json:"binlogs,omitempty"`
	Statslogs            []*FieldBinlog `protobuf:"bytes,6,rep,name=statslogs,proto3" json:"statslogs,omitempty"`
	Deltalogs            []*FieldBinlog `protobuf:"bytes,7,rep,name=deltalogs,proto3" json:"deltalogs,omitempty"`
	Size                 int64          `protobuf:"varint,8,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SegmentBackupInfo) Reset()         { *m = SegmentBackupInfo{} }
func (m *SegmentBackupInfo) String() string { return proto.CompactTextString(m) }
func (*SegmentBackupInfo) ProtoMessage()    {}
func (*SegmentBackupInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{2}
}

func (m *SegmentBackupInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SegmentBackupInfo.Unmarshal(m, b)
}
func (m *SegmentBackupInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SegmentBackupInfo.Marshal(b, m, deterministic)
}
func (m *SegmentBackupInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SegmentBackupInfo.Merge(m, src)
}
func (m *SegmentBackupInfo) XXX_Size() int {
	return xxx_messageInfo_SegmentBackupInfo.Size(m)
}
func (m *SegmentBackupInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SegmentBackupInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SegmentBackupInfo proto.InternalMessageInfo

func (m *SegmentBackupInfo) GetSegmentId() int64 {
	if m != nil {
		return m.SegmentId
	}
	return 0
}

func (m *SegmentBackupInfo) GetCollectionId() int64 {
	if m != nil {
		return m.CollectionId
	}
	return 0
}

func (m *SegmentBackupInfo) GetPartitionId() int64 {
	if m != nil {
		return m.PartitionId
	}
	return 0
}

func (m *SegmentBackupInfo) GetNumOfRows() int64 {
	if m != nil {
		return m.NumOfRows
	}
	return 0
}

func (m *SegmentBackupInfo) GetBinlogs() []*FieldBinlog {
	if m != nil {
		return m.Binlogs
	}
	return nil
}

func (m *SegmentBackupInfo) GetStatslogs() []*FieldBinlog {
	if m != nil {
		return m.Statslogs
	}
	return nil
}

func (m *SegmentBackupInfo) GetDeltalogs() []*FieldBinlog {
	if m != nil {
		return m.Deltalogs
	}
	return nil
}

func (m *SegmentBackupInfo) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

//*
// root of backup
type BackupInfo struct {
	Id           string              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StateCode    BackupTaskStateCode `protobuf:"varint,2,opt,name=state_code,json=stateCode,proto3,enum=milvus.proto.backup.BackupTaskStateCode" json:"state_code,omitempty"`
	ErrorMessage string              `protobuf:"bytes,3,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	StartTime    int64               `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime      int64               `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Progress     int32               `protobuf:"varint,6,opt,name=progress,proto3" json:"progress,omitempty"`
	Name         string              `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	// backup timestamp
	BackupTimestamp uint64 `protobuf:"varint,8,opt,name=backup_timestamp,json=backupTimestamp,proto3" json:"backup_timestamp,omitempty"`
	// array of collection backup
	CollectionBackups    []*CollectionBackupInfo `protobuf:"bytes,9,rep,name=collection_backups,json=collectionBackups,proto3" json:"collection_backups,omitempty"`
	Size                 int64                   `protobuf:"varint,10,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *BackupInfo) Reset()         { *m = BackupInfo{} }
func (m *BackupInfo) String() string { return proto.CompactTextString(m) }
func (*BackupInfo) ProtoMessage()    {}
func (*BackupInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{3}
}

func (m *BackupInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackupInfo.Unmarshal(m, b)
}
func (m *BackupInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackupInfo.Marshal(b, m, deterministic)
}
func (m *BackupInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackupInfo.Merge(m, src)
}
func (m *BackupInfo) XXX_Size() int {
	return xxx_messageInfo_BackupInfo.Size(m)
}
func (m *BackupInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BackupInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BackupInfo proto.InternalMessageInfo

func (m *BackupInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *BackupInfo) GetStateCode() BackupTaskStateCode {
	if m != nil {
		return m.StateCode
	}
	return BackupTaskStateCode_BACKUP_INITIAL
}

func (m *BackupInfo) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *BackupInfo) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *BackupInfo) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *BackupInfo) GetProgress() int32 {
	if m != nil {
		return m.Progress
	}
	return 0
}

func (m *BackupInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BackupInfo) GetBackupTimestamp() uint64 {
	if m != nil {
		return m.BackupTimestamp
	}
	return 0
}

func (m *BackupInfo) GetCollectionBackups() []*CollectionBackupInfo {
	if m != nil {
		return m.CollectionBackups
	}
	return nil
}

func (m *BackupInfo) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

//*
// For level storage
type CollectionLevelBackupInfo struct {
	Infos                []*CollectionBackupInfo `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *CollectionLevelBackupInfo) Reset()         { *m = CollectionLevelBackupInfo{} }
func (m *CollectionLevelBackupInfo) String() string { return proto.CompactTextString(m) }
func (*CollectionLevelBackupInfo) ProtoMessage()    {}
func (*CollectionLevelBackupInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{4}
}

func (m *CollectionLevelBackupInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectionLevelBackupInfo.Unmarshal(m, b)
}
func (m *CollectionLevelBackupInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectionLevelBackupInfo.Marshal(b, m, deterministic)
}
func (m *CollectionLevelBackupInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectionLevelBackupInfo.Merge(m, src)
}
func (m *CollectionLevelBackupInfo) XXX_Size() int {
	return xxx_messageInfo_CollectionLevelBackupInfo.Size(m)
}
func (m *CollectionLevelBackupInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectionLevelBackupInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CollectionLevelBackupInfo proto.InternalMessageInfo

func (m *CollectionLevelBackupInfo) GetInfos() []*CollectionBackupInfo {
	if m != nil {
		return m.Infos
	}
	return nil
}

//*
// For level storage
type PartitionLevelBackupInfo struct {
	Infos                []*PartitionBackupInfo `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *PartitionLevelBackupInfo) Reset()         { *m = PartitionLevelBackupInfo{} }
func (m *PartitionLevelBackupInfo) String() string { return proto.CompactTextString(m) }
func (*PartitionLevelBackupInfo) ProtoMessage()    {}
func (*PartitionLevelBackupInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{5}
}

func (m *PartitionLevelBackupInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartitionLevelBackupInfo.Unmarshal(m, b)
}
func (m *PartitionLevelBackupInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartitionLevelBackupInfo.Marshal(b, m, deterministic)
}
func (m *PartitionLevelBackupInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartitionLevelBackupInfo.Merge(m, src)
}
func (m *PartitionLevelBackupInfo) XXX_Size() int {
	return xxx_messageInfo_PartitionLevelBackupInfo.Size(m)
}
func (m *PartitionLevelBackupInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PartitionLevelBackupInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PartitionLevelBackupInfo proto.InternalMessageInfo

func (m *PartitionLevelBackupInfo) GetInfos() []*PartitionBackupInfo {
	if m != nil {
		return m.Infos
	}
	return nil
}

//*
// For level storage
type SegmentLevelBackupInfo struct {
	Infos                []*SegmentBackupInfo `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SegmentLevelBackupInfo) Reset()         { *m = SegmentLevelBackupInfo{} }
func (m *SegmentLevelBackupInfo) String() string { return proto.CompactTextString(m) }
func (*SegmentLevelBackupInfo) ProtoMessage()    {}
func (*SegmentLevelBackupInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{6}
}

func (m *SegmentLevelBackupInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SegmentLevelBackupInfo.Unmarshal(m, b)
}
func (m *SegmentLevelBackupInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SegmentLevelBackupInfo.Marshal(b, m, deterministic)
}
func (m *SegmentLevelBackupInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SegmentLevelBackupInfo.Merge(m, src)
}
func (m *SegmentLevelBackupInfo) XXX_Size() int {
	return xxx_messageInfo_SegmentLevelBackupInfo.Size(m)
}
func (m *SegmentLevelBackupInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SegmentLevelBackupInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SegmentLevelBackupInfo proto.InternalMessageInfo

func (m *SegmentLevelBackupInfo) GetInfos() []*SegmentBackupInfo {
	if m != nil {
		return m.Infos
	}
	return nil
}

//*
// Create Backup in milvus
type CreateBackupRequest struct {
	// uuid of request, will generate one if not set
	RequestId string `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	// backup name, will generate one if not set
	BackupName string `protobuf:"bytes,2,opt,name=backup_name,json=backupName,proto3" json:"backup_name,omitempty"`
	// collection names to backup, empty to backup all
	CollectionNames []string `protobuf:"bytes,3,rep,name=collection_names,json=collectionNames,proto3" json:"collection_names,omitempty"`
	// async or not
	Async                bool     `protobuf:"varint,4,opt,name=async,proto3" json:"async,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBackupRequest) Reset()         { *m = CreateBackupRequest{} }
func (m *CreateBackupRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBackupRequest) ProtoMessage()    {}
func (*CreateBackupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{7}
}

func (m *CreateBackupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBackupRequest.Unmarshal(m, b)
}
func (m *CreateBackupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBackupRequest.Marshal(b, m, deterministic)
}
func (m *CreateBackupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBackupRequest.Merge(m, src)
}
func (m *CreateBackupRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBackupRequest.Size(m)
}
func (m *CreateBackupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBackupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBackupRequest proto.InternalMessageInfo

func (m *CreateBackupRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *CreateBackupRequest) GetBackupName() string {
	if m != nil {
		return m.BackupName
	}
	return ""
}

func (m *CreateBackupRequest) GetCollectionNames() []string {
	if m != nil {
		return m.CollectionNames
	}
	return nil
}

func (m *CreateBackupRequest) GetAsync() bool {
	if m != nil {
		return m.Async
	}
	return false
}

//*
// BackupInfoResponse
type BackupInfoResponse struct {
	// uuid of the request to response
	RequestId string `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	// response code. 0 means success. others are fail
	Code ResponseCode `protobuf:"varint,2,opt,name=code,proto3,enum=milvus.proto.backup.ResponseCode" json:"code,omitempty"`
	// error msg if fail
	Msg string `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	// backup info entity
	Data                 *BackupInfo `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *BackupInfoResponse) Reset()         { *m = BackupInfoResponse{} }
func (m *BackupInfoResponse) String() string { return proto.CompactTextString(m) }
func (*BackupInfoResponse) ProtoMessage()    {}
func (*BackupInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{8}
}

func (m *BackupInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackupInfoResponse.Unmarshal(m, b)
}
func (m *BackupInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackupInfoResponse.Marshal(b, m, deterministic)
}
func (m *BackupInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackupInfoResponse.Merge(m, src)
}
func (m *BackupInfoResponse) XXX_Size() int {
	return xxx_messageInfo_BackupInfoResponse.Size(m)
}
func (m *BackupInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BackupInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BackupInfoResponse proto.InternalMessageInfo

func (m *BackupInfoResponse) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *BackupInfoResponse) GetCode() ResponseCode {
	if m != nil {
		return m.Code
	}
	return ResponseCode_Success
}

func (m *BackupInfoResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *BackupInfoResponse) GetData() *BackupInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetBackupRequest struct {
	// uuid of request, will generate one if not set
	RequestId string `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	// backup name to query, backup_name or backup_id is needed
	BackupName string `protobuf:"bytes,2,opt,name=backup_name,json=backupName,proto3" json:"backup_name,omitempty"`
	// backup to query
	BackupId string `protobuf:"bytes,3,opt,name=backup_id,json=backupId,proto3" json:"backup_id,omitempty"`
	// if bucket_name and path is set. will override bucket/path in config.
	BucketName string `protobuf:"bytes,4,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	// if bucket_name and path is set. will override bucket/path in config.
	Path                 string   `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBackupRequest) Reset()         { *m = GetBackupRequest{} }
func (m *GetBackupRequest) String() string { return proto.CompactTextString(m) }
func (*GetBackupRequest) ProtoMessage()    {}
func (*GetBackupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{9}
}

func (m *GetBackupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBackupRequest.Unmarshal(m, b)
}
func (m *GetBackupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBackupRequest.Marshal(b, m, deterministic)
}
func (m *GetBackupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBackupRequest.Merge(m, src)
}
func (m *GetBackupRequest) XXX_Size() int {
	return xxx_messageInfo_GetBackupRequest.Size(m)
}
func (m *GetBackupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBackupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBackupRequest proto.InternalMessageInfo

func (m *GetBackupRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *GetBackupRequest) GetBackupName() string {
	if m != nil {
		return m.BackupName
	}
	return ""
}

func (m *GetBackupRequest) GetBackupId() string {
	if m != nil {
		return m.BackupId
	}
	return ""
}

func (m *GetBackupRequest) GetBucketName() string {
	if m != nil {
		return m.BucketName
	}
	return ""
}

func (m *GetBackupRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type ListBackupsRequest struct {
	// uuid of request, will generate one if not set
	RequestId string `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	// if collection_name is set, will only return backups contains this collection
	CollectionName       string   `protobuf:"bytes,2,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBackupsRequest) Reset()         { *m = ListBackupsRequest{} }
func (m *ListBackupsRequest) String() string { return proto.CompactTextString(m) }
func (*ListBackupsRequest) ProtoMessage()    {}
func (*ListBackupsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{10}
}

func (m *ListBackupsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBackupsRequest.Unmarshal(m, b)
}
func (m *ListBackupsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBackupsRequest.Marshal(b, m, deterministic)
}
func (m *ListBackupsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBackupsRequest.Merge(m, src)
}
func (m *ListBackupsRequest) XXX_Size() int {
	return xxx_messageInfo_ListBackupsRequest.Size(m)
}
func (m *ListBackupsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBackupsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListBackupsRequest proto.InternalMessageInfo

func (m *ListBackupsRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *ListBackupsRequest) GetCollectionName() string {
	if m != nil {
		return m.CollectionName
	}
	return ""
}

type ListBackupsResponse struct {
	// uuid of the request to response
	RequestId string `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	// response code. 0 means success. others are fail
	Code ResponseCode `protobuf:"varint,2,opt,name=code,proto3,enum=milvus.proto.backup.ResponseCode" json:"code,omitempty"`
	// error msg if fail
	Msg string `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	// backup info entities
	Data                 []*BackupInfo `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListBackupsResponse) Reset()         { *m = ListBackupsResponse{} }
func (m *ListBackupsResponse) String() string { return proto.CompactTextString(m) }
func (*ListBackupsResponse) ProtoMessage()    {}
func (*ListBackupsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{11}
}

func (m *ListBackupsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBackupsResponse.Unmarshal(m, b)
}
func (m *ListBackupsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBackupsResponse.Marshal(b, m, deterministic)
}
func (m *ListBackupsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBackupsResponse.Merge(m, src)
}
func (m *ListBackupsResponse) XXX_Size() int {
	return xxx_messageInfo_ListBackupsResponse.Size(m)
}
func (m *ListBackupsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBackupsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListBackupsResponse proto.InternalMessageInfo

func (m *ListBackupsResponse) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *ListBackupsResponse) GetCode() ResponseCode {
	if m != nil {
		return m.Code
	}
	return ResponseCode_Success
}

func (m *ListBackupsResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ListBackupsResponse) GetData() []*BackupInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

type DeleteBackupRequest struct {
	// uuid of request, will generate one if not set
	RequestId string `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	// backup name
	BackupName           string   `protobuf:"bytes,2,opt,name=backup_name,json=backupName,proto3" json:"backup_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBackupRequest) Reset()         { *m = DeleteBackupRequest{} }
func (m *DeleteBackupRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteBackupRequest) ProtoMessage()    {}
func (*DeleteBackupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{12}
}

func (m *DeleteBackupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBackupRequest.Unmarshal(m, b)
}
func (m *DeleteBackupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBackupRequest.Marshal(b, m, deterministic)
}
func (m *DeleteBackupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBackupRequest.Merge(m, src)
}
func (m *DeleteBackupRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteBackupRequest.Size(m)
}
func (m *DeleteBackupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBackupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBackupRequest proto.InternalMessageInfo

func (m *DeleteBackupRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *DeleteBackupRequest) GetBackupName() string {
	if m != nil {
		return m.BackupName
	}
	return ""
}

type DeleteBackupResponse struct {
	// uuid of the request to response
	RequestId string `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	// response code. 0 means success. others are fail
	Code ResponseCode `protobuf:"varint,2,opt,name=code,proto3,enum=milvus.proto.backup.ResponseCode" json:"code,omitempty"`
	// error msg if fail
	Msg                  string   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBackupResponse) Reset()         { *m = DeleteBackupResponse{} }
func (m *DeleteBackupResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteBackupResponse) ProtoMessage()    {}
func (*DeleteBackupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{13}
}

func (m *DeleteBackupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBackupResponse.Unmarshal(m, b)
}
func (m *DeleteBackupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBackupResponse.Marshal(b, m, deterministic)
}
func (m *DeleteBackupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBackupResponse.Merge(m, src)
}
func (m *DeleteBackupResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteBackupResponse.Size(m)
}
func (m *DeleteBackupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBackupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBackupResponse proto.InternalMessageInfo

func (m *DeleteBackupResponse) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *DeleteBackupResponse) GetCode() ResponseCode {
	if m != nil {
		return m.Code
	}
	return ResponseCode_Success
}

func (m *DeleteBackupResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type RestoreBackupRequest struct {
	// uuid of request, will generate one if not set
	RequestId string `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	// backup name to restore
	BackupName string `protobuf:"bytes,2,opt,name=backup_name,json=backupName,proto3" json:"backup_name,omitempty"`
	// collections to restore
	CollectionNames []string `protobuf:"bytes,3,rep,name=collection_names,json=collectionNames,proto3" json:"collection_names,omitempty"`
	// Support two ways to rename the collections while recover
	// 1, set a suffix
	CollectionSuffix string `protobuf:"bytes,4,opt,name=collection_suffix,json=collectionSuffix,proto3" json:"collection_suffix,omitempty"`
	// 2, give a map to rename the collections, if not given, use the original name.
	// collection_renames has higher priority than collection_suffix
	CollectionRenames map[string]string `protobuf:"bytes,5,rep,name=collection_renames,json=collectionRenames,proto3" json:"collection_renames,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// execute asynchronously or not
	Async bool `protobuf:"varint,6,opt,name=async,proto3" json:"async,omitempty"`
	// if bucket_name and path is set. will override bucket/path in config.
	BucketName string `protobuf:"bytes,7,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	// if bucket_name and path is set. will override bucket/path in config.
	Path                 string   `protobuf:"bytes,8,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestoreBackupRequest) Reset()         { *m = RestoreBackupRequest{} }
func (m *RestoreBackupRequest) String() string { return proto.CompactTextString(m) }
func (*RestoreBackupRequest) ProtoMessage()    {}
func (*RestoreBackupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{14}
}

func (m *RestoreBackupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestoreBackupRequest.Unmarshal(m, b)
}
func (m *RestoreBackupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestoreBackupRequest.Marshal(b, m, deterministic)
}
func (m *RestoreBackupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestoreBackupRequest.Merge(m, src)
}
func (m *RestoreBackupRequest) XXX_Size() int {
	return xxx_messageInfo_RestoreBackupRequest.Size(m)
}
func (m *RestoreBackupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RestoreBackupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RestoreBackupRequest proto.InternalMessageInfo

func (m *RestoreBackupRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *RestoreBackupRequest) GetBackupName() string {
	if m != nil {
		return m.BackupName
	}
	return ""
}

func (m *RestoreBackupRequest) GetCollectionNames() []string {
	if m != nil {
		return m.CollectionNames
	}
	return nil
}

func (m *RestoreBackupRequest) GetCollectionSuffix() string {
	if m != nil {
		return m.CollectionSuffix
	}
	return ""
}

func (m *RestoreBackupRequest) GetCollectionRenames() map[string]string {
	if m != nil {
		return m.CollectionRenames
	}
	return nil
}

func (m *RestoreBackupRequest) GetAsync() bool {
	if m != nil {
		return m.Async
	}
	return false
}

func (m *RestoreBackupRequest) GetBucketName() string {
	if m != nil {
		return m.BucketName
	}
	return ""
}

func (m *RestoreBackupRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type RestorePartitionTask struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StateCode            RestoreTaskStateCode `protobuf:"varint,2,opt,name=state_code,json=stateCode,proto3,enum=milvus.proto.backup.RestoreTaskStateCode" json:"state_code,omitempty"`
	ErrorMessage         string               `protobuf:"bytes,3,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	StartTime            int64                `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              int64                `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Progress             int32                `protobuf:"varint,6,opt,name=progress,proto3" json:"progress,omitempty"`
	PartBackup           *PartitionBackupInfo `protobuf:"bytes,7,opt,name=part_backup,json=partBackup,proto3" json:"part_backup,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RestorePartitionTask) Reset()         { *m = RestorePartitionTask{} }
func (m *RestorePartitionTask) String() string { return proto.CompactTextString(m) }
func (*RestorePartitionTask) ProtoMessage()    {}
func (*RestorePartitionTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{15}
}

func (m *RestorePartitionTask) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestorePartitionTask.Unmarshal(m, b)
}
func (m *RestorePartitionTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestorePartitionTask.Marshal(b, m, deterministic)
}
func (m *RestorePartitionTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestorePartitionTask.Merge(m, src)
}
func (m *RestorePartitionTask) XXX_Size() int {
	return xxx_messageInfo_RestorePartitionTask.Size(m)
}
func (m *RestorePartitionTask) XXX_DiscardUnknown() {
	xxx_messageInfo_RestorePartitionTask.DiscardUnknown(m)
}

var xxx_messageInfo_RestorePartitionTask proto.InternalMessageInfo

func (m *RestorePartitionTask) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RestorePartitionTask) GetStateCode() RestoreTaskStateCode {
	if m != nil {
		return m.StateCode
	}
	return RestoreTaskStateCode_INITIAL
}

func (m *RestorePartitionTask) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *RestorePartitionTask) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *RestorePartitionTask) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *RestorePartitionTask) GetProgress() int32 {
	if m != nil {
		return m.Progress
	}
	return 0
}

func (m *RestorePartitionTask) GetPartBackup() *PartitionBackupInfo {
	if m != nil {
		return m.PartBackup
	}
	return nil
}

type RestoreCollectionTask struct {
	Id                    string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StateCode             RestoreTaskStateCode    `protobuf:"varint,2,opt,name=state_code,json=stateCode,proto3,enum=milvus.proto.backup.RestoreTaskStateCode" json:"state_code,omitempty"`
	ErrorMessage          string                  `protobuf:"bytes,3,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	StartTime             int64                   `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime               int64                   `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	CollBackup            *CollectionBackupInfo   `protobuf:"bytes,6,opt,name=coll_backup,json=collBackup,proto3" json:"coll_backup,omitempty"`
	TargetCollectionName  string                  `protobuf:"bytes,7,opt,name=target_collection_name,json=targetCollectionName,proto3" json:"target_collection_name,omitempty"`
	PartitionRestoreTasks []*RestorePartitionTask `protobuf:"bytes,8,rep,name=partition_restore_tasks,json=partitionRestoreTasks,proto3" json:"partition_restore_tasks,omitempty"`
	RestoredSize          int64                   `protobuf:"varint,9,opt,name=restored_size,json=restoredSize,proto3" json:"restored_size,omitempty"`
	ToRestoreSize         int64                   `protobuf:"varint,10,opt,name=to_restore_size,json=toRestoreSize,proto3" json:"to_restore_size,omitempty"`
	Progress              int32                   `protobuf:"varint,11,opt,name=progress,proto3" json:"progress,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                `json:"-"`
	XXX_unrecognized      []byte                  `json:"-"`
	XXX_sizecache         int32                   `json:"-"`
}

func (m *RestoreCollectionTask) Reset()         { *m = RestoreCollectionTask{} }
func (m *RestoreCollectionTask) String() string { return proto.CompactTextString(m) }
func (*RestoreCollectionTask) ProtoMessage()    {}
func (*RestoreCollectionTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{16}
}

func (m *RestoreCollectionTask) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestoreCollectionTask.Unmarshal(m, b)
}
func (m *RestoreCollectionTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestoreCollectionTask.Marshal(b, m, deterministic)
}
func (m *RestoreCollectionTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestoreCollectionTask.Merge(m, src)
}
func (m *RestoreCollectionTask) XXX_Size() int {
	return xxx_messageInfo_RestoreCollectionTask.Size(m)
}
func (m *RestoreCollectionTask) XXX_DiscardUnknown() {
	xxx_messageInfo_RestoreCollectionTask.DiscardUnknown(m)
}

var xxx_messageInfo_RestoreCollectionTask proto.InternalMessageInfo

func (m *RestoreCollectionTask) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RestoreCollectionTask) GetStateCode() RestoreTaskStateCode {
	if m != nil {
		return m.StateCode
	}
	return RestoreTaskStateCode_INITIAL
}

func (m *RestoreCollectionTask) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *RestoreCollectionTask) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *RestoreCollectionTask) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *RestoreCollectionTask) GetCollBackup() *CollectionBackupInfo {
	if m != nil {
		return m.CollBackup
	}
	return nil
}

func (m *RestoreCollectionTask) GetTargetCollectionName() string {
	if m != nil {
		return m.TargetCollectionName
	}
	return ""
}

func (m *RestoreCollectionTask) GetPartitionRestoreTasks() []*RestorePartitionTask {
	if m != nil {
		return m.PartitionRestoreTasks
	}
	return nil
}

func (m *RestoreCollectionTask) GetRestoredSize() int64 {
	if m != nil {
		return m.RestoredSize
	}
	return 0
}

func (m *RestoreCollectionTask) GetToRestoreSize() int64 {
	if m != nil {
		return m.ToRestoreSize
	}
	return 0
}

func (m *RestoreCollectionTask) GetProgress() int32 {
	if m != nil {
		return m.Progress
	}
	return 0
}

type RestoreBackupTask struct {
	Id                     string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StateCode              RestoreTaskStateCode     `protobuf:"varint,2,opt,name=state_code,json=stateCode,proto3,enum=milvus.proto.backup.RestoreTaskStateCode" json:"state_code,omitempty"`
	ErrorMessage           string                   `protobuf:"bytes,3,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	StartTime              int64                    `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime                int64                    `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	CollectionRestoreTasks []*RestoreCollectionTask `protobuf:"bytes,6,rep,name=collection_restore_tasks,json=collectionRestoreTasks,proto3" json:"collection_restore_tasks,omitempty"`
	RestoredSize           int64                    `protobuf:"varint,7,opt,name=restored_size,json=restoredSize,proto3" json:"restored_size,omitempty"`
	ToRestoreSize          int64                    `protobuf:"varint,8,opt,name=to_restore_size,json=toRestoreSize,proto3" json:"to_restore_size,omitempty"`
	Progress               int32                    `protobuf:"varint,9,opt,name=progress,proto3" json:"progress,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                 `json:"-"`
	XXX_unrecognized       []byte                   `json:"-"`
	XXX_sizecache          int32                    `json:"-"`
}

func (m *RestoreBackupTask) Reset()         { *m = RestoreBackupTask{} }
func (m *RestoreBackupTask) String() string { return proto.CompactTextString(m) }
func (*RestoreBackupTask) ProtoMessage()    {}
func (*RestoreBackupTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{17}
}

func (m *RestoreBackupTask) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestoreBackupTask.Unmarshal(m, b)
}
func (m *RestoreBackupTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestoreBackupTask.Marshal(b, m, deterministic)
}
func (m *RestoreBackupTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestoreBackupTask.Merge(m, src)
}
func (m *RestoreBackupTask) XXX_Size() int {
	return xxx_messageInfo_RestoreBackupTask.Size(m)
}
func (m *RestoreBackupTask) XXX_DiscardUnknown() {
	xxx_messageInfo_RestoreBackupTask.DiscardUnknown(m)
}

var xxx_messageInfo_RestoreBackupTask proto.InternalMessageInfo

func (m *RestoreBackupTask) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RestoreBackupTask) GetStateCode() RestoreTaskStateCode {
	if m != nil {
		return m.StateCode
	}
	return RestoreTaskStateCode_INITIAL
}

func (m *RestoreBackupTask) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *RestoreBackupTask) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *RestoreBackupTask) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *RestoreBackupTask) GetCollectionRestoreTasks() []*RestoreCollectionTask {
	if m != nil {
		return m.CollectionRestoreTasks
	}
	return nil
}

func (m *RestoreBackupTask) GetRestoredSize() int64 {
	if m != nil {
		return m.RestoredSize
	}
	return 0
}

func (m *RestoreBackupTask) GetToRestoreSize() int64 {
	if m != nil {
		return m.ToRestoreSize
	}
	return 0
}

func (m *RestoreBackupTask) GetProgress() int32 {
	if m != nil {
		return m.Progress
	}
	return 0
}

type RestoreBackupResponse struct {
	// uuid of the request to response
	RequestId string `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	// response code. 0 means success. others are fail
	Code ResponseCode `protobuf:"varint,2,opt,name=code,proto3,enum=milvus.proto.backup.ResponseCode" json:"code,omitempty"`
	// error msg if fail
	Msg string `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	// restore task info entity
	Data                 *RestoreBackupTask `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *RestoreBackupResponse) Reset()         { *m = RestoreBackupResponse{} }
func (m *RestoreBackupResponse) String() string { return proto.CompactTextString(m) }
func (*RestoreBackupResponse) ProtoMessage()    {}
func (*RestoreBackupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{18}
}

func (m *RestoreBackupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestoreBackupResponse.Unmarshal(m, b)
}
func (m *RestoreBackupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestoreBackupResponse.Marshal(b, m, deterministic)
}
func (m *RestoreBackupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestoreBackupResponse.Merge(m, src)
}
func (m *RestoreBackupResponse) XXX_Size() int {
	return xxx_messageInfo_RestoreBackupResponse.Size(m)
}
func (m *RestoreBackupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RestoreBackupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RestoreBackupResponse proto.InternalMessageInfo

func (m *RestoreBackupResponse) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *RestoreBackupResponse) GetCode() ResponseCode {
	if m != nil {
		return m.Code
	}
	return ResponseCode_Success
}

func (m *RestoreBackupResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *RestoreBackupResponse) GetData() *RestoreBackupTask {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetRestoreStateRequest struct {
	// uuid of request, will generate one if not set
	RequestId string `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	// restore task id to query
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRestoreStateRequest) Reset()         { *m = GetRestoreStateRequest{} }
func (m *GetRestoreStateRequest) String() string { return proto.CompactTextString(m) }
func (*GetRestoreStateRequest) ProtoMessage()    {}
func (*GetRestoreStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{19}
}

func (m *GetRestoreStateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRestoreStateRequest.Unmarshal(m, b)
}
func (m *GetRestoreStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRestoreStateRequest.Marshal(b, m, deterministic)
}
func (m *GetRestoreStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRestoreStateRequest.Merge(m, src)
}
func (m *GetRestoreStateRequest) XXX_Size() int {
	return xxx_messageInfo_GetRestoreStateRequest.Size(m)
}
func (m *GetRestoreStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRestoreStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRestoreStateRequest proto.InternalMessageInfo

func (m *GetRestoreStateRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *GetRestoreStateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// copied from milvus data_coord.proto
type FieldBinlog struct {
	FieldID              int64     `protobuf:"varint,1,opt,name=fieldID,proto3" json:"fieldID,omitempty"`
	Binlogs              []*Binlog `protobuf:"bytes,2,rep,name=binlogs,proto3" json:"binlogs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *FieldBinlog) Reset()         { *m = FieldBinlog{} }
func (m *FieldBinlog) String() string { return proto.CompactTextString(m) }
func (*FieldBinlog) ProtoMessage()    {}
func (*FieldBinlog) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{20}
}

func (m *FieldBinlog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldBinlog.Unmarshal(m, b)
}
func (m *FieldBinlog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldBinlog.Marshal(b, m, deterministic)
}
func (m *FieldBinlog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldBinlog.Merge(m, src)
}
func (m *FieldBinlog) XXX_Size() int {
	return xxx_messageInfo_FieldBinlog.Size(m)
}
func (m *FieldBinlog) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldBinlog.DiscardUnknown(m)
}

var xxx_messageInfo_FieldBinlog proto.InternalMessageInfo

func (m *FieldBinlog) GetFieldID() int64 {
	if m != nil {
		return m.FieldID
	}
	return 0
}

func (m *FieldBinlog) GetBinlogs() []*Binlog {
	if m != nil {
		return m.Binlogs
	}
	return nil
}

type Binlog struct {
	EntriesNum           int64    `protobuf:"varint,1,opt,name=entries_num,json=entriesNum,proto3" json:"entries_num,omitempty"`
	TimestampFrom        uint64   `protobuf:"varint,2,opt,name=timestamp_from,json=timestampFrom,proto3" json:"timestamp_from,omitempty"`
	TimestampTo          uint64   `protobuf:"varint,3,opt,name=timestamp_to,json=timestampTo,proto3" json:"timestamp_to,omitempty"`
	LogPath              string   `protobuf:"bytes,4,opt,name=log_path,json=logPath,proto3" json:"log_path,omitempty"`
	LogSize              int64    `protobuf:"varint,5,opt,name=log_size,json=logSize,proto3" json:"log_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Binlog) Reset()         { *m = Binlog{} }
func (m *Binlog) String() string { return proto.CompactTextString(m) }
func (*Binlog) ProtoMessage()    {}
func (*Binlog) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{21}
}

func (m *Binlog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Binlog.Unmarshal(m, b)
}
func (m *Binlog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Binlog.Marshal(b, m, deterministic)
}
func (m *Binlog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Binlog.Merge(m, src)
}
func (m *Binlog) XXX_Size() int {
	return xxx_messageInfo_Binlog.Size(m)
}
func (m *Binlog) XXX_DiscardUnknown() {
	xxx_messageInfo_Binlog.DiscardUnknown(m)
}

var xxx_messageInfo_Binlog proto.InternalMessageInfo

func (m *Binlog) GetEntriesNum() int64 {
	if m != nil {
		return m.EntriesNum
	}
	return 0
}

func (m *Binlog) GetTimestampFrom() uint64 {
	if m != nil {
		return m.TimestampFrom
	}
	return 0
}

func (m *Binlog) GetTimestampTo() uint64 {
	if m != nil {
		return m.TimestampTo
	}
	return 0
}

func (m *Binlog) GetLogPath() string {
	if m != nil {
		return m.LogPath
	}
	return ""
}

func (m *Binlog) GetLogSize() int64 {
	if m != nil {
		return m.LogSize
	}
	return 0
}

// copied from milvus common.proto
type KeyValuePair struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyValuePair) Reset()         { *m = KeyValuePair{} }
func (m *KeyValuePair) String() string { return proto.CompactTextString(m) }
func (*KeyValuePair) ProtoMessage()    {}
func (*KeyValuePair) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{22}
}

func (m *KeyValuePair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyValuePair.Unmarshal(m, b)
}
func (m *KeyValuePair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyValuePair.Marshal(b, m, deterministic)
}
func (m *KeyValuePair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyValuePair.Merge(m, src)
}
func (m *KeyValuePair) XXX_Size() int {
	return xxx_messageInfo_KeyValuePair.Size(m)
}
func (m *KeyValuePair) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyValuePair.DiscardUnknown(m)
}

var xxx_messageInfo_KeyValuePair proto.InternalMessageInfo

func (m *KeyValuePair) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KeyValuePair) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

//*
// @brief Field schema
type FieldSchema struct {
	FieldID              int64           `protobuf:"varint,1,opt,name=fieldID,proto3" json:"fieldID,omitempty"`
	Name                 string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsPrimaryKey         bool            `protobuf:"varint,3,opt,name=is_primary_key,json=isPrimaryKey,proto3" json:"is_primary_key,omitempty"`
	Description          string          `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	DataType             DataType        `protobuf:"varint,5,opt,name=data_type,json=dataType,proto3,enum=milvus.proto.backup.DataType" json:"data_type,omitempty"`
	TypeParams           []*KeyValuePair `protobuf:"bytes,6,rep,name=type_params,json=typeParams,proto3" json:"type_params,omitempty"`
	IndexParams          []*KeyValuePair `protobuf:"bytes,7,rep,name=index_params,json=indexParams,proto3" json:"index_params,omitempty"`
	AutoID               bool            `protobuf:"varint,8,opt,name=autoID,proto3" json:"autoID,omitempty"`
	State                FieldState      `protobuf:"varint,9,opt,name=state,proto3,enum=milvus.proto.backup.FieldState" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *FieldSchema) Reset()         { *m = FieldSchema{} }
func (m *FieldSchema) String() string { return proto.CompactTextString(m) }
func (*FieldSchema) ProtoMessage()    {}
func (*FieldSchema) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{23}
}

func (m *FieldSchema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldSchema.Unmarshal(m, b)
}
func (m *FieldSchema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldSchema.Marshal(b, m, deterministic)
}
func (m *FieldSchema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldSchema.Merge(m, src)
}
func (m *FieldSchema) XXX_Size() int {
	return xxx_messageInfo_FieldSchema.Size(m)
}
func (m *FieldSchema) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldSchema.DiscardUnknown(m)
}

var xxx_messageInfo_FieldSchema proto.InternalMessageInfo

func (m *FieldSchema) GetFieldID() int64 {
	if m != nil {
		return m.FieldID
	}
	return 0
}

func (m *FieldSchema) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FieldSchema) GetIsPrimaryKey() bool {
	if m != nil {
		return m.IsPrimaryKey
	}
	return false
}

func (m *FieldSchema) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *FieldSchema) GetDataType() DataType {
	if m != nil {
		return m.DataType
	}
	return DataType_None
}

func (m *FieldSchema) GetTypeParams() []*KeyValuePair {
	if m != nil {
		return m.TypeParams
	}
	return nil
}

func (m *FieldSchema) GetIndexParams() []*KeyValuePair {
	if m != nil {
		return m.IndexParams
	}
	return nil
}

func (m *FieldSchema) GetAutoID() bool {
	if m != nil {
		return m.AutoID
	}
	return false
}

func (m *FieldSchema) GetState() FieldState {
	if m != nil {
		return m.State
	}
	return FieldState_FieldCreated
}

//*
// @brief Collection schema
type CollectionSchema struct {
	Name                 string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string         `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	AutoID               bool           `protobuf:"varint,3,opt,name=autoID,proto3" json:"autoID,omitempty"`
	Fields               []*FieldSchema `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CollectionSchema) Reset()         { *m = CollectionSchema{} }
func (m *CollectionSchema) String() string { return proto.CompactTextString(m) }
func (*CollectionSchema) ProtoMessage()    {}
func (*CollectionSchema) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{24}
}

func (m *CollectionSchema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectionSchema.Unmarshal(m, b)
}
func (m *CollectionSchema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectionSchema.Marshal(b, m, deterministic)
}
func (m *CollectionSchema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectionSchema.Merge(m, src)
}
func (m *CollectionSchema) XXX_Size() int {
	return xxx_messageInfo_CollectionSchema.Size(m)
}
func (m *CollectionSchema) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectionSchema.DiscardUnknown(m)
}

var xxx_messageInfo_CollectionSchema proto.InternalMessageInfo

func (m *CollectionSchema) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CollectionSchema) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CollectionSchema) GetAutoID() bool {
	if m != nil {
		return m.AutoID
	}
	return false
}

func (m *CollectionSchema) GetFields() []*FieldSchema {
	if m != nil {
		return m.Fields
	}
	return nil
}

func init() {
	proto.RegisterEnum("milvus.proto.backup.ResponseCode", ResponseCode_name, ResponseCode_value)
	proto.RegisterEnum("milvus.proto.backup.BackupTaskStateCode", BackupTaskStateCode_name, BackupTaskStateCode_value)
	proto.RegisterEnum("milvus.proto.backup.RestoreTaskStateCode", RestoreTaskStateCode_name, RestoreTaskStateCode_value)
	proto.RegisterEnum("milvus.proto.backup.ConsistencyLevel", ConsistencyLevel_name, ConsistencyLevel_value)
	proto.RegisterEnum("milvus.proto.backup.DataType", DataType_name, DataType_value)
	proto.RegisterEnum("milvus.proto.backup.FieldState", FieldState_name, FieldState_value)
	proto.RegisterType((*CollectionBackupInfo)(nil), "milvus.proto.backup.CollectionBackupInfo")
	proto.RegisterType((*PartitionBackupInfo)(nil), "milvus.proto.backup.PartitionBackupInfo")
	proto.RegisterType((*SegmentBackupInfo)(nil), "milvus.proto.backup.SegmentBackupInfo")
	proto.RegisterType((*BackupInfo)(nil), "milvus.proto.backup.BackupInfo")
	proto.RegisterType((*CollectionLevelBackupInfo)(nil), "milvus.proto.backup.CollectionLevelBackupInfo")
	proto.RegisterType((*PartitionLevelBackupInfo)(nil), "milvus.proto.backup.PartitionLevelBackupInfo")
	proto.RegisterType((*SegmentLevelBackupInfo)(nil), "milvus.proto.backup.SegmentLevelBackupInfo")
	proto.RegisterType((*CreateBackupRequest)(nil), "milvus.proto.backup.CreateBackupRequest")
	proto.RegisterType((*BackupInfoResponse)(nil), "milvus.proto.backup.BackupInfoResponse")
	proto.RegisterType((*GetBackupRequest)(nil), "milvus.proto.backup.GetBackupRequest")
	proto.RegisterType((*ListBackupsRequest)(nil), "milvus.proto.backup.ListBackupsRequest")
	proto.RegisterType((*ListBackupsResponse)(nil), "milvus.proto.backup.ListBackupsResponse")
	proto.RegisterType((*DeleteBackupRequest)(nil), "milvus.proto.backup.DeleteBackupRequest")
	proto.RegisterType((*DeleteBackupResponse)(nil), "milvus.proto.backup.DeleteBackupResponse")
	proto.RegisterType((*RestoreBackupRequest)(nil), "milvus.proto.backup.RestoreBackupRequest")
	proto.RegisterMapType((map[string]string)(nil), "milvus.proto.backup.RestoreBackupRequest.CollectionRenamesEntry")
	proto.RegisterType((*RestorePartitionTask)(nil), "milvus.proto.backup.RestorePartitionTask")
	proto.RegisterType((*RestoreCollectionTask)(nil), "milvus.proto.backup.RestoreCollectionTask")
	proto.RegisterType((*RestoreBackupTask)(nil), "milvus.proto.backup.RestoreBackupTask")
	proto.RegisterType((*RestoreBackupResponse)(nil), "milvus.proto.backup.RestoreBackupResponse")
	proto.RegisterType((*GetRestoreStateRequest)(nil), "milvus.proto.backup.GetRestoreStateRequest")
	proto.RegisterType((*FieldBinlog)(nil), "milvus.proto.backup.FieldBinlog")
	proto.RegisterType((*Binlog)(nil), "milvus.proto.backup.Binlog")
	proto.RegisterType((*KeyValuePair)(nil), "milvus.proto.backup.KeyValuePair")
	proto.RegisterType((*FieldSchema)(nil), "milvus.proto.backup.FieldSchema")
	proto.RegisterType((*CollectionSchema)(nil), "milvus.proto.backup.CollectionSchema")
}

func init() { proto.RegisterFile("backup.proto", fileDescriptor_65240d19de191688) }

var fileDescriptor_65240d19de191688 = []byte{
	// 2095 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x58, 0xcb, 0x73, 0x1b, 0x49,
	0x19, 0xf7, 0x68, 0x64, 0x3d, 0xbe, 0x91, 0xe5, 0x71, 0xdb, 0xeb, 0x9d, 0xf5, 0x12, 0xa2, 0x15,
	0x24, 0xab, 0x78, 0x8b, 0xa4, 0x70, 0x36, 0x21, 0xa4, 0x60, 0x21, 0x96, 0xed, 0x20, 0x92, 0x38,
	0xae, 0x91, 0xe2, 0x4a, 0x2d, 0x8f, 0xa9, 0xd1, 0x4c, 0x5b, 0x1e, 0x32, 0x33, 0x2d, 0xa6, 0x5b,
	0xd9, 0x28, 0x55, 0xf0, 0x17, 0x70, 0xe0, 0x00, 0x55, 0x5b, 0x5b, 0x70, 0xe2, 0xc4, 0x09, 0x38,
	0x70, 0xe1, 0x3f, 0x82, 0x7f, 0x80, 0x2b, 0xd5, 0xdd, 0xf3, 0x92, 0x3c, 0xb6, 0x95, 0xaa, 0x2d,
	0xc2, 0x72, 0xeb, 0xfe, 0xfa, 0x7b, 0x74, 0xff, 0xbe, 0x47, 0x7f, 0xdd, 0xd0, 0x18, 0xda, 0xce,
	0x8b, 0xc9, 0xf8, 0xe6, 0x38, 0x22, 0x8c, 0xa0, 0xf5, 0xc0, 0xf3, 0x5f, 0x4e, 0xa8, 0x9c, 0xdd,
	0x94, 0x4b, 0xed, 0xcf, 0x97, 0x61, 0xa3, 0x4b, 0x7c, 0x1f, 0x3b, 0xcc, 0x23, 0xe1, 0xae, 0x20,
	0xf6, 0xc2, 0x13, 0x82, 0x9a, 0x50, 0xf2, 0x5c, 0x43, 0x69, 0x29, 0x9d, 0xba, 0x59, 0xf2, 0x5c,
	0xf4, 0x10, 0x80, 0x32, 0x9b, 0x61, 0xcb, 0x21, 0x2e, 0x36, 0x4a, 0x2d, 0xa5, 0xd3, 0xdc, 0xe9,
	0xdc, 0x2c, 0x50, 0x79, 0x53, 0x2a, 0x19, 0xd8, 0xf4, 0x45, 0x9f, 0x0b, 0x74, 0x89, 0x8b, 0xcd,
	0x3a, 0x4d, 0x86, 0xa8, 0x0d, 0x0d, 0x1c, 0x45, 0x24, 0x7a, 0x82, 0x29, 0xb5, 0x47, 0xd8, 0x50,
	0x85, 0x89, 0x19, 0x1a, 0xba, 0x22, 0x8c, 0x45, 0xcc, 0x62, 0x5e, 0x80, 0x8d, 0x72, 0x4b, 0xe9,
	0xa8, 0x42, 0x45, 0xc4, 0x06, 0x5e, 0x80, 0xd1, 0x7b, 0x50, 0xc3, 0xa1, 0x2b, 0x17, 0x97, 0xc5,
	0x62, 0x15, 0x87, 0xae, 0x58, 0xda, 0x82, 0xda, 0x38, 0x22, 0xa3, 0x08, 0x53, 0x6a, 0x54, 0x5a,
	0x4a, 0x67, 0xd9, 0x4c, 0xe7, 0xe8, 0x1b, 0xb0, 0xe2, 0xa4, 0x47, 0xb5, 0x3c, 0xd7, 0xa8, 0x0a,
	0xd9, 0x46, 0x46, 0xec, 0xb9, 0xe8, 0x5d, 0xa8, 0xba, 0x43, 0x2b, 0xb4, 0x03, 0x6c, 0xd4, 0xc4,
	0xce, 0x2a, 0xee, 0xf0, 0xd0, 0x0e, 0x30, 0xfa, 0x10, 0x56, 0x73, 0xd2, 0x82, 0xa1, 0x2e, 0x18,
	0x9a, 0x19, 0x59, 0x30, 0x7e, 0x1f, 0x2a, 0xd4, 0x39, 0xc5, 0x81, 0x6d, 0x40, 0x4b, 0xe9, 0x68,
	0x3b, 0xd7, 0x0a, 0x51, 0xca, 0x40, 0xef, 0x0b, 0x66, 0x33, 0x16, 0x12, 0x67, 0x3f, 0xb5, 0x23,
	0x97, 0x5a, 0xe1, 0x24, 0x30, 0x34, 0x71, 0x86, 0xba, 0xa4, 0x1c, 0x4e, 0x02, 0x64, 0xc2, 0x9a,
	0x43, 0x42, 0xea, 0x51, 0x86, 0x43, 0x67, 0x6a, 0xf9, 0xf8, 0x25, 0xf6, 0x8d, 0x86, 0x70, 0xc7,
	0x79, 0x86, 0x52, 0xee, 0xc7, 0x9c, 0xd9, 0xd4, 0x9d, 0x39, 0x0a, 0x7a, 0x06, 0x6b, 0x63, 0x3b,
	0x62, 0x9e, 0x38, 0x99, 0x14, 0xa3, 0xc6, 0x4a, 0x4b, 0xed, 0x68, 0xe7, 0xb8, 0xf8, 0x28, 0xe1,
	0xce, 0x02, 0xc6, 0xd4, 0xc7, 0xb3, 0x44, 0x8a, 0x6e, 0x80, 0x2e, 0xf9, 0x85, 0xa7, 0x28, 0xb3,
	0x83, 0xb1, 0xd1, 0x6c, 0x29, 0x9d, 0xb2, 0xb9, 0x2a, 0xe9, 0x83, 0x84, 0x8c, 0x10, 0x94, 0xa9,
	0xf7, 0x1a, 0x1b, 0xab, 0xc2, 0x23, 0x62, 0xdc, 0xfe, 0xa7, 0x02, 0xeb, 0x05, 0x86, 0xd0, 0x07,
	0xd0, 0xc8, 0x76, 0x1b, 0xc7, 0xa8, 0x6a, 0x6a, 0x29, 0xad, 0xe7, 0xa2, 0x6b, 0xd0, 0xcc, 0x58,
	0x84, 0xab, 0x4a, 0xc2, 0x55, 0x2b, 0x29, 0x55, 0x78, 0xea, 0x4c, 0x40, 0xa8, 0x05, 0x01, 0xf1,
	0x14, 0x56, 0x29, 0x1e, 0x05, 0x38, 0x64, 0x29, 0x34, 0x55, 0x01, 0xcd, 0xf5, 0x42, 0x68, 0xfa,
	0x92, 0x37, 0x07, 0x4c, 0x93, 0xe6, 0x49, 0x34, 0x3d, 0x6b, 0x2d, 0x77, 0xd6, 0x7f, 0x95, 0x60,
	0xed, 0x8c, 0xa4, 0x08, 0x85, 0xd8, 0x74, 0x7a, 0xce, 0x7a, 0x4c, 0xe9, 0xb9, 0x67, 0xb7, 0x5f,
	0x2a, 0xd8, 0xfe, 0x3c, 0x5a, 0xea, 0x59, 0xb4, 0xbe, 0x0e, 0x5a, 0x38, 0x09, 0x2c, 0x72, 0x62,
	0x45, 0xe4, 0x33, 0x9a, 0xa4, 0x5b, 0x38, 0x09, 0x9e, 0x9e, 0x98, 0xe4, 0x33, 0x8a, 0xee, 0x43,
	0x75, 0xe8, 0x85, 0x3e, 0x19, 0x51, 0x63, 0x59, 0x9c, 0xbc, 0x55, 0x78, 0xf2, 0x03, 0x0f, 0xfb,
	0xee, 0xae, 0x60, 0x34, 0x13, 0x01, 0xf4, 0x09, 0x88, 0xd4, 0xa7, 0x42, 0xba, 0xb2, 0xa0, 0x74,
	0x26, 0xc2, 0xe5, 0x5d, 0xec, 0x33, 0x5b, 0xc8, 0x57, 0x17, 0x95, 0x4f, 0x45, 0x0a, 0xc1, 0xfe,
	0x8d, 0x0a, 0xf0, 0xff, 0x5d, 0xe9, 0x10, 0x94, 0x45, 0xd4, 0x57, 0x85, 0x45, 0x31, 0x2e, 0xcc,
	0xc6, 0x5a, 0x71, 0x36, 0x3e, 0x07, 0x94, 0x0b, 0xac, 0x24, 0xea, 0xeb, 0x02, 0xfd, 0x1b, 0x97,
	0x54, 0xb3, 0x5c, 0xe0, 0xaf, 0x39, 0x73, 0xd4, 0xcc, 0x1d, 0x90, 0x73, 0xc7, 0x4f, 0xe1, 0xbd,
	0x4c, 0x5c, 0x14, 0xa4, 0x9c, 0x73, 0x7e, 0x00, 0xcb, 0x5e, 0x78, 0x42, 0xa8, 0xa1, 0xbc, 0xa9,
	0x75, 0x29, 0xd7, 0xfe, 0x14, 0x8c, 0xb4, 0x88, 0xcc, 0x2b, 0xff, 0x64, 0x56, 0xf9, 0xe2, 0xb5,
	0x2e, 0xd6, 0x7d, 0x0c, 0x9b, 0x71, 0xd2, 0xce, 0x6b, 0xfe, 0xde, 0xac, 0xe6, 0x45, 0x4b, 0x45,
	0xac, 0xf7, 0xf7, 0x0a, 0xac, 0x77, 0x23, 0x6c, 0x33, 0x2c, 0xd7, 0x4c, 0xfc, 0xcb, 0x09, 0xa6,
	0x0c, 0x7d, 0x0d, 0xea, 0x91, 0x1c, 0xf6, 0x92, 0x80, 0xcd, 0x08, 0xe8, 0x2a, 0x68, 0xb1, 0x83,
	0x73, 0x15, 0x0f, 0x24, 0xe9, 0x30, 0x8e, 0x80, 0xb9, 0x1b, 0x8c, 0x1a, 0x6a, 0x4b, 0xed, 0xd4,
	0xcd, 0xd5, 0xd9, 0x2b, 0x8c, 0xa2, 0x0d, 0x58, 0xb6, 0xe9, 0x34, 0x74, 0x44, 0x44, 0xd6, 0x4c,
	0x39, 0x69, 0xff, 0x55, 0x01, 0x94, 0xdb, 0x2d, 0xa6, 0x63, 0x12, 0x52, 0x7c, 0xc9, 0xb6, 0xee,
	0x40, 0x39, 0x97, 0x48, 0x1f, 0x14, 0x22, 0x91, 0xa8, 0x12, 0x19, 0x24, 0xd8, 0x91, 0x0e, 0x6a,
	0x40, 0x47, 0x71, 0xce, 0xf0, 0x21, 0xba, 0x0d, 0x65, 0xd7, 0x66, 0xb6, 0xd8, 0x92, 0xb6, 0x73,
	0xf5, 0x82, 0x8c, 0x14, 0xbb, 0x13, 0xcc, 0xed, 0x3f, 0x29, 0xa0, 0x3f, 0xc4, 0xec, 0x4b, 0xc5,
	0xf1, 0x7d, 0xa8, 0xc7, 0x0c, 0x71, 0x3d, 0xad, 0x9b, 0x35, 0x49, 0x88, 0xa5, 0x27, 0xce, 0x0b,
	0xcc, 0xa4, 0x74, 0x39, 0x96, 0x16, 0x24, 0x21, 0x8d, 0xa0, 0x3c, 0xb6, 0xd9, 0xa9, 0x48, 0xe7,
	0xba, 0x29, 0xc6, 0xed, 0x9f, 0x00, 0x7a, 0xec, 0xd1, 0xe4, 0x86, 0x58, 0x6c, 0x9b, 0x05, 0xfd,
	0x48, 0xa9, 0xa8, 0x1f, 0x69, 0xff, 0x4d, 0x81, 0xf5, 0x19, 0xed, 0x6f, 0xcb, 0x6d, 0xea, 0xe2,
	0x6e, 0x1b, 0xc0, 0xfa, 0x1e, 0xf6, 0xf1, 0x97, 0x9b, 0x00, 0xed, 0x5f, 0xc1, 0xc6, 0xac, 0xd6,
	0xff, 0x2a, 0x12, 0xed, 0xbf, 0xa8, 0xb0, 0x61, 0x62, 0xca, 0x48, 0xf4, 0xd6, 0xf2, 0xfa, 0x23,
	0xc8, 0x15, 0x65, 0x8b, 0x4e, 0x4e, 0x4e, 0xbc, 0x57, 0x71, 0x8c, 0xe6, 0x74, 0xf4, 0x05, 0x1d,
	0x91, 0x99, 0x6b, 0x20, 0xc2, 0x52, 0xb3, 0x6c, 0x01, 0x7e, 0x78, 0x1e, 0x0c, 0x67, 0x4e, 0x97,
	0xab, 0xce, 0xa6, 0x54, 0xb1, 0x1f, 0xb2, 0x68, 0x9a, 0xbf, 0x1d, 0x62, 0x7a, 0x56, 0x75, 0x2a,
	0xb9, 0xaa, 0x33, 0x9f, 0x51, 0xd5, 0x73, 0x33, 0xaa, 0x96, 0x65, 0xd4, 0xd6, 0x1e, 0x6c, 0x16,
	0xdb, 0xe5, 0x7e, 0x79, 0x81, 0xa7, 0x31, 0xcc, 0x7c, 0xc8, 0xcd, 0xbe, 0xb4, 0xfd, 0x49, 0x02,
	0xad, 0x9c, 0xdc, 0x2f, 0xdd, 0x53, 0xda, 0x7f, 0x2f, 0xa5, 0x1e, 0x4b, 0xaf, 0x01, 0x7e, 0xdd,
	0x9f, 0xe9, 0x19, 0x7e, 0x54, 0xd0, 0x33, 0xdc, 0xb8, 0x08, 0xa2, 0xff, 0xc1, 0xa6, 0xa1, 0x07,
	0xa2, 0x2b, 0x8c, 0xef, 0x7b, 0x81, 0xf3, 0x9b, 0xdc, 0x89, 0xc0, 0x85, 0xe5, 0xbc, 0xfd, 0xc7,
	0x32, 0xbc, 0x13, 0x1f, 0x34, 0xf3, 0xc2, 0x57, 0x1a, 0xb8, 0x1f, 0x83, 0xc6, 0xe3, 0x35, 0x01,
	0xa7, 0x22, 0xc0, 0x79, 0x83, 0x6e, 0x04, 0xb8, 0xb4, 0x9c, 0xa3, 0x8f, 0x61, 0x93, 0xd9, 0xd1,
	0x08, 0x33, 0x6b, 0xbe, 0x80, 0xcb, 0xd8, 0xde, 0x90, 0xab, 0xdd, 0xd9, 0x67, 0xa5, 0x0d, 0xef,
	0x66, 0x8d, 0x7c, 0x24, 0xc1, 0xb0, 0x98, 0x4d, 0x5f, 0x50, 0xa3, 0x76, 0x41, 0x6f, 0x54, 0x14,
	0xbe, 0xe6, 0x3b, 0xa9, 0xa6, 0x1c, 0xaa, 0xe2, 0x81, 0x1c, 0x2b, 0x76, 0x2d, 0xd1, 0xa6, 0xd5,
	0xe5, 0x83, 0x22, 0x21, 0xf6, 0xbd, 0xd7, 0x18, 0x5d, 0x87, 0x55, 0x46, 0xd2, 0x0d, 0xe4, 0xba,
	0xb9, 0x15, 0x46, 0x62, 0x6d, 0x82, 0x2f, 0x1f, 0x6a, 0xda, 0x6c, 0xa8, 0xb5, 0xbf, 0x50, 0x61,
	0x6d, 0xa6, 0x56, 0x7c, 0xa5, 0x63, 0xc3, 0x05, 0x63, 0xa6, 0x4e, 0xe6, 0x5d, 0x23, 0x9f, 0x3c,
	0xdb, 0x17, 0xed, 0x7a, 0x36, 0x43, 0xcc, 0xcd, 0x7c, 0x5d, 0xbc, 0xc8, 0x39, 0xd5, 0xc5, 0x9c,
	0x53, 0xbb, 0xcc, 0x39, 0xf5, 0x39, 0xe7, 0xfc, 0x43, 0x49, 0x93, 0xf7, 0xad, 0xdc, 0x93, 0xe8,
	0xfe, 0x4c, 0xa3, 0x77, 0xfd, 0xf2, 0x9b, 0x46, 0xe0, 0x26, 0x1b, 0x87, 0x03, 0xd8, 0x7c, 0x88,
	0x59, 0x72, 0x54, 0x1e, 0x00, 0x8b, 0x5d, 0xb2, 0x32, 0xf6, 0x4a, 0x49, 0xec, 0xb5, 0x7f, 0x0e,
	0x5a, 0xee, 0x45, 0x89, 0x0c, 0xa8, 0x9e, 0xf0, 0x69, 0x6f, 0x2f, 0x7e, 0x86, 0x27, 0x53, 0x74,
	0x27, 0x7b, 0x1c, 0x97, 0x84, 0xaf, 0xdf, 0x2f, 0xee, 0x70, 0x66, 0xdf, 0xc5, 0xed, 0x3f, 0x2b,
	0x50, 0x89, 0x75, 0x5f, 0x05, 0x0d, 0x87, 0x2c, 0xf2, 0xb0, 0xfc, 0xf1, 0x91, 0xfa, 0x21, 0x26,
	0x1d, 0x4e, 0x02, 0x74, 0x0d, 0x9a, 0xe9, 0x93, 0xcd, 0x3a, 0x89, 0x48, 0x20, 0xf6, 0x59, 0x36,
	0x57, 0x52, 0xea, 0x41, 0x44, 0x02, 0xfe, 0xd2, 0xcf, 0xd8, 0x18, 0x11, 0x88, 0x96, 0x4d, 0x2d,
	0xa5, 0x0d, 0x08, 0x0f, 0x62, 0x9f, 0x8c, 0x2c, 0x71, 0x5b, 0xca, 0x5b, 0xbf, 0xea, 0x93, 0xd1,
	0x91, 0xcd, 0x4e, 0x93, 0x25, 0x11, 0x32, 0x71, 0x7c, 0xfb, 0x64, 0xc4, 0x83, 0xa5, 0x7d, 0x17,
	0x1a, 0x8f, 0xf0, 0xf4, 0x98, 0xdf, 0x8a, 0x47, 0xb6, 0x17, 0x2d, 0x7a, 0x83, 0xb6, 0x3f, 0x57,
	0x63, 0x10, 0xe5, 0x0f, 0xd7, 0x05, 0x20, 0x26, 0xef, 0xd5, 0x52, 0xee, 0xbd, 0xfa, 0x4d, 0x68,
	0x7a, 0xd4, 0x1a, 0x47, 0x5e, 0x60, 0x47, 0x53, 0x8b, 0x1b, 0x54, 0x45, 0x57, 0xd0, 0xf0, 0xe8,
	0x91, 0x24, 0x3e, 0xc2, 0x53, 0xd4, 0x02, 0xcd, 0xc5, 0xd4, 0x89, 0xbc, 0x31, 0x4f, 0x98, 0xf8,
	0x50, 0x79, 0x12, 0xba, 0x0f, 0x75, 0x1e, 0x19, 0x16, 0x9b, 0x8e, 0xe5, 0xc9, 0x9a, 0x3b, 0x57,
	0x0a, 0x5d, 0xb4, 0x67, 0x33, 0x7b, 0x30, 0x1d, 0x63, 0xb3, 0xe6, 0xc6, 0x23, 0xb4, 0x0b, 0x1a,
	0x17, 0xb3, 0xc6, 0x76, 0x64, 0x07, 0x49, 0x32, 0x17, 0x47, 0x76, 0x1e, 0x21, 0x13, 0xb8, 0xd4,
	0x91, 0x10, 0x42, 0x7b, 0xd0, 0xf0, 0x42, 0x17, 0xbf, 0x4a, 0x94, 0x54, 0x17, 0x55, 0xa2, 0x09,
	0xb1, 0x58, 0xcb, 0x26, 0x54, 0xec, 0x09, 0x23, 0xbd, 0x3d, 0x91, 0xcf, 0x35, 0x33, 0x9e, 0xa1,
	0x3b, 0xb0, 0x2c, 0xca, 0x9c, 0xc8, 0xe2, 0xe6, 0x39, 0xed, 0xb5, 0x74, 0x82, 0x48, 0x06, 0xc9,
	0xdd, 0xfe, 0x42, 0x01, 0x7d, 0xfe, 0x07, 0x32, 0xf5, 0x82, 0x92, 0xf3, 0xc2, 0x1c, 0xbe, 0xa5,
	0xb3, 0xf8, 0x66, 0x3b, 0x53, 0x67, 0x76, 0x76, 0x0f, 0x2a, 0xc2, 0xbd, 0x34, 0xee, 0xfc, 0x2f,
	0xf8, 0xb6, 0x49, 0x7e, 0x40, 0x25, 0xff, 0xf6, 0xaf, 0xa1, 0x91, 0xaf, 0x13, 0x48, 0x83, 0x6a,
	0x7f, 0xe2, 0x38, 0x98, 0x52, 0x7d, 0x09, 0xad, 0x82, 0x76, 0x48, 0x98, 0xd5, 0x9f, 0x8c, 0xc7,
	0x24, 0x62, 0xba, 0x82, 0xd6, 0x60, 0xe5, 0x90, 0x58, 0x47, 0x38, 0x0a, 0x3c, 0x4a, 0x3d, 0x12,
	0xea, 0x25, 0x54, 0x83, 0xf2, 0x81, 0xed, 0xf9, 0xba, 0x8a, 0x36, 0x60, 0x55, 0x00, 0x88, 0x19,
	0x8e, 0xac, 0x7d, 0x5e, 0xee, 0xf5, 0xdf, 0xaa, 0xe8, 0x0a, 0x18, 0x71, 0x55, 0xb0, 0x9e, 0x0e,
	0x7f, 0x81, 0x1d, 0x66, 0x71, 0x95, 0x07, 0x64, 0x12, 0xba, 0xfa, 0xef, 0xd4, 0xed, 0x57, 0xb0,
	0x5e, 0xf0, 0xb3, 0x83, 0x10, 0x34, 0x77, 0x1f, 0x74, 0x1f, 0x3d, 0x3b, 0xb2, 0x7a, 0x87, 0xbd,
	0x41, 0xef, 0xc1, 0x63, 0x7d, 0x09, 0x6d, 0x80, 0x1e, 0xd3, 0xf6, 0x9f, 0xef, 0x77, 0x9f, 0x0d,
	0x7a, 0x87, 0x0f, 0x75, 0x25, 0xc7, 0xd9, 0x7f, 0xd6, 0xed, 0xee, 0xf7, 0xfb, 0x7a, 0x89, 0xef,
	0x3b, 0xa6, 0x1d, 0x3c, 0xe8, 0x3d, 0xd6, 0xd5, 0x1c, 0xd3, 0xa0, 0xf7, 0x64, 0xff, 0xe9, 0xb3,
	0x81, 0x5e, 0xde, 0x3e, 0x4e, 0xdb, 0xcd, 0x59, 0xd3, 0x1a, 0x54, 0x33, 0x9b, 0x2b, 0x50, 0xcf,
	0x1b, 0xe3, 0xe8, 0xa4, 0x56, 0xf8, 0xc9, 0xa5, 0x7a, 0x0d, 0xaa, 0x99, 0xde, 0xe7, 0xdc, 0xdb,
	0x73, 0x9f, 0xbe, 0x00, 0x95, 0x3e, 0x8b, 0x48, 0x38, 0xd2, 0x97, 0x84, 0x0e, 0x2c, 0xd1, 0x13,
	0x0a, 0x77, 0x39, 0x14, 0xd8, 0xd5, 0x4b, 0xa8, 0x09, 0xb0, 0xff, 0x12, 0x87, 0x6c, 0x62, 0xfb,
	0xfe, 0x54, 0x57, 0xf9, 0xbc, 0x3b, 0xa1, 0x8c, 0x04, 0xde, 0x6b, 0xec, 0xea, 0xe5, 0xed, 0x3f,
	0x28, 0x50, 0x4b, 0x12, 0x87, 0x5b, 0x3f, 0x24, 0x21, 0xd6, 0x97, 0xf8, 0x68, 0x97, 0x10, 0x5f,
	0x57, 0xf8, 0xa8, 0x17, 0xb2, 0x7b, 0x7a, 0x09, 0xd5, 0x61, 0xb9, 0x17, 0xb2, 0x6f, 0xdf, 0xd5,
	0xd5, 0x78, 0x78, 0x7b, 0x47, 0x2f, 0xc7, 0xc3, 0xbb, 0x1f, 0xeb, 0xcb, 0x7c, 0x78, 0xe0, 0x13,
	0x9b, 0xe9, 0xc0, 0x37, 0xb7, 0x47, 0x26, 0x43, 0x1f, 0xeb, 0x5a, 0xbc, 0x51, 0x2f, 0x1c, 0xe9,
	0x1b, 0x7c, 0x6f, 0xc7, 0x76, 0xd4, 0x3d, 0xb5, 0x23, 0xfd, 0x1d, 0xa4, 0x43, 0x63, 0xd7, 0x0b,
	0xed, 0x68, 0x7a, 0x8c, 0x1d, 0x46, 0x22, 0xdd, 0xe5, 0x20, 0x0b, 0x0d, 0x31, 0x01, 0x6f, 0x1f,
	0x03, 0x64, 0xc1, 0xcf, 0x05, 0xc4, 0x4c, 0xfe, 0xad, 0xb8, 0xfa, 0x12, 0x0f, 0x9e, 0x8c, 0xc2,
	0x4d, 0x28, 0x29, 0x69, 0x2f, 0x22, 0xe3, 0x31, 0x27, 0x95, 0x52, 0x39, 0x41, 0xc2, 0xae, 0xae,
	0xee, 0xfc, 0xbb, 0x0c, 0xeb, 0x4f, 0x44, 0x38, 0xcb, 0x48, 0xe9, 0xe3, 0xe8, 0xa5, 0xe7, 0x60,
	0xe4, 0x40, 0x23, 0xff, 0x71, 0x83, 0x8a, 0xdb, 0xe7, 0x82, 0xbf, 0x9d, 0xad, 0x0f, 0x2f, 0x7b,
	0x18, 0xc7, 0x19, 0xd1, 0x5e, 0x42, 0x3f, 0x83, 0x7a, 0xfa, 0xa5, 0x81, 0x8a, 0x3f, 0xfd, 0xe7,
	0xbf, 0x3c, 0xde, 0x44, 0xfd, 0x10, 0xb4, 0xdc, 0x77, 0x01, 0x2a, 0x96, 0x3c, 0xfb, 0x5d, 0xb1,
	0xd5, 0xb9, 0x9c, 0x31, 0xb5, 0x81, 0xa1, 0x91, 0x7f, 0x89, 0x9f, 0x83, 0x53, 0xc1, 0x17, 0xc0,
	0xd6, 0x8d, 0x05, 0x38, 0x53, 0x33, 0xa7, 0xb0, 0x32, 0xd3, 0x28, 0xa0, 0x1b, 0x0b, 0x3f, 0x5b,
	0xb7, 0xb6, 0x17, 0x61, 0x4d, 0x2d, 0x8d, 0x00, 0xb2, 0xbe, 0x03, 0x7d, 0x74, 0x9e, 0x53, 0x0a,
	0x1a, 0x93, 0x37, 0x33, 0xb4, 0xfb, 0xdd, 0x4f, 0xbf, 0x33, 0xf2, 0xd8, 0xe9, 0x64, 0x78, 0xd3,
	0x21, 0xc1, 0xad, 0xd7, 0x9e, 0xef, 0x7b, 0xaf, 0x19, 0x76, 0x4e, 0x6f, 0x49, 0x25, 0xdf, 0x92,
	0xe2, 0xb7, 0x1c, 0x12, 0xe1, 0x5b, 0x42, 0xe1, 0x2d, 0x49, 0x19, 0x0f, 0x87, 0x15, 0x31, 0xbf,
	0xfd, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x66, 0x92, 0x53, 0x69, 0x17, 0x1c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MilvusBackupServiceClient is the client API for MilvusBackupService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MilvusBackupServiceClient interface {
	// Create backup
	CreateBackup(ctx context.Context, in *CreateBackupRequest, opts ...grpc.CallOption) (*BackupInfoResponse, error)
	// Get backup with the chosen name
	GetBackup(ctx context.Context, in *GetBackupRequest, opts ...grpc.CallOption) (*BackupInfoResponse, error)
	// List backups that contains the given collection name, if collection is not given, return all backups in the cluster
	ListBackups(ctx context.Context, in *ListBackupsRequest, opts ...grpc.CallOption) (*ListBackupsResponse, error)
	// Delete backup by given backup name
	DeleteBackup(ctx context.Context, in *DeleteBackupRequest, opts ...grpc.CallOption) (*DeleteBackupResponse, error)
	// Restore backup to milvus, return backup restore report
	RestoreBackup(ctx context.Context, in *RestoreBackupRequest, opts ...grpc.CallOption) (*RestoreBackupResponse, error)
	// Get restore state by given id
	GetRestore(ctx context.Context, in *GetRestoreStateRequest, opts ...grpc.CallOption) (*RestoreBackupResponse, error)
}

type milvusBackupServiceClient struct {
	cc *grpc.ClientConn
}

func NewMilvusBackupServiceClient(cc *grpc.ClientConn) MilvusBackupServiceClient {
	return &milvusBackupServiceClient{cc}
}

func (c *milvusBackupServiceClient) CreateBackup(ctx context.Context, in *CreateBackupRequest, opts ...grpc.CallOption) (*BackupInfoResponse, error) {
	out := new(BackupInfoResponse)
	err := c.cc.Invoke(ctx, "/milvus.proto.backup.MilvusBackupService/CreateBackup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *milvusBackupServiceClient) GetBackup(ctx context.Context, in *GetBackupRequest, opts ...grpc.CallOption) (*BackupInfoResponse, error) {
	out := new(BackupInfoResponse)
	err := c.cc.Invoke(ctx, "/milvus.proto.backup.MilvusBackupService/GetBackup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *milvusBackupServiceClient) ListBackups(ctx context.Context, in *ListBackupsRequest, opts ...grpc.CallOption) (*ListBackupsResponse, error) {
	out := new(ListBackupsResponse)
	err := c.cc.Invoke(ctx, "/milvus.proto.backup.MilvusBackupService/ListBackups", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *milvusBackupServiceClient) DeleteBackup(ctx context.Context, in *DeleteBackupRequest, opts ...grpc.CallOption) (*DeleteBackupResponse, error) {
	out := new(DeleteBackupResponse)
	err := c.cc.Invoke(ctx, "/milvus.proto.backup.MilvusBackupService/DeleteBackup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *milvusBackupServiceClient) RestoreBackup(ctx context.Context, in *RestoreBackupRequest, opts ...grpc.CallOption) (*RestoreBackupResponse, error) {
	out := new(RestoreBackupResponse)
	err := c.cc.Invoke(ctx, "/milvus.proto.backup.MilvusBackupService/RestoreBackup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *milvusBackupServiceClient) GetRestore(ctx context.Context, in *GetRestoreStateRequest, opts ...grpc.CallOption) (*RestoreBackupResponse, error) {
	out := new(RestoreBackupResponse)
	err := c.cc.Invoke(ctx, "/milvus.proto.backup.MilvusBackupService/GetRestore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MilvusBackupServiceServer is the server API for MilvusBackupService service.
type MilvusBackupServiceServer interface {
	// Create backup
	CreateBackup(context.Context, *CreateBackupRequest) (*BackupInfoResponse, error)
	// Get backup with the chosen name
	GetBackup(context.Context, *GetBackupRequest) (*BackupInfoResponse, error)
	// List backups that contains the given collection name, if collection is not given, return all backups in the cluster
	ListBackups(context.Context, *ListBackupsRequest) (*ListBackupsResponse, error)
	// Delete backup by given backup name
	DeleteBackup(context.Context, *DeleteBackupRequest) (*DeleteBackupResponse, error)
	// Restore backup to milvus, return backup restore report
	RestoreBackup(context.Context, *RestoreBackupRequest) (*RestoreBackupResponse, error)
	// Get restore state by given id
	GetRestore(context.Context, *GetRestoreStateRequest) (*RestoreBackupResponse, error)
}

// UnimplementedMilvusBackupServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMilvusBackupServiceServer struct {
}

func (*UnimplementedMilvusBackupServiceServer) CreateBackup(ctx context.Context, req *CreateBackupRequest) (*BackupInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBackup not implemented")
}
func (*UnimplementedMilvusBackupServiceServer) GetBackup(ctx context.Context, req *GetBackupRequest) (*BackupInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBackup not implemented")
}
func (*UnimplementedMilvusBackupServiceServer) ListBackups(ctx context.Context, req *ListBackupsRequest) (*ListBackupsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBackups not implemented")
}
func (*UnimplementedMilvusBackupServiceServer) DeleteBackup(ctx context.Context, req *DeleteBackupRequest) (*DeleteBackupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBackup not implemented")
}
func (*UnimplementedMilvusBackupServiceServer) RestoreBackup(ctx context.Context, req *RestoreBackupRequest) (*RestoreBackupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestoreBackup not implemented")
}
func (*UnimplementedMilvusBackupServiceServer) GetRestore(ctx context.Context, req *GetRestoreStateRequest) (*RestoreBackupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRestore not implemented")
}

func RegisterMilvusBackupServiceServer(s *grpc.Server, srv MilvusBackupServiceServer) {
	s.RegisterService(&_MilvusBackupService_serviceDesc, srv)
}

func _MilvusBackupService_CreateBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MilvusBackupServiceServer).CreateBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.proto.backup.MilvusBackupService/CreateBackup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MilvusBackupServiceServer).CreateBackup(ctx, req.(*CreateBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MilvusBackupService_GetBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MilvusBackupServiceServer).GetBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.proto.backup.MilvusBackupService/GetBackup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MilvusBackupServiceServer).GetBackup(ctx, req.(*GetBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MilvusBackupService_ListBackups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBackupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MilvusBackupServiceServer).ListBackups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.proto.backup.MilvusBackupService/ListBackups",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MilvusBackupServiceServer).ListBackups(ctx, req.(*ListBackupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MilvusBackupService_DeleteBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MilvusBackupServiceServer).DeleteBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.proto.backup.MilvusBackupService/DeleteBackup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MilvusBackupServiceServer).DeleteBackup(ctx, req.(*DeleteBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MilvusBackupService_RestoreBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MilvusBackupServiceServer).RestoreBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.proto.backup.MilvusBackupService/RestoreBackup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MilvusBackupServiceServer).RestoreBackup(ctx, req.(*RestoreBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MilvusBackupService_GetRestore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRestoreStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MilvusBackupServiceServer).GetRestore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/milvus.proto.backup.MilvusBackupService/GetRestore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MilvusBackupServiceServer).GetRestore(ctx, req.(*GetRestoreStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MilvusBackupService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "milvus.proto.backup.MilvusBackupService",
	HandlerType: (*MilvusBackupServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBackup",
			Handler:    _MilvusBackupService_CreateBackup_Handler,
		},
		{
			MethodName: "GetBackup",
			Handler:    _MilvusBackupService_GetBackup_Handler,
		},
		{
			MethodName: "ListBackups",
			Handler:    _MilvusBackupService_ListBackups_Handler,
		},
		{
			MethodName: "DeleteBackup",
			Handler:    _MilvusBackupService_DeleteBackup_Handler,
		},
		{
			MethodName: "RestoreBackup",
			Handler:    _MilvusBackupService_RestoreBackup_Handler,
		},
		{
			MethodName: "GetRestore",
			Handler:    _MilvusBackupService_GetRestore_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backup.proto",
}
