// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package restore

import (
	mock "github.com/stretchr/testify/mock"

	"github.com/zilliztech/milvus-backup/internal/collref"
)

// NewMockCollMapper creates a new instance of MockCollMapper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCollMapper(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCollMapper {
	mock := &MockCollMapper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCollMapper is an autogenerated mock type for the CollMapper type
type MockCollMapper struct {
	mock.Mock
}

type MockCollMapper_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCollMapper) EXPECT() *MockCollMapper_Expecter {
	return &MockCollMapper_Expecter{mock: &_m.Mock}
}

// TargetNames provides a mock function for the type MockCollMapper
func (_mock *MockCollMapper) TargetNames(collRef collref.Name) []collref.Name {
	ret := _mock.Called(collRef)

	if len(ret) == 0 {
		panic("no return value specified for TargetNames")
	}

	var r0 []collref.Name
	if returnFunc, ok := ret.Get(0).(func(collref.Name) []collref.Name); ok {
		r0 = returnFunc(collRef)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]collref.Name)
		}
	}
	return r0
}

// MockCollMapper_TargetNames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TargetNames'
type MockCollMapper_TargetNames_Call struct {
	*mock.Call
}

// TargetNames is a helper method to define mock.On call
//   - collRef collref.Name
func (_e *MockCollMapper_Expecter) TargetNames(collRef any) *MockCollMapper_TargetNames_Call {
	return &MockCollMapper_TargetNames_Call{Call: _e.mock.On("TargetNames", collRef)}
}

func (_c *MockCollMapper_TargetNames_Call) Run(run func(collRef collref.Name)) *MockCollMapper_TargetNames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 collref.Name
		if args[0] != nil {
			arg0 = args[0].(collref.Name)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCollMapper_TargetNames_Call) Return(collRefs []collref.Name) *MockCollMapper_TargetNames_Call {
	_c.Call.Return(collRefs)
	return _c
}

func (_c *MockCollMapper_TargetNames_Call) RunAndReturn(run func(collRef collref.Name) []collref.Name) *MockCollMapper_TargetNames_Call {
	_c.Call.Return(run)
	return _c
}
