// Code generated by "stringer -type=Format"; DO NOT EDIT.

package backup

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FormatAuto-0]
	_ = x[FormatBinlog-1]
	_ = x[FormatSnapshot-2]
}

const _Format_name = "FormatAutoFormatBinlogFormatSnapshot"

var _Format_index = [...]uint8{0, 10, 22, 36}

func (i Format) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Format_index)-1 {
		return "Format(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Format_name[_Format_index[idx]:_Format_index[idx+1]]
}
