# Configures the system log output.
log:
  level: info # Only supports debug, info, warn, error, panic, or fatal. Default 'info'.
  console: true # whether print log to console
  file:
    filename: "logs/backup.log"

http:
  simpleResponse: true

# Zilliz Cloud config.
# If you want to migrate data to Zilliz Cloud, you need to configure the following parameters.
# Otherwise, you can ignore it.
cloud:
  address: https://api.cloud.zilliz.com
  apikey: <your-api-key>

# milvus proxy address, compatible to milvus.yaml
milvus:
  address: localhost
  port: 19530
  user: "root"
  password: "Milvus"

  # tls mode values [0, 1, 2]
  # 0 is close, 1 is one-way authentication, 2 is mutual authentication
  tlsMode: 0
  # tls cert path for validate server, will be used when tlsMode is 1 or 2
  caCertPath: ""
  serverName: ""
  # mutual tls cert path, for server to validate client.
  # Will be used when tlsMode is 2
  # for backward compatibility, if not set, will use tlsmode 1.
  # WARN: in future version, if user set tlsmode 2, but not set mtlsCertPath, will cause error.
  mtlsCertPath: ""
  mtlsKeyPath: ""

  # Milvus replicate msg channel name, default is by-dev-replicate-msg
  rpcChannelName: "by-dev-replicate-msg"

  storage:
    provider: "azure"
    address: core.windows.net
    port: 443
    region: "westus2"
    accessKeyID: ""
    secretAccessKey: ""
    token: ""
    useSSL: true
    useIAM: false
    iamEndpoint: ""
    bucketName: "milvus-data"
    rootPath: "milvus/azure-instance"

backup:
  storage:
    provider: "azure"
    address: core.windows.net
    port: 443
    region: "westus2"
    accessKeyID: ""
    secretAccessKey: ""
    token: ""
    useSSL: true
    useIAM: false
    iamEndpoint: ""
    bucketName: "milvus-data"
    rootPath: "backup"

  concurrency:
    collections: 4
    segments: 1024

  # Pause GC during backup through Milvus Http API.
  gcPause:
    enable: true
    address: http://localhost:9091

restore:
  concurrency:
    collections: 2
    importJobs: 768
  keepTempFiles: false

transfer:
  mode: auto
  concurrency: 128
  multipartCopyThresholdMiB: 500
